src/layouts/EditImage.jsx
This fixes the SVG preview issue mentioned in #8.
SVGs can now be previewed with the additional `<img>` tag. The initial
tag is left there for previews regarding `png/jpg` image.
=> fix: preview SVGs

src/layouts/EditCollectionPage.jsx, src/layouts/EditFile.jsx, src/layouts/EditImage.jsx, src/layouts/EditPage.jsx, src/templates/LeftNavPage.jsx, src/templates/pageComponents/LeftNav.jsx, src/utils.js
**Overview**
When renaming files, we saved to state improperly (`this.newFileName = node`). This has been fixed so that we use `this.setState({ tempFileName: event.target.value })` 
**Bug fix**
The prop `leftNavPages` in `EditCollectionPage` was validated as an object even though it is returned as an array of objects. Proptype validation was corrected to reflect that.
=> Use this.setState to set newFileName 

src/layouts/Images.jsx
Initially, the image upload function would get called immediately after the page loads even
when the button was not clicked. Here was why:
So the issue arises from the way the `uploadImage` function is passed in the
`onClick` prop of the upload button. How onClick basically works is that
it accepts a function definition and then carries out that function definition when the
the click event occurs. What we were passing initially was actually the
returned value from calling `uploadImage` and not it's function definition.
So when the button gets clicked, `onClick` would try to call that returned
value but since `uploadImage` does not return anything, nothing happens
and we just get a really buggy behaviour.
=> fix: make image upload predictable

src/components/PageCard.jsx, src/layouts/Pages.jsx, src/utils.js
This PR addresses https://github.com/isomerpages/isomercms-frontend/issues/43. This PR should be reviewed after https://github.com/isomerpages/isomercms-frontend/pull/42.
Users can now:
- edit the page settings (title, permalink)
- delete an existing page
A similar title caching mechamism was implemented to PR for the Pages page as described in the [Resource Room](https://github.com/isomerpages/isomercms-frontend/pull/42).
=> allow users to modify page frontmatter from Pages page

package-lock.json, package.json, public/index.html, src/App.jsx, src/components/ResourceCard.jsx, src/components/ResourceCategoryModal.jsx, src/layouts/EditCollectionPage.jsx, src/layouts/EditPage.jsx, src/layouts/EditResourcePage.jsx, src/layouts/Resources.jsx, src/templates/ResourceCard.jsx, src/templates/pageComponents/LeftNav.jsx, src/utils.js
This PR adds the resource room functionality to the frontend (https://github.com/isomerpages/isomercms-frontend/issues/26). 
The image below is the InVision design for the resource room. 
In order to display the `title`, `post-type`, and `date`, the frontend would need to retrieve the data in the frontmatter of each resource page.
However, this means the backend would have had to call many GitHub APIs:
- 1 API call to list directory in the `resources` folder, and then
- 1 API call for each directory to list the names of all files in the directory, and then
- 1 API call for each file to retrieve the front matter.
If there were on average `m` directories and `n` files in each directory, the frontend would have to call `mn+1` GitHub APIs, which could take a really long time. 
Instead, we can …
=> Add basic resource room functionality

src/App.jsx, src/components/CollectionPageSettingsModal.jsx, src/components/Sidebar.jsx, src/layouts/EditCollectionPage.jsx, src/layouts/Pages.jsx, src/utils.js
This PR does the following:
1) Removes `Collections` tab and displays the displaced collection pages in the `Pages` tab instead
2) Introduces a new modal for editing the frontmatter of the collection pages (`CollectionPagesSettingsModal`)
3) Users who click on the page cards of collection pages will still be directed to edit on the `/sites/:siteName/collections/:collectionName/:pageName` endpoint instead of the default `/sites/:siteName/pages/:pageName` endpoint.
**NOTE**
This is a pull request that needs to be merged along with the [PR](https://github.com/isomerpages/isomercms-backend/pull/31) for the backend or else it will break.
=> BREAKING CHANGE: Include collection pages in the `Pages` tab

src/layouts/Sites.jsx, src/styles/isomer-cms/pages/Sites.module.scss
This PR styles the Sites title on the Sites page so that it looks like the following:
=> style: create class for sites section title

src/App.jsx, src/components/Sidebar.jsx, src/layouts/Files.jsx, src/layouts/Images.jsx, src/layouts/Media.jsx
This PR accomplishes the following objectives:
- Create a `Media` option in the `Sidebar` which contains links to `Images` and `Files`
- Remove `Images` and `Files` from the `Sidebar`
- Implement `Pages`-like styling for both the `Images` and `Files` pages
=> [Feat] Implement media page

src/styles/isomer-cms/pages/Editor.module.scss, src/styles/isomer-template.scss
This PR fixes the homepage styling to keep the preview consistent across
Small:
different window sizes
Large:
=> style: fix homepage editor styling

src/layouts/EditHomepage.jsx
This PR sets up the header for EditHomepage. It also lints the file.
=> feat: set up EditHomepage header elements

src/styles/isomer-cms/elements/base.scss
=> fix: make background cover entire page height

src/layouts/Pages.jsx, src/layouts/Resources.jsx
This PR improves the UX for page loading in Pages and Resources. 
At present, some page elements  that the user should not be able to interact with are displayed while the page is still loading. This PR hides these page elements and only displays them when the page is fully loaded.
=> feat: improve loading ux

src/styles/isomer-cms/elements/base.scss
This PR fixes the letter spacing issue caused by the isomer-template CSS. At present, the isomer template CSS lives in a `.css` file, which means that the styles get applied to all HTML elements in the CMS as well.
As a result, the letter spacing in the header segment looks too tightly packed (see below).
To overcome this issue, we could rewrite the isomer template CSS into React scoped CSS, but that would take some time. Instead, as a stop gap measure, I propose adding a `letter-spacing: 0px !important` to override the letter-spacing imposed by the isomer template CSS.
=> style: fix letter spacing issue caused by isomer-template CSS

src/utils/validators.js
The HLB staging site has many permalinks linking out to external sites. Because our permalink/URL validation only works for internal links (i.e. links to other parts of the same Isomer website), the use of permalinks will fail the validation in our CMS user test.
I propose to disable permalink validation on the Homepage until we have completed a more sophisticated permalink validation function.
=> fix: remove validation for permalinks on the homepage page

src/layouts/EditNav.jsx
This PR adds the correct Header title and back button to the Main Menu page.
=> fix: add correct main menu header elements

src/components/PageSettingsModal.jsx
This PR fixes https://github.com/isomerpages/isomercms-frontend/issues/92.
The bug exists because `newFileName !== fileName`, since `newFileName` is undefined when creating a new file. The fix is to add another condition to the statement that checks if the user is trying to create a new file.
=> fix: remove DELETE API call when creating new page

src/components/NavigationPreview.jsx, src/styles/isomer-template.scss
Currently, the EditNav preview disappears when the window size is small.
This PR will make the navigation preview in the EditNav page visible even when the window size is small.
=> fix: make EditNav preview mobile responsive

src/utils.js
Currently, we parse content by splitting on `---` to obtain the front matter and assume that there are no other `---` blocks in the content. However, if there exists another `---` block in the content part of the markdown file, we will lose all content after that `---`. This PR fixes that.
=> fix: modify markdown parsing logic

src/components/Sidebar.jsx
This PR flattens the media tab and replaces it with it's children (files' and 'images'). Here are the visual changes.
Before:
After:
=> [Feat] Flatten media tab

src/components/ResourceSettingsModal.jsx, src/styles/isomer-cms/elements/form.scss, src/utils/validators.js
This PR replaces the button to switch resource types in the resource settings modal into
radio buttons as users were confused by the button during round 2 of
user tests. Here's a preview of the change:
=> feat: add radio button to switch resource types

src/components/ResourceSettingsModal.jsx
This PR fixes the bug in the resource settings modal where users cannot change the resource category of an existing post.
This bug occurs because the `saveHandler` method does not track the previous category of the post. Take for example a post with the category `foo`. When a user clicks on the Resource Settings modal and changes the category to `bar`, line 142 (of the previous `ResourceSettingsModal.jsx` code) attempts to delete the old file belonging to the Resource Category: `bar`. However, the resource file does not exist.
Track the `prevCategory` so that the `saveHandler` method correctly deletes the previous resource file.
=> fix: allow users to change category of existing post

src/components/ImageSettingsModal.jsx, src/components/ImagesModal.jsx, src/layouts/EditPage.jsx
This PR achieves a couple of things:
1. It allows the user to rename an image before uploading an image in the `EditPage` component (previously implemented for the `Images` tab in #105).
2. It refactors the `ImageModal` component to be a React `PureComponent`. This provides performance benefits when rendering newly uploaded images. We can use `PureComponent` because the shallow comparison performed by `PureComponent` (which only compares references for objects/nested state) is sufficient because we do not and will not allow users to replace the content of an image while retaining the file name. 
This functionality is facilitated by storing `images` in the parent `EditPage` instead of inside `ImageModal`. If `images` were stored inside `ImageModal`, we would need to define a modal inside a …
=> [feat] Allow rename before image upload in EditPage, refactor ImageModal

src/layouts/EditPage.jsx, src/layouts/Pages.jsx
The settings icon in the pages tab will no longer triggers someone's OCD.
=> center settings icon in page cards

src/components/ImageSettingsModal.jsx, src/components/ImagesModal.jsx, src/layouts/EditPage.jsx, src/layouts/Images.jsx, src/styles/isomer-cms/pages/Media.module.scss
This PR accomplishes the following:
- Introduce selection functionality in `ImagesModal`
- Introduces a fix to the bug described in #125 
Previously in `EditPage`, when selecting an image in `ImagesModal`, the image would be selected on click. Now, users have to click on the image first and then click on the select button.
**Still considering**: I'm wondering if we should keep `ImagesModal` as a `PureComponent` or if we should delegate the `selectedImage` state to `ImagesModal` and make it a functional component. Thoughts?
=> [Feat - EditPage, ImagesModal] Highlight selected image

src/layouts/Resources.jsx
This PR reduces the resource card setting icon hitbox.
=> fix(resource-card): reduce setting icon hitbox

src/layouts/Settings.jsx
**Note:** This PR is to be reviewed together with PR #[60](https://github.com/isomerpages/isomercms-backend/pull/60) on the backend repo.
This PR accomplishes several things:
1. Updates the `Settings` layout to read from the updated backend response, which now sends footer-related content from the repo's `_data/footer.yml` file instead of just social media content from the repo's `_data/social-media.yml` file. 
2. Allow users to edit the new footer fields available: `Contact Us`, `Show Reach`, `Feedback`, and `Faq`
=> fix: update Settings page to read from updated backend response

src/components/Header.jsx
This PR fixes an issue with a non-existent endpoint being called when the logout button is clicked. The button now calls the appropriate endpoint, removes the user's existing cookie, and redirects the user to the login page. To be reviewed with PR #[59](https://github.com/isomerpages/isomercms-backend/pull/59) on the isomercms-backend repo.
=> Fix: handle behaviour on logout

src/layouts/EditResourcePage.jsx, src/layouts/Resources.jsx, src/styles/isomer-cms/elements/header.scss, src/styles/isomer-cms/pages/Editor.module.scss, src/styles/isomer-template.scss, src/templates/LeftNavPage.jsx, src/templates/SimplePage.jsx, src/templates/pageComponents/Breadcrumb.jsx, src/utils.js
This PR fixes the issue raised in Issue #137. Currently, the display issue exists because the styling for those components were mistakenly given a right offset value instead of a left offset value. To decrease the chances of this occurring in future, the styling has also been refactored out into a separate css class, and the offset has been changed to padding instead. This PR also fixes an issue with the display exceeding the width of the screen.
In addition, this PR also adds in the date to the breadcrumb on resource pages, as raised in Issue #165. The date formatting has also been changed to match the display on the actual website.
The title and breadcrumb have also been modified to be truncated if their length is too long.
=> Fix: display issue for breadcrumb

src/utils/validators.js
This PR fixes a simple image filename validation bug. Currently, file names which contain more than one full stop, such as
'Screenshot 2020-10-28 at 10.51.26 PM.png' are provided with the current error message: `Invalid filename: filename must end with a valid file extension (.JPG, .png, .pdf, etc.)`
However, this is not an accurate descriptor of the problem. This commit creates a separate error message for situations where there are more than one full stop in the filename. The new error message now reads: `Invalid filename: filename can only contain one full stop and must follow the structure {name}.{extension}`
=> fix: image filename validation bug

src/components/media/MediaSettingsModal.jsx, src/layouts/Files.jsx, src/layouts/Images.jsx
This PR fixes a simple bug where the `onSave` prop was missing for the `MediaSettingsModal` in the `Images` layout. This led to the following error message:
```
Unhandled Rejection (TypeError): onSave is not a function
```
This PR fixes that by defining the `onSave` prop so the `Images` layout is reloaded when a new image is uploaded. It also sets the `onSave` prop as a required prop type.
=> fix: missing `onSave` prop for MediaSettingsModal in Images layout

src/components/ProtectedRoute.jsx, src/layouts/AuthCallback.jsx
This PR fixes a bug which was introduced in PR #189 
Previously, on the `AuthCallback` component, we set the login state to be true and immediately returned a redirect to the `/sites` page. The problem with this is that it's possible that the redirection occurs before the login state is set.
This PR makes the changes to redirect only AFTER login state has been set by introducing a `shouldRedirectToSites` hook, which the redirection is dependent on.
Note that we currently use a context string, `#isomercms`, to filter access to the `AuthCallback` component. If this filter string is not present, the component will not be accessible.
This leads to a small bug. If the user attempts to access `/auth#isomercms`, they will be presented with the following screen and logged out. We can fix this in …
=> fix: redirect to /sites only after login state changes to true

src/components/ProtectedRoute.jsx, src/layouts/AuthCallback.jsx
This PR adds the missing `isLoggedIn` prop to wrapped component inside `ProtectedRoute`.
It also ensures that the `setLogin` callback is run if the login state is false.
=> hotfix: add missing `isLoggedIn` prop

src/utils/cookieChecker.js
Currently, we initialize `isLoggedIn` checking for the existence of an `isomercms` cookie. If the cookie exists, we fail to write to it and the number of cookies doesn't increase. Then, we can initialize `isLoggedIn` to be true. If it doesn't exist, then it creates a new `isomercms` cookie with the value `new_value`.
The problem with this is if the redirection occurs too quickly, then the app attempts to make an api call to the backend with the invalid `isomercms` cookie, instead of the one it receives from the backend, resulting in an auto-logout. This commit fixes that by removing the cookie immediately after it's written and the check is made.
=> fix: do not set cookie when checking for isomercms cookie

src/utils.js
In a previous change, the `prevCategory` variable was renamed to `originalCategory`. This variable is passed down as a function argument to the `saveAndRetrieveUrl` function, but we forgot to change the reference to `prevCategory` from within the function, resulting in failed API calls.
This commit fixes that typo by renaming all instances of `prevCategory` to `originalCategory`.
=> fix: rename prevCategory to originalCategory

src/components/HyperlinkModal.jsx, src/layouts/EditPage.jsx, src/utils/markdownToolbar.jsx
This PR addresses issue #194, creating a popup modal when users click on the link button for the users to populate. The popup modal is previewed as below, and will take selected text (if any) as input to the text form field, otherwise the form field has a default value of "".
The look of the hyperlink modal above has been approved by the designers, but we are still discussing whether something similar can be applied to inserting alt-text for images. That change can be applied in a future PR as this seems like it would take more significant research.
Depending on the discussion for image alt-text, it might be worth considering if we should create a more general popup modal to subclass.
=> feat: adds hyperlink modal to prompt users for input text and link

src/templates/pageComponents/LeftNav.jsx
This PR fixes a bug where editing pages with third navs was extremely laggy. This was due to the way we generated the third nav data - editing anything in the page caused a rerender of the third nav as well, which was computationally expensive. This PR fixes this by generating the the third nav data once upon loading only, to prevent unnecessary rerendering.
=> Fix: prevent re-render of third nav component

src/layouts/EditPage.jsx, src/styles/isomer-cms/pages/Editor.module.scss
This PR addresses issue #233 
Currently, when users enter the EditPage layout, they can enter text into the EasyMDE editor right away. However, whatever content they enter will be replaced when the page content finally loads. This is a bad UI experience and this commit seeks to change that by blocking access to the editor until all page content has loaded.
There is no native way of masking the EasyMDE editor that we're using (refer to the issue on their repo https://github.com/Ionaru/easy-markdown-editor/issues/49) so we need to manually apply a mask to prevent the user from editing content until the page content is loaded.
**Loading**
**After load**
Do we need to add some kind of feedback on the page preview side? Or is the loading spinner on the editor sufficient?
=> feat: mask markdown editor until page content has loaded

src/layouts/EditHomepage.jsx
This PR fixes the bug raised in issue https://github.com/isomerpages/isomercms-frontend/issues/267. The reason for this issue was our assumption that a page had either a dropdown or highlights - given the relaxation of compulsory fields in the hero section, it became possible for a page to have neither, in which case our error initialization was not performed correctly. This PR fixes that issue by checking for this case.
=> Fix: proper intialization of section errors

src/layouts/EditHomepage.jsx
This PR addresses issue #239.
Currently, there are multiple instances in the `EditHomepage` layout where state was being indirectly set by referencing the state object directly. Refer to issue #239 for more details. This PR fixes that by ~referencing a deep-copied version of the state object instead of the state object itself~ using `immutability-helper` to update the state instead.
=> fix: set state directly in EditHomepage

src/components/media/MediaSettingsModal.jsx
This PR adds handling for the PayloadTooLargeError in the MediaSettingsModal. To be reviewed with PR#[94](https://github.com/isomerpages/isomercms-backend/pull/94) on the isomercms-backend repo. This PR attempts to resolve https://github.com/isomerpages/isomercms-frontend/issues/226.
=> Fix: add check for PayloadTooLargeError for media

src/utils.js
Currently, when saving data for resource pages, we enquote the title in anticipation of special characters in the title. However, this turns out to be unnecessary, and in fact, detrimental because our yaml library automatically enquotes strings which contains special characters. This manual enquoting results in a title string with two double quotes.
**Example**
This PR fixes that by removing the use of enquote string and letting the library do its work.
=> fix: remove use of enquote string

src/layouts/EditHomepage.jsx
This PR fixes a bug introduced by https://github.com/isomerpages/isomercms-frontend/pull/309/. Currently, the resources section cannot be saved when the button name is present, as the url for that section is always missing and hence results in an error. This PR fixes that by adding an additional check to ensure the section is not of type resources.
=> Fix: disable check for url for resources section

src/components/FolderCard.jsx, src/components/OverviewCard.jsx
Currently, when the CMS is run on a Firefox browser, the dropdown buttons for the `OverviewCard` and `FolderCard` are unresponsive - meaning, nothing happens when you click on them. @alexanderleegs  found that this was due to the differences in order in which event handlers are called on different browsers. In the case of Firefox, the `onClick` event is only called after the `blur` event is fired, which means that our buttons do not work, since we define our event handlers `onClick`. For reference: https://stackoverflow.com/questions/24635536/different-behavior-of-blur-event-in-different-browsers
The solution to this is to use the `onMouseDown` event instead of an `onClick` event, since the `onMouseDown` is fired before the `blur` event. For reference: …
=> fix: button handler is not called after blur event in Firefox

src/styles/isomer-template.scss
Currently, the markdown editor highlights spelling errors in red, which can be distracting. This commit overwrites the default red highlights with a less distracting dotted red line instead. 
This PR fixes #304.
**Before**
**After**
=> fix: modify editpage error class css to underline spelling errors

src/components/ComponentSettingsModal.jsx, src/components/FormField.jsx
This PR contains a small fix for the bug shown below where the error message runs onto the next form field, by creating a `<div></div>` tag to wrap the form fields. 
Before:
Fixed:
=> fix: creates div to wrap formfield

src/styles/isomer-cms/elements/card.scss
This PR fixes an issue with overly long titles, in order to resolve https://github.com/isomerpages/isomercms-frontend/issues/216. We truncate overly long titles to prevent the section cards from becoming too large.
=> fix: truncate long titles of cards

src/components/ComponentSettingsModal.jsx
This PR fixes a minor issue with the field title of the category field of the component settings modal.
Previously, we updated the title to reflect to users more clearly that they should be choosing categories to add to - however, this also resulted in the field title changing when editing details, which is a source of confusion. This PR introduces separate field titles depending on whether the user can select a field.
In addition, the placeholder text for the collection name when editing the details of unlinked pages has been changed to `Unlinked Page` instead of the previous `Select a category or create a new category...` to make it clearer to the user that the category cannot be edited from this modal.
=> Fix: show different messages for field for new pages and existing pages

src/layouts/EditHomepage.jsx, src/templates/homepage/HeroSection.jsx, src/templates/homepage/InfobarSection.jsx, src/templates/homepage/InfopicLeftSection.jsx, src/templates/homepage/InfopicRightSection.jsx, src/templates/homepage/ResourcesSection.jsx
This PR refactors the existing EditHomepage to use hooks instead of a class component. The reason for this is twofold:
- We want to implement a similar page to editHomepage for navigation
- We would like to use context to set site colours instead of how it's being done currently, however, we have a mix of class components and functional components currently, which prevents us from using the useContext hook
Of particular note is the change in rendering behaviour while loading the page data. Previously, we would display a blank version of the editHomepage.
**Previous**
However, I ran into some issues replicating this behaviour. Instead, this PR displays the following while loading the page info.
**After**
Also, this PR refactors the scrollRefs to be a state variable to be more consistent …
=> Refactor: editHomepage to use hooks

src/App.jsx, src/contexts/SiteColorsContext.js, src/hooks/useSiteColorsHook.jsx, src/layouts/EditContactUs.jsx, src/layouts/EditHomepage.jsx, src/layouts/EditPage.jsx, src/layouts/Workspace.jsx, src/utils/siteColorUtils.js
Currently, our app re-renders with a distracting flash when we retrieve an update a repo's site colors. 
_Gif demonstrating the problem_
_Upon reload of the page, it displays the default color palette and then flashes to the new color palette_
This is probably* because of a couple of reasons:
- site colors was stored as a state variable at the root app level, which causes a re-render of the root app
- even if we do not pass site colors as a prop, we use the `render` prop in our `ProtectedRoute` HOC, which causes a re-render of the layout component being passed to the HOC
This PR solves this problem by storing site colors in local storage instead. The site color reading and writing processes are abstracted into a custom hook, which greatly reduces the number of lines of code needed to …
=> Feat/update site colors without re-render

src/components/media/MediaModal.jsx, src/layouts/Images.jsx
This PR fixes 2 minor bugs involving the uploading of images.
- In the image tab, we placed a restriction on uploadable files to only a certain subset of images. This caused issues for users who wanted to upload a new favicon.
- In places which used `FormFieldMedia` to deal with image uploads, we only restrict the uploadable file to be of any image type. However, due to a typo (`image*` instead of `image/*`), there were no restrictions being placed on files uploaded in this way.
The two places where this could occur have both been changed to allow any type of image (`image/*`).
=> Fix: restriction of image files that can be uploaded

src/App.jsx, src/api.js, src/components/LoadingButtonReactQuery.jsx, src/layouts/EditNavBar.jsx, src/layouts/Folders.jsx
This PR refactors the `EditNavBar` layout to use `react-query`, in line with our recent PRs (#350, #357). The GET and POST API calls are now defined as functions within the `api.js` file, and we replace them with `useQuery` and `useMutation` in the `EditNavBar` code.
This PR also creates a new, simplified `LoadingButton` component that is compatible with `react-query`. `react-query` provides us with the loading state of our api call - this means we don't need to handle it ourselves within our `LoadingButton` component. The new button component simply receives an `isLoading` prop and renders a loading spinner and loading styles when `isLoading` is true.
=> refactor: use react-query for EditNavBar

src/api.js, src/components/CollectionPagesSection.jsx, src/components/FolderCreationModal.jsx, src/components/FolderNamingModal.jsx, src/components/LoadingButton.jsx, src/components/folders/FolderContent.jsx, src/constants.js, src/layouts/CategoryPages.jsx, src/layouts/EditNavBar.jsx, src/layouts/EditPage.jsx, src/layouts/Folders.jsx, src/layouts/Resources.jsx, src/layouts/Workspace.jsx, src/utils.js
This PR adds functionality for allowing empty folders, subfolders, and resource pages, as well as the associated changes required. To be reviewed in conjunction with PR #[137](https://github.com/isomerpages/isomercms-backend/pull/137) on the isomercms frontend repo. A discussion of the reasoning behind this change can be found [here](https://docs.google.com/document/d/1EccpS_ATrfOe4DmU4ChXtU9kV6Jl1rFOdKqBLyG6ym8/edit#).
The changes introduced in this PR are:
- Users can skip adding files to newly created folders/subfolders, allowing for the existence of empty folders
- The behaviour for handling empty subfolders and resource pages has been changed:
- Previously, if it was detected that no pages were returned from the backend, we would automatically redirect them to the workspace/resources …
=> Feat: empty folders, add resource category

package.json, src/utils.js
This PR replaces all use of the npm `js-yaml` library with the npm `yaml` ([link](https://www.npmjs.com/package/yaml)) library. This PR is accompanied by PR #[140](https://github.com/isomerpages/isomercms-backend/pull/140) on the backend.
The main reason for replacing `js-yaml` is because it is unable to handle certain characters, and throws a YAMLException error. An example string which it is unable to handle is: `Stairwells, walkways and fresh
food – making today’s cities healthier cities`, or in unicode, `Stairwells, walkways and fresh food â making todayâs cities healthier cities`
However, the `yaml` library is able to handle such strings. Although it does not have as many weekly downloads as the `js-yaml` library (27 million weekly downloads), it is still widely used (11 million …
=> feat/ replace js-yaml library with yaml library

src/components/LoadingButton.jsx, src/components/navbar/NavSection.jsx, src/layouts/EditContactUs.jsx, src/layouts/EditHomepage.jsx, src/layouts/EditNavBar.jsx, src/layouts/EditPage.jsx, src/layouts/Folders.jsx
This PR fixes an issue with EditNavBar regarding the handling of resource rooms for sites which do not have one. Previously, we always assumed that sites contained a resource room, which caused errors when attempting to retrieve the list of categories. This PR changes it such that we first check if a resource room exists. In addition, the option to create a link with a resource room has now been disabled if a site does not contain a resource room.
Also fixes a minor bug involving the `isEditPage` prop passed to `Header` being a string instead of a boolean.
=> Fix: disable creation of resource room link if user has no resource room

src/layouts/EditContactUs.jsx, src/layouts/EditHomepage.jsx, src/layouts/EditPage.jsx
This PR fixes a bug involving the editing of contact us pages. In line with the recent changes to page encoding on the backend (PR [#133](https://github.com/isomerpages/isomercms-backend/pull/133)), simple page encoding is now performed in the backend, so we were mistakenly encoding contact us pages twice. This has been corrected to send the data as is.
In addition, this PR also shifts the encoding/decoding to the backend. To be reviewed in conjunction with PR [#151](https://github.com/isomerpages/isomercms-backend/pull/151) on the isomercms-backend repo.
=> Fix: remove encoding in homepage and when saving edit contact us

src/layouts/Workspace.jsx
This PR makes the Workspace copy changes requested by designers in their CMS v1 review, 13 April ([link](https://docs.google.com/document/d/1_aC5FuHqSQqqWx0aOcpDFyw2iEk1vsCpDgt4fLQ1zck/edit#))
The list is also copied below for reference.
> Workspace
> [Copy changes] Change ‘Collections’ to ‘Folders’ (done)
> [Copy changes] Any mentions of ‘Collection’ should be ‘Folders (done)
> [Copy changes] Change ‘Unlinked Pages’ to ‘Pages’. And ‘Note: The pages here do not belong to any folders.’ (done)
=> fix: workspace copy changes for Collections > Folders

src/components/ComponentSettingsModal.jsx, src/components/FileMoveMenuDropdown.jsx, src/components/OverviewCard.jsx, src/components/PageSettingsModal.jsx, src/components/folders/FolderContent.jsx, src/layouts/CategoryPages.jsx, src/layouts/Folders.jsx, src/layouts/Resources.jsx
This PR makes the Resources copy changes requested by designers in their CMS v1 review, 13 April ([link](https://docs.google.com/document/d/1_aC5FuHqSQqqWx0aOcpDFyw2iEk1vsCpDgt4fLQ1zck/edit#)). 
Additionally, this PR applies the `deslugify` changes to category/ folder names to Resources, Folders and related components such as `ComponentSettingsModal`, `PageSettingsModal`, `FileMoveDropdown` etc.
The list is also copied below for reference.
> Resources Tab
> [Copy changes] Change ‘Resource Categories’ to just ‘Categories’ (done)
> [Copy changes] Button: Change to ‘Create new category’ (done)
> 
> [Copy changes] Can we standardise the category names to Title case instead of all CAPS (done)
> [Copy changes] At the category workspace, can we use the category name without hyphens i.e. ‘Media …
=> fix: resource copy changes

src/api.js, src/layouts/EditPage.jsx, src/templates/SimplePage.jsx, src/templates/pageComponents/Breadcrumb.jsx, src/templates/pageComponents/PageHeader.jsx
This PR adds `resourceRoomName` and `resourceName` as a breadcrumb for resource pages, so that the `EditPage` preview shows an accurate breadcrumb similar to that on the actual Isomer site. This PR should be reviewed with [#153](https://github.com/isomerpages/isomercms-backend/pull/153) on the backend.
=> fix: add resourceRoomName and resourceName to breadcrumb

src/components/Header.jsx, src/components/LoadingButton.jsx, src/components/SaveDeleteButtons.jsx, src/components/Sidebar.jsx, src/components/media/MediaSettingsModal.jsx, src/components/navbar/NavSection.jsx, src/components/navbar/NavSublinkSection.jsx, src/layouts/EditNavBar.jsx, src/layouts/EditPage.jsx, src/layouts/Settings.jsx, src/styles/isomer-cms/elements/base.scss, src/styles/isomer-cms/elements/card.scss, src/styles/isomer-cms/pages/Admin.module.scss
This PR fixes a range of UI issues brought up in the recent [UX review](https://docs.google.com/document/d/1_aC5FuHqSQqqWx0aOcpDFyw2iEk1vsCpDgt4fLQ1zck/edit#bookmark=id.tae0sux04cgu).
The changes made in this PR are:
- **Top Nav Bar**
- [Copy changes] Modal copy: Second sentence can change to ‘Refresh your staging site to see if your changes have been built’
- **Side Nav Bar**
- The Settings tab sets the sitename first, so there is no more jumping of the sidebar when moving to settings.
- The external link icons have been removed from Guide and Help
- The hover state for the logged in as tab has been removed
- **Images/Files Modal**
- [Copy changes] Modal title (it’s important for the title to reflect the intent of the task)
- When user is uploading a new image, modal title should say …
=> Fix/misc UI fixes

src/components/SaveDeleteButtons.jsx, src/components/media/MediaSettingsModal.jsx
This PR fixes 2 minor bugs:
- The loading spinner when uploading new files/images has been removed
- SaveDelete buttons now correctly take state of save/delete variable if specified
=> Fix: remove loading spinner for images/files which are being uploaded

src/routing/ProtectedRoute.jsx
This PR fixes a bug in which params given to the `ProtectedRoute` were not being passed to the wrapped component.
=> fix: pass parameters to wrapped components

src/layouts/Folders.jsx
This PR fixes two issues on the folders layout:
- Success toast pops up on selecting the item for settings even if no settings are adjusted
- Folder deletion does not work as the deletion modal does not appear
=> fix: fixes toast popup on item select, folder deletion modal

src/components/PageSettingsModal.jsx
This PR fixes a bug involving the creation of collection pages. Currently, when we create a new collection page, the third nav title placed into the front matter is unslugified, meaning that the display on the actual site also shows the unslugified version. This can result in 2 separate third nav categories:
To fix this, we unslugify the third-nav-title of the frontmatter on page creation.
Note that this only affects third nav page creation, as page movement correctly unslugifies the third nav title.
=> fix: third nav title on page creation

src/components/FolderModal.jsx
This PR fixes a minor bug where users could still save even if the renamed folder title was invalid.
=> Fix: disable save button for folder modal on error

src/components/ComponentSettingsModal.jsx
This bug fixes a small bug where upon file creation with title "Example Title", "Example Title" should be automatically postpended with "_1" if the title already exists. 
The bug was caused by checking for the uniqueness of the full resource post filename `{date}-{filetype}-{name}.md` as opposed to the uniqueness of just the `name` as we've now decided upon.
=> fix: duplicate resource title check for example_title

package-lock.json, package.json
On the current `develop` branch, there are 5991 reported vulnerabilities (172 moderate, 5819 high). This PR runs `npm audit fix` to fix most of those vulnerabilities, but there remain 80 vulnerabilities which require manual review. 
A separate issue #481 has been created to address the remaining vulnerabilities.
=> chore: update dependencies using `npm audit fix`

src/layouts/Settings.jsx
This PR fixes a minor issue in which social media links which did not exist in the footer.yml file would not show up in the settings page. To be reviewed in conjunction with PR #[184](https://github.com/isomerpages/isomercms-backend/pull/184) on the isomercms backend repo.
In addition, this PR also adds in the option for linkedin insights under the list of analytics in the settings tab.
Resolves #497
=> Fix: show social media links even if empty

.eslintIgnore, .eslintrc.json, .prettierignore, .prettierrc.json, package-lock.json, package.json
This PR reactivates our prettier code-formatting configs by adding the prettier  config files, and removing the catchall `*` in the ignore files for both eslint and prettier.
=> lint: code formatting

.env-example
Currently, when we attempt to start our react app, `create-react-app` fails to compile when there are any eslint or prettier errors. The reason for this is documented in this github issue: https://github.com/facebook/create-react-app/issues/9887#issuecomment-720902192
This issue is fixed with react-scripts v`4.0.2` with the use of an `ESLINT_NO_DEV_ERRORS` env var (this is documented under Create React App's advanced configuration here: https://create-react-app.dev/docs/advanced-configuration/)
This commit adds the `ESLINT_NO_DEV_ERRORS` env var to our env-example file. We will need to separately add it to our production and staging environments too.
=> fix: prevent eslint errors from blocking build

.gitignore, package.json
This PR adds `npm run dev` as a command to make running the CMS frontend consistent with that of the backend. The PR also sets the local env var file to `.env` to match that in the backend repo.
=> chore: set npm run dev 

package-lock.json, package.json, src/utils/validators.js
This PR addresses #494.
Currently, users are able to choose a resource date that's in the future. Since we currently do not have a cron job running to build sites regularly, we cannot trigger a rebuild when these resource pages are supposed to appear, hence the posts will not appear when users expect them to. 
For now, we have decided to disable future resource posts, and explore supporting this in the future.
=> fix: validates that resource page dates are not in future

.env-example, README.md, package-lock.json, package.json, scripts/run-e2e.js
This PR uses a node script to reset the `e2e-test-repo` state before running our e2e tests so that we don't have to do it manually.
As it stands, the repo is reset once before all e2e tests are run. This should be sufficient since our tests should not be dependent on side effects to pass (i.e. we shouldn't rely on the outputs of one of our tests for a subsequent test to pass).
=> test: reset e2e repo state

cypress/integration/editPage.spec.js, cypress/integration/files.spec.js, cypress/integration/images.spec.js, cypress/integration/pages.spec.js, cypress/support/medias.js, package-lock.json, package.json, src/components/DeleteWarningModal.jsx, src/components/FileMoveMenuDropdown.jsx, src/components/MenuDropdown.jsx
This PR patches some of our failing and flaky E2E tests. It fixes the following tests:
1. Failing delete test for `EditPage`
2. Failing delete tests using the `Folders` and `Media` layouts
3. Failing test for subfolder renaming
4. Flaky file-moving breadcrumbs
Other misc. changes:
- Eliminate extraneous `id` attribute in `DeleteWarningModal`
In the course of testing this PR, issue #526 (cleanup of uploaded assets during testing) was also filed, to be resolved in a subsequent PR.
**Problem**
Previously, the "Edit page should allow user to delete page" test failed because Cypress was unable to click on the delete button in the `DeleteWarningModal`. I suspect that this is because the modal takes some time to appear in the DOM.
**Solution**
To resolve this problem, we wait for the …
=> test: cleanup e2e tests

package-lock.json, package.json
This PR upgrades vulnerable dependencies:
- the majority of deps were upgraded using `npm audit fix`
- `node-sass` upgraded to 6.0.1 using `npm install node-sass@6.0.1`
- `marked` upgraded to 2.1.3 using `npm install marked@2.1.3`
=> fix: dependency upgrades

src/components/media/MediaModal.jsx, src/layouts/Media.jsx, src/styles/isomer-cms/pages/Content.module.scss
This PR fixes https://github.com/isomerpages/isomer-product/issues/27. It specifically does the following:
- update the `<input accept="<ACCEPTED INPUT>">` file types to match the file extensions explained in the issue
- sets the file restriction message for our admin users
=> feat: validate and sanitize media files

src/layouts/EditPage.jsx, src/layouts/EditPageV2.jsx
This PR is a hotfix to modify the configurations on DOMPurify to allow for iframes in EditPage. 
Currently, users are unable to insert Youtube videos and other embedded frames in EditPage as `iframes` are sanitised and removed by `DOMPurify.sanitize`.
This PR also applies `DOMPurify` to the refactored collectionPages flow as `DOMPurify` was accidentally removed during the refactor.
=> [hotfix to develop] Allow iframe objects in EditPage

README.md, netlify.toml
To test locally, set the following env vars:
```
export CYPRESS_COOKIE_NAME='isomercmsE2E'
export CYPRESS_COOKIE_VALUE='blahblahblah' // this value needs to match the value of the E2E_TEST_SECRET 
// env var in the backend
export CYPRESS_TEST_REPO_NAME='e2e-test-repo'
export CYPRESS_BASEURL="http://localhost:3000" // or whatever port you choose
```
This PR is to be reviewed with PR #[270](https://github.com/isomerpages/isomercms-backend/pull/270) on the backend.
This PR is part one of a two-part change which will allow us to automate our E2E tests. 
1. Allow us to run E2E tests locally without having to replace our login token
2. Allow us to automate E2E tests as part of the Netlify build process, using the `cypress-netlify-plugin` library
For more details, refer to this decision document …
=> test: e2e authentication

src/layouts/Settings.jsx
This PR adds functionality to allow the editing of the description field in the settings tab. To be reviewed in conjunction with PR [#280](https://github.com/isomerpages/isomercms-backend/pull/280) on the isomercms backend repo.
=> Feat: add description field to settings page

src/components/FormFieldColor.jsx
This PR resolves #646. It fixes an issue which allowed users to manually modify the site colours, which could result in the site breaking if the colours were not specified properly. The input has been disabled in this PR, such that users can only use the colour picker to enforce correct colours being chosen.
=> Fix: disable manual user input for colours

package.json
This PR updates the `npm run test-e2e` and `npm run cypress:open` commands to always use the updated env vars.
=> Chore: update cypress test command

src/styles/isomer-template.scss
This PR fixes the font on EditPage. 
Currently, there's a style override that causes the EditPage font to render as `monospace`, and on highlight, render as `Inter`. We remove the style override so that `Inter` is the default font.
=> Hotfix to develop: update fonts for span

.github/pull_request_template.md
Right now we don't have a structured way of writing PRs. This means that important information might be lost (eg: changing build scripts/env vars/breaking deps upgrade) as the author forgot while writing their PRs. Adding a github template would solve this issue and extra sections can be deleted if unused.
1. copy formsg's pr template 
1. feel free to suggest edits as necessary! i'll make the changes and raise a corresponding PR on BE when this is merged in with the final version of the PR template
=> chore(.github/templates): adds github PR template

.github/mergify.yml
We should automate some stuff on isomer, which would otherwise either slip by or require man hours. 
Add mergify to the repo to automate the boring stuff away. The mergify config is relatively conservative (taken from `ts-template`) with a few added configurations. The added configs are: 
1. close PRs without any recent (>1 month) activity 
2. delete branches after their PR is merged (we can still restore branch so this is not information destroying) 
3. mark a PR as draft if [wip] (case insensitive) is in the title.
1. the mergify config only runs `lint` and does **not** test to see if the changes pass (for dependabot/snyk). this is due to the extremely long run time for ci tests - we should test them once we have lightweight unit tests up.
=> chore: add mergify

src/components/media/MediaModal.jsx
Nested ternaries make expressions difficult to read. `MediaModal` has a couple of nested ternaries, which make it difficult to understand the component
1. Define a `Modal` component within `MediaModal` to simplify the flow.
=> refactor(mediamodal): removed nested ternary

.github/mergify.yml
previous rule asserted that `Bump` was the start of the PR title due to `^`. Our dependabot titles start with `Chore(deps | dev-deps)`
remove `^`
=> fix(mergify): update PR rule for dependabot

src/components/media/MediaModal.jsx
The `MediaModal` infinitely renders when creating the modal as a component (introduced in #758).
Change it to a function invocation. However, still unsure why it works as i always thought components and functions are equal (in React).
=> fix(mediamodal): fixed infinite rendering bug

.storybook/preview.js, src/components/FormFieldMedia/FormFieldMedia.scss, src/components/FormFieldMedia/FormFieldMedia.stories.tsx, src/components/FormFieldMedia/v2/FormFieldMedia.stories.tsx, src/components/FormFieldMedia/v2/FormFieldMedia.tsx, src/components/FormFieldMedia/v2/FormMediaInput.tsx, src/components/FormFieldMedia/v2/FormMediaInput.v2.tsx, src/components/FormFieldMedia/v2/index.ts, src/types/forms.ts
`FormFieldMedia` does not have an associated story. It is also written in javascript, which lacks static typing.
Closes #746
This PR has more stories than normal. This is because isomer has not decided on a direction for the migration strategy and the stories laid out here are meant to provide context and information on what migration strategy might best suit us.
1. `v1/Form Field Media` is the component as-is.
2. `v1/Form Field Media With Theming` is the component as-is but with an arbitrary `ThemeProvider`. This is the config that would be adopted if we were to adopt the design system gradually (ie, minor UI changes but no functionality changes) 
3. `v2/Form Field Media` is the component with mixed usage of our (themed) components and unthemed portions swapping to design system (here, …
=> feat: add story for formFieldMedia

cypress/integration/workspace.spec.js, src/__tests__/utils.jsx, src/utils.js
Newly created unlinked pages are created with `layout:post` in the frontmatter. This causes an issue where unlinked pages take on the secondary colour of a repo, instead of the primary colour as expected. These pages also display a date , which is undesired behaviour.
This issue was caused by an incorrect retrieval of default front matter - we relied on collectionName to determine whether the page was a resource page or not, rather than the absence of resourceRoomName.
Resolves #775 
- No - this PR is backwards compatible
Attempting to add a new unlinked page will create one without `layout:post` in the front matter
Unlinked pages created since the pages refactor prior to this fix will still have the incorrect colours
=> Fix: do not return layout for unlinked pages

src/components/Banner/Banner.tsx, src/components/Banner/index.tsx, src/layouts/Sites.jsx, src/styles/isomer-cms/elements/base.scss, src/styles/isomer-cms/elements/header.scss
This PR adds a new custom banner component, as well as modifies the Sites layout to use the banner for an announcement about identity phase 1. 
Closes https://github.com/isomerpages/isomercms-frontend/issues/772
The PR adds a custom banner component - because, unfortunately, the existing CMS styles interfere with those from the design system.
There are 2 external icon links, and the left icon in the banner is mis-aligned.
As such, we had to create a very simple custom banner that did not have icons (i.e. no left icon and no close button functionality) just to tide us over for now, while we refactor the styles/components in the CMS. We chose to take this hacky approach because it was crucial to get the announcement banner for identity phase 1 out by this week.
No - this PR is backwards …
=> feat: add banner component and identity phase 1 banner

README.md, package.json
This PR automates the release flow to automatically run `npm version` and push tags to github.
Closes #788 
- `release --update=<versionType>` : runs `npm version <versionType> && git push --tags` to automate the release process.
Will replicate this on the backend repo after this PR has been approved.
=> Chore: automate release versioning

.github/mergify.yml, .github/workflows/chromatic.yml
Chromatic workflow is being triggered by bots, which is not needed.
add if condition in the chromatic job so that the workflow is only triggered if the username doesn't end with bot. This PR also adds in a fix for mergify (see #770) that got overridden
=> fix(ci): prevent chromatic from being triggered by bots

src/components/Banner/Banner.tsx
This PR positions the banner link immediately next to the banner text; the link currently is flushed to the right of the banner.
**BEFORE**:
**AFTER**:
=> chore: position banner link immediately next to text

src/components/Form/FormTitle.jsx, src/components/settings/ColorPickerSection.jsx, src/components/settings/FormFieldColor.jsx
`FormFieldColour` has quite a few components inside. It should only be restricted to the the colour picker and the hex display.
Closes #771
1. Shift away wrapper component/`FormTitle` into the wrapping component (`ColorPickerSection`)
2. Use base `FormInput` to simplify internal component logic
=> ref(formFieldColour): refactored to use base form components

src/components/FormFieldHorizontal.jsx, src/components/PageSettingsModal/PageSettingsModal.jsx, src/components/Spacing/Spacing.jsx, src/components/Spacing/Spacing.module.scss, src/components/Spacing/index.js, src/layouts/Settings.jsx, src/styles/isomer-cms/elements/form.scss
This PR builds on #774 and is part of #771 
The `FormFieldHorizontal` component is extremely similar to `FormField` but has alot of repeated code within it. This PR uses the new `FormInput` component introduced in #774 to refactor this component and make it simpler.
The `FormFieldHorizontal` component additionally had 2 line breaks on error, which it used for formatting. This made it difficult to compose as it now had layout logic in addition to just being a UI input.
1. utilized `FormInput` component as a base and pass customized props to it.
2. created a new `Spacing` component (inspired by Chakra's [Stack](https://chakra-ui.com/docs/layout/stack)) that handles layout and removes this concern from `FormInput`. I've checked with Nat on this and the spacing is a constant 24px between …
=> ref(form field horizontal): replace with simpler API

src/components/Link/Link.module.scss, src/components/Link/Link.tsx, src/components/Link/index.ts, src/components/VerifyUserDetailsModal.jsx, src/styles/isomer-cms/elements/form.scss
Some styling in #559 does not adhere to isomer styling and hence looked awkward. This PR made minor stylistic fixes to those portions 
1. add padding on input to avoid congestion
2. use isomer button styling
**BEFORE**:
**AFTER**:
=> refactor(identity): button and input styling

scripts/build.js
Cypress tests fail with unhelpful error messages if the required environment variables are not defined.
Throw an exception if any variable is undefined (showing the value that was read for each).
npm run test-e2e #should give error messages if `PERSONAL_ACCESS_TOKEN` or `USERNAME` are undefined.
=> test: added e2e test error message if environment variables are not defined.

src/utils/directoryUtils.ts
This PR fixes an issue when renaming subcollections - getDirectoryType was returning the incorrect type, which was causing the subcollection title to be incorrectly slugified. This PR fixes this issue and adds additional comments to explain the functionality.
=> Fix: return correct directory type and update comments

cypress/integration/editPage.spec.js, cypress/integration/folders.spec.js, cypress/integration/move.spec.js, cypress/integration/settings.spec.js, cypress/integration/workspace.spec.js, package.json, scripts/reset-e2e.js
Previously, in #819, there was work done to rewrite components in semantic html and this resulted in the html types of elements being changed from `div` to `button` as well as a minor rewrite of some components (most notably, `BreadCrumb` to make them more declarative). 
As a result of this, our e2e tests broke because they were written using selectors for those specific html tags/certain specific text.
This PR fixes the failing e2e tests
1. rewrite e2e-tests to use selectors for the new html tags
2. for tests checking the `breadcrumb` component, the cypress tests were updated to check for the _siblings_ rather than the raw text content (as previously it was a string like `Workspace > Something > Some other thing`.) 
3. For certain tests, we require an assertion to guard against …
=> fix(test): update e2e tests

craco.config.js, jest.config.ts, package-lock.json, package.json, public/index.html, src/__tests__/RouteSelector.spec.jsx, src/components/Form/FormInput.jsx, src/components/FormFieldMedia/FormMediaInput.jsx, src/components/FormFieldMedia/v2/FormFieldMedia.tsx, src/components/FormFieldMedia/v2/FormMediaInput.tsx, src/components/InputWithButton.jsx, src/components/MediaCreationModal/MediaCreationModal.jsx, src/components/VerifyUserDetailsModal.jsx, src/components/homepage/HeroSection.jsx, src/components/homepage/InfopicSection.jsx, src/components/media/MediaAltText.jsx, src/components/media/MediaSearchBar.jsx, src/components/navbar/NavSection.jsx, src/components/settings/FormFieldColor.jsx, src/layouts/EditHomepage.jsx, src/styles/isomer-cms/elements/form.scss, src/styles/isomer-cms/pages/Editor.module.scss, src/tests/TestDecoder.mock.ts
Previously, we had no padding on input owing to emotion resetting padding to 0. This caused inputs to look squashed. In addition, the border colour of inputs were wrong (black) rather than grey due to `reset-css`. This also fixes some UI issues with preview (h1-6 on homepage/contact).
1. change base components to use chakra/design system components
2. shift h1-6 styling into own css class and other previews extend the class
3. remove reset-css (there's a similar chunk in `isomer-templates.scss` but it's `minireset`)
=> ref(design-system): replace input and some buttons

cypress/integration/resourceCategory.spec.js, src/components/DirectorySettingsModal/DirectorySettingsSchema.jsx, src/theme/index.ts
This PR fixes a flaky e2e test in cypress by changing from a fixed wait time to using an assertion to ensure that the element is no longer in the Dom.
This PR also fixes the check for resource category so that special symbols are no longer allowed.
Also fixes our ui theming from design system
1. Changed validation for resources to use the same one as originally
2. Changed wait time to assertion
3. Extend them from ogp design system (I mistakenly thought calling`extendTheme` was sufficient but we need to also add the base design system theme
=> fix(e2e): release 0.7.0

src/layouts/EditPage.jsx
#838 changed `marked` to use a new major version and updated teh API but missed out on the import. this resulted in a bug where we are unable to use the edit page as it will crash.
fixes the import (see [here](https://marked.js.org/) under the nodeJS section)
=> fix(marked): fixed import

src/layouts/EditPage.jsx
This PR fixes an issue where users were unable to save sanitised files and file which were overwritten by a later commit. The reason for this was due to the format of the data provided, which has been fixed in this PR.
=> Fix: save sanitised file data

src/components/Sidebar/Sidebar.tsx, src/layouts/layouts/SiteViewLayout/SiteViewHeader.tsx
previously, links for header and sidebar were opened in the current tab. this pr changes that so that they are now opened in a new tab.
1. add `target/rel` props
=> fix(nav): open external links for header/sidebar in new tab

src/styles/isomer-template.scss, src/styles/preview-panel.scss
previously, context menu items **that were pdfs** had a pdf file icon appearing on the left side of the item. this was due to global styles in `isomer-templates.scss` not being localized into `preview-panel`. 
Delete the style from `isomer-template` and shift it into `preview-panel`
=> fix(preview/dropdown): fixed global styles interfering with context menu items

src/layouts/Settings/ColourSettings.tsx, src/layouts/Settings/FooterSettings.tsx, src/layouts/Settings/GeneralSettings.tsx, src/layouts/Settings/components/FormToggle.tsx, src/layouts/Settings/components/SettingsFormFieldMedia.tsx
See [here](https://docs.google.com/document/d/1EreGS8X1uIOgMrl7yXDF4jCprsIQ25BTVmyGLpT5P9k/edit#), under settings, for an overview of the concurrent editing issues faced.
1. use `controller` which react hook forms provides. rather than managing state from within rhf ourselves, the `controller` simplifies these usage patterns and handles the state of the field for us. Hence, using this component allows us to focus on writing simple components that take in values while deferring the lifecycle etc to rhf
=> fix(v1.5): concurrent editing displays updates/errors properly

src/layouts/Settings/Settings.tsx
previously, the warning modal was removed for ease of manual testing (sadge) - this PR readds the modal back into settings page. 
related to #941 - tbc if need to rebase and use the generic warning modal
1. extract `hasDiff` out from `useEffect`
2. conditionally display modal when `hasDiff`
=> fix(settings): add warning modal back into settings

src/components/WarningModal/WarningModal.tsx, src/layouts/Settings/Settings.tsx
Previously in the v1.5 PR, the `Settings` page uses a newly created `Modal` component rather than using the `WarningModal` component that is used to display warning messages. 
This PR changes the `Modal` to use the `WarningModal` component and also, changes the `spacing` in `WarningModal` to 4. This is because the spacing given in figma seems to be 16px, which is `spacing = {4}`.
=> refactor(settings): change conflict modal to use WarningModal component 

src/layouts/Folders/components/FolderBreadcrumb.tsx, src/layouts/ResourceCategory/components/ResourceCategoryBreadcrumb.tsx, src/layouts/ResourceRoom/components/ResourceBreadcrumb.tsx, src/layouts/Settings/ColourSettings.tsx, src/theme/components/Breadcrumb.ts, src/theme/components/index.ts
Some UI styling differed from what the designers had in mind for v1.5; refer [here](https://docs.google.com/document/d/1EreGS8X1uIOgMrl7yXDF4jCprsIQ25BTVmyGLpT5P9k/edit#) for a comprehensive list of changes. 
This PR addresses the following: 
1. underline on hover for breadcrumbs
2. last breadcrumb colour
3. settings -> colour button's outline colour
1. for underline on breadcrumb hover, this is done through overriding the chakra UI styling for breadcrumbs as the `textDecoration` is set by chakra [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/breadcrumb.ts). concretely, this means that all future breadcrumbs will **not** have underline on hover. waiting for designers' response on this but if this is the desired behaviour then it should be ok. 
2. …
=> chore(v1.5): minor UI updates 

src/components/DirectoryCreationModal/DirectoryCreationModal.jsx
This PR fixes a display issue with the footer on the creation modal which was introduced with the Footer refactor. As we are working on a refactor for full screen modals, we've opted for a quick temporary fix - `position: fixed` has been added back to the footer in this modal to replicate the previous footer behaviour.
=> Fix: create modal footer

src/styles/isomer-template.scss, src/templates/utils/leftnavGeneration.jsx, src/utils/siteColorUtils.js
This PR fixes a minor styling issue with third nav previews. With the release of #895, we mistakenly removed some styling of third navs in the editpage preview, as these styles were attached to the globally imported sgds stylesheet - bullet points were showing up in the list where they should not and the chevrons indicating third nav items were missing. This PR adds those styles back into our codebase.
Note that since we do not import sgds styles globally anymore, I have opted to swap the chevron used in the nav preview to bx-chevron rather than sgds-chevron, since the icons are similar enough, rather than having to refactor all editpage components to use scoped styles.
Current (incorrect) display on CMS:
Preview on CMS:
Preview prior to removal:
Actual site:
=> Fix: editpage third nav styling

package-lock.json, package.json, src/hooks/settingsHooks/useGetSettings.ts
This PR provides a temporary fix for ignoring `url` in config files, which is a common field - we should eventually add this as an available parameter which can be modified in settings.
It also downgrades @storybook/addon-essentials to 6.4.18, to prevent type errors being caused by storybook packages being of different versions. We will update the storybook packages in a future PR.
=> Fix: ignore url in config

src/layouts/screens/DeleteWarningScreen.jsx, src/utils.js
This PR fixes an issue where users were unable to delete resource categories. As the logic for this component is complicated and difficult to debug, we will file an issue to tackle a more permanent fix/refactor in future.
Issue: https://github.com/isomerpages/isomercms-frontend/issues/977
=> Fix: delete resource category

.storybook/preview.js, src/components/Header.jsx, src/components/Sidebar/Sidebar.stories.tsx, src/components/Sidebar/Sidebar.tsx, src/contexts/LoginContext.tsx, src/mocks/constants.ts, src/mocks/handlers.ts, src/mocks/utils.ts, src/types/user.ts
Previously, we were relying on a hard-coded `LoginContext` for our stories as `msw` was not implemented in our codebase and we had no way of providing mock data.
This led to components dependent on `LoginContext` to be unable to update their states accurately to reflect the logged in status. 
Moreover, the `LoginContext` was not being used and components were reading from `localStorage`, which is not reactive and doesn't cause a re-render on change. this led to issues on initial login for `Header`.
Also, this PR adds a new GSIB viewport for visual testing (1920 * 1080).
1. Remove `LoginContext` from storybook preview and use `LoginProvider` 
2. Add mocks for the routes used by `LoginProvider`
3. For components relying on `userId`, read directly from the context rather than `localStorage`
=> ref(storybook): login context for stories

src/components/folders/FolderItem.jsx, src/components/folders/ReorderingModal.jsx, src/hooks/directoryHooks/useGetFolders.ts, src/layouts/Folders/Folders.stories.tsx, src/layouts/Folders/Folders.tsx, src/layouts/Folders/Subfolder.stories.tsx, src/layouts/Folders/components/FolderCard.tsx, src/layouts/Folders/components/PageCard.tsx, src/layouts/Folders/components/index.ts, src/layouts/ResourceCategory/components/ResourceCard.tsx, src/layouts/Workspace/Workspace.tsx, src/layouts/Workspace/components/Cards/PageCard.tsx, src/mocks/constants.ts, src/mocks/utils.ts, src/services/DirectoryService/DirectoryService.ts, src/styles/isomer-cms/elements/base.scss, src/types/directory.ts, src/types/utils.ts
first part of problem can be seen in #980, where writing page level stories helps to ensure design consistency + give our designers an easier life.
second part of problem is that folders previously did not lend itself well to page level stories. this resulted in the card missing a few UI elements in storybook, which meant that a refactor was needed. moreover, the card component here did not fit the designer's vision in v1.5 (the component itself looked visually different). 
1. write stories for `Folders`
2. update api of `useGetFolders` and related types (as it can return both folders/pages)
3. write new `PageCard` and `FolderCard` component for use in `Folders`
=> ref(storybook): refactor folders and add stories

src/layouts/Workspace/Workspace.stories.tsx, src/layouts/Workspace/Workspace.tsx, src/layouts/Workspace/components/Cards/ContactCard.tsx, src/layouts/Workspace/components/Cards/HomepageCard.tsx, src/layouts/Workspace/components/Cards/NavigationCard.tsx
See #980 for an overview of the problem
1. This PR adds stories for `Workspace` - lmk if i missed out any potentially interesting stories
2. This PR also has minor fixes for loading states: previously, we used a skeleton to wrap the component. this is problematic as the skeleton takes the height of the component, which is 0 when there's nothing loading. This prevents the skeleton from being seen and feedback from being given to the user. This was fixed through a conditional height - display a fixed height when it's loading, let the height fit content after.
=> ref(storybook): adds workspace stories

.gitignore, src/hooks/settingsHooks/useUrlHook.jsx
The "View Staging" button in the header does not work as expected for sites without the staging URLs in the description. This was due to the button calling the `/v1/sites/:siteName/stagingUrl` endpoint, which extracts the staging URL from the repository description.
**Bug Fixes**:
- The "View Staging" button has been updated to call the `/v2/sites/:siteName/stagingUrl` endpoint instead, which extracts the staging URL from the `_config.yml` file.
**Unit tests**:
- Run `npm run tests`
**Smoke tests**:
- Run `npm run dev`
- Log in and access any site without a staging URL in the description, such as `moe-princesselizabeth`, `moe-dunearnsec` and `moe-temasekpri`.
- Verify that the "View Staging" button now works.
*None*
=> fix: update stagingUrl endpoint from v1 to v2

src/utils/allowedHTML.ts, src/utils/validators.js
Since HTML code regarding iframe is part of the 400 character limit (see image below), this does not allow certain agencies to add in iframe. Currently, the workaround is to manually adding the code directly to the back end.
Closes #994
Using a regex pattern to get instances of `<iframe></iframe>` and `<div></div>` (what our current users are using), and then not including this subset of the sting as part of the total character count allowed.
Note: This is meant to be a temporary workaround, once we move to block editing, this should not be an issue
=> Fix/hitting character limit when adding <iframe/>

cypress/e2e/folders.spec.ts
Altered dom structure in the prior PR #1016 meant that the existing tests that relied on clicking the context menu might fail here. 
1. change selector so that context menu clicking works
=> fix(folders.spec): change selector to account for altered dom structure

cypress/e2e/folders.spec.ts, src/layouts/Folders/components/FolderCard.tsx, src/layouts/Folders/components/PageCard.tsx
**note: updates to e2e tests will come in a subsequent PR**
See #998 for the issue - this problem also exists in folders; however, this problem only showed up now because of 2 reasons
1. `Folders` didn't have its card component updated to fit figma at point of merge for the context menu PR. 
2. This problem exists only when using an updated chakra version after merging the cypress update PR
Refer to #998 for more deets but the only concrete change is to add a full width `Box` as the parent of `Card` and `ContextMenu`
=> fix(folders): fixed floating context menu for cards in folders

src/hooks/settingsHooks/constants.ts, src/hooks/settingsHooks/useGetSettings.ts, src/layouts/Settings/GeneralSettings.tsx, src/types/settings.ts, src/utils/validators.js
Closes https://github.com/isomerpages/isomercms-backend/issues/454.
**Bug Fixes**:
- The `url` configuration parameter in `_config.yml` can now be configured on the frontend with a validation of the domain name if given.
**BEFORE**:
**AFTER**:
Frontend PR for https://github.com/isomerpages/isomercms-backend/pull/490.
*None*
=> fix: add support for site url config parameter

src/hooks/directoryHooks/useDeleteDirectoryHook.jsx, src/hooks/pageHooks/useDeletePageHook.jsx
in #973, some deletion hooks did not have their keys updated and this resulted in pages and folders in `resources` not automatically updating even when the pages/folders within were deleted.  
1. update query keys
2. pass `params` and omit extra keys
**note**: this is a bandaid solution and a more permanent fix would be to refactor these deletion hooks akin to what has been done in #973 instead
=> fix(hooks): update query keys for page and directory deletion hooks

cypress/e2e/editPage.spec.ts, cypress/e2e/settings.spec.ts, cypress/fixtures/constants.ts, cypress/support/index.d.ts, cypress/support/settings.ts, src/hooks/moveHooks/useMoveHook.jsx, src/hooks/pageHooks/useCreatePageHook.jsx
see #1033 for an overview of the bugs uncovered during release ;--; 
Partially resolves #1033
1. add query key invalidation for `move`/`createPage` hooks
2. update cypress test command to fill in the SEO by default
3. add success/failure e2e test for SEO Field
=> fix(e2e-tests): update e2e tests 

src/components/folders/FolderItem.jsx, src/components/folders/ReorderingModal.jsx, src/hooks/directoryHooks/useDeleteDirectoryHook.jsx, src/hooks/pageHooks/useDeletePageHook.jsx, src/hooks/pageHooks/useUpdatePageHook.jsx
Previously, drag and drop did not work on `develop`. this is because having the`chakra.button` interfered with the draggable as they both respond to `onClick` events. 
Related to #1033 
1. remove extra stuff from `FolderItem` as it's only used in re-ordering modal now.
=> fix(reorderingmodal): removed chakra.button from folderItem

src/hooks/directoryHooks/useUpdateDirectoryHook.jsx
This PR fixes an issue where renaming a resource category would not immediately update the name of the displayed folder until refresh, due to the invalidation of the wrong query key.
=> Fix: useUpdateDirectoryHook invalidate query

cypress/e2e/settings.spec.ts, src/hooks/settingsHooks/useUpdateSettings.ts, src/utils/validators.js
The site URL field in the site settings page does not allow for trailing slashes.
**Bug Fixes**:
- The domain name regex has been updated to allow for a single trailing slash in the site URL input field.
- Any trailing slash will be removed before sending the domain name to the backend.
**Unit tests**:
- Run `npm run tests`
**Smoke tests**:
- Run `npm run dev`.
- Use any site and navigate to the site settings page.
- Add a valid domain to the SEO field (site URL) and add a single trailing slash.
- Click anywhere outside the field, no error message will be shown.
- Click on "Save", the updated settings can be saved and the trailing slash will disappear.
*None*
=> fix: allow trailing slash for site URL but remove on save

cypress/e2e/settings.spec.ts, src/layouts/Settings/GeneralSettings.tsx
The copy used for the SEO settings field can be confusing for users.
- The copy used for the SEO settings field has been improved as provided by design.
- The error message when the field is empty has also been improved.
**Smoke tests**:
- Run `npm run dev`.
- Use any site and navigate to the site settings page.
- The updated description will be shown.
- Add any text to the SEO field (site URL) and then remove it.
- Click anywhere outside the field, the updated error message will be shown.
*None*
=> fix: improve copy of SEO settings field per design

src/layouts/Media/components/ImagePreviewCard.tsx
Previously, images in private repos were being returned as the raw base64 data. This causes the file extension parsing to erroneously display a huge chunk of text rather than the proper extension.
1. check if the url begins with the specified format indicator (`data:image/`)
2. if so, extract the characters till a terminating semi colon
3. otherwise, get file extension the normal way.
=> fix(imagepreviewcard): update generation of file extension

cypress/e2e/files.spec.ts, cypress/e2e/images.spec.ts, cypress/support/medias.ts, src/layouts/Media/Media.tsx, src/layouts/Media/components/FilePreviewCard.tsx, src/layouts/Media/components/ImagePreviewCard.tsx
There are some minor issues with the images and files pages:
1. SVG files will have an additional "?sanitize=true" string that appears together with the file extension, which can be confusing to users.
2. The "Ungrouped Images" heading appears for both images and files pages.
**Bug Fixes**:
- The way to obtain the file extension has been adjusted to strip away any additional characters after a single "?" character, which is only present for svg files.
**BEFORE**:
**AFTER**:
**Smoke tests**:
- Run `npm run dev`.
- Log in and navigate to any site's images page that has an SVG file
- Verify that the "?sanitize=true" portion does not appear
- Navigate to the Files page
- Verify that the text are adjusted to suit the Files page instead of the Images page
**e2e tests**:
- …
=> fix(media): remove ?sanitize=true for svg and adjust heading

cypress/e2e/workspace.spec.ts, src/layouts/layouts/SiteViewLayout/SiteViewLayout.tsx
workspace was flaking due to lack of assertions before using the selectors, leading to hidden elements (as beneath the `Skeleton`). the alias for the context menu item was also erroneous, leading to the command to fail.
this causes tests to flake.
add an assertion for the folder caption as proof that the folder section has finished loading prior to test execution.
fix alias for `contextMenuItem`
=> fix(e2e): workspace.spec

cypress/e2e/resourceCategory.spec.ts, src/assets/images/EmptyBoxImage.tsx, src/components/EmptyArea.tsx, src/components/LoadingButton/LoadingButton.tsx, src/hooks/settingsHooks/useGetSettings.ts, src/layouts/ResourceCategory/ResourceCategory.tsx, src/layouts/ResourceRoom/ResourceRoom.stories.tsx, src/layouts/ResourceRoom/ResourceRoom.tsx, src/theme/components/Tabs.ts
Currently, our empty state for ResourceRoom is not very pleasant to look at and not intuitive. Isomer should have a more descriptive empty state to guide the user along
Addresses #962
As suggested in [figma here](https://www.figma.com/file/7OtNYkc4s9BkFk05ConEbd/V1.5?node-id=1559%3A62055)
**BEFORE**:
**AFTER**:
Other Notes: 
Other changes are linked to outstanding PRs by @seaerchin
=> feat(resource-room): empty state for empty resource room

.github/pull_request_template.md, .github/workflows/ci-e2e.yml, .github/workflows/trigger-e2e.yml
Our e2e tests are painful to run and we choose not to run it on our local machines. This can result in potential bugs that could have been caught in our e2e tests to be missed, and to only surface during release day. This is dangerous and can result in significant loss in developer productivity to identify the root cause of e2e test failures.
Fixes #1037.
**Features**:
- A new workflow is introduced to allow e2e tests to be triggered via a special comment. This workflow will ensure that:
- The user is authorised to perform the command (being part of [isomerpages/core team](https://github.com/orgs/isomerpages/teams/core))
- There are no existing e2e tests being run before triggering one
- The existing e2e test workflow can now be triggered directly through a …
=> feat: allow e2e tests to be triggered from a PR comment

src/components/MediaSettingsModal/MediaSettingsSchema.jsx
Currently, when uploading files with dots, IsomerCMS fails with an ambigous message stating "A new media file could not be created. Please try again or check your internet connection" This is a bandage on the front end rather than a permanent fix
Closes #1021. 
Throw an error when the user attempts to upload a file with dots within the file name, excluding the extension. 
- [] Yes - this PR contains breaking changes
=> fix(file not uploaded when having 2 dots): Improve user experience by throwing an error

.github/workflows/ci-e2e.yml, .github/workflows/trigger-e2e.yml
The e2e tests GitHub Actions workflow does not handle `workflow_dispatch` events well, causing the PR comments to be given to incorrect pull requests. Also, the step to check for user's team membership does not work well for bot accounts.
**Bug Fixes**:
- The original e2e test workflow has been updated to allow specifying the pull request number. This number will be used to determine the name of the original branch, the SHA of the HEAD commit for that branch and the title of the pull request. This fix was performed on [advice from the Cypress documentation](https://docs.cypress.io/guides/continuous-integration/github-actions#Pull-requests-commit-message-is-merge-SHA-into-SHA).
- The step to check the user's team membership has been updated to continue on errors, so …
=> fix(gh-actions): handle failures from bots and refine PR comments

.github/workflows/ci-e2e.yml
Add missing `GITHUB_TOKEN` environment variable for the updated ci-e2e workflow. This is required to authenticate the request to the GitHub API ([see the failed run for more details](https://github.com/isomerpages/isomercms-frontend/actions/runs/3134900623/jobs/5090121951)).
=> fix: add GITHUB_TOKEN environment variable for ci-e2e

src/layouts/Dashboard/components/ReviewRequestModal/RequestOverview/RequestOverview.stories.tsx, src/layouts/Dashboard/components/ReviewRequestModal/RequestOverview/RequestOverview.tsx, src/mocks/constants.ts
This PR adds sorting and filtering to the modal. This is done through adding `react-table` to the frontend. `react-table` presents a headless view of the data, which allows us to plug it into the respective UI library.  
- this uses the inbuilt functionality of `react-table` of `filter` + `sort` to achieve this. 
- the docs are abit unclear on how to accomplish this so i'll try to note this down below.
`react-table` uses its `columnHelper` to define its data model. through using the `columnHelper`, we are able to define the following forms of columns: 
1. accessor - these read data from our data model 
2. display - these do **not** read any data but instead, display arbitrary content 
3. grouping - no data model, only used to group other columns together.
accessor columns access our data …
=> feat(rr): sorting the modal

src/components/ButtonLink/ButtonLink.tsx, src/components/ButtonLink/index.ts, src/layouts/ReviewRequest/components/ReviewRequestForm/ReviewRequestForm.tsx, src/layouts/ReviewRequest/components/SendRequestModal/SendRequestModal.stories.tsx, src/layouts/ReviewRequest/components/SendRequestModal/SendRequestModal.tsx, src/layouts/ReviewRequest/components/SendRequestModal/index.ts, src/layouts/layouts/SiteViewLayout/SiteViewHeader.tsx, src/mocks/constants.ts, src/theme/foundations/colours.ts, src/types/reviewRequest.ts
This PR adds the send request modal, which the requestor sees after submitting a review request. 
Part of #1070 
1. Add modal 
2. Add a utility function to generate the `mailTo` content. This was done with reference from [here](https://css-tricks.com/snippets/html/mailto-links/) as well as [here](https://www.rfc-editor.org/rfc/rfc2368#page-3) (for line breaks.)
=> feat(review-request): send review request modal 

src/layouts/SiteDashboard/SiteDashboard.stories.tsx, src/layouts/SiteDashboard/SiteDashboard.tsx, src/layouts/SiteDashboard/components/ReviewRequestCard.tsx, src/layouts/Sites.jsx, src/mocks/constants.ts, src/mocks/utils.ts, src/utils/date.ts
The site dashboard displays the Unix timestamp directly instead of a human-readable date format, which is hard to interpret for users. Also, the site dashboard is designed for email login users, but both GitHub login users and email login users are able to access it.
Fixes #1115.
- The dates on the site dashboard is now displayed in a human-readable format.
- The site dashboard has been restricted to only email login users, GitHub login users will be redirected to the workspace.
- Time format has been changed to use 12-hour time instead of 24-hour time.
1. Run with `npm run dev`.
2. Navigate to the site dashboard of any site (as an email login user)
3. Verify that the dates shown are in the human-readable format
4. Log out and log in through GitHub …
=> fix: touch up site dashboard

src/routing/RouteSelector.jsx
when the site has an approved review request, the user should be redirected to `/dashboard` on login. this was only done for `Workspace` and legacy components (in `.js`) and wasn't done for the new pages.
add redirect
=> chore(routeselector): add approval redirect on all sub components

src/layouts/layouts/SiteViewLayout/SiteViewHeader.tsx
Part of #1113 - this PR makes the `SiteViewHeader` conditionally go back to either the dashboard or sites, depending on whether they are at the dashboard itself.
As `SiteViewHeader` is **only** used at review request related stuff, this header should only be seen by **email** users.
Closes #1113 
add conditional for href on back button
=> fix(siteviewheader): conditional url for back button

src/layouts/layouts/SiteEditLayout/SiteEditHeader.tsx
See #1136 for a brief overview but for `SiteViewHeader`. In here, we distinguish between github/identity users and we conditionally alter the text/url based on that. 
This is done through checking the `userId` variable, which is set when the user logs in through github. 
1. retrieve `userId` and check
=> fix(header): conditional url for site edit header

src/layouts/ReviewRequest/Dashboard.tsx
The figma has a footer appearing on the review request dashboard after the review request is approved. This footer was initially missing from the rr and this PR adds it back. 
1. use our `Footer` component + hook to merge the PR
=> fix(rr): add footer to dashboard after rr is approved

src/hooks/reviewHooks/useUpdateReviewRequest.ts, src/layouts/ReviewRequest/Dashboard.tsx, src/layouts/ReviewRequest/components/ManageReviewerModal/ManageReviewerModal.tsx, src/services/ReviewService.ts, src/types/error.ts, src/types/reviewRequest.ts
See #1108 for an overview of the problem
Closes #1108 
1. remove `stateManager` functionality and use `react-hook-forms` to manage state instead.
2. create new hooks + service api to ping the backend on update admin change.
- Requires the corresponding backend PR to be merged to work.
=> feat(rr): allow update of admins in rr 

src/components/CollaboratorModal/components/AcknowledgementSubmodal.tsx, src/layouts/ReviewRequest/components/PublishedModal/PublishedModal.tsx
Currently, the "Go to live site" link in the modal that appears when the user publishes a review request will open in the same tab. This behaviour can be rather annoying to the user as it navigates the user away from the CMS.
**Bug Fixes**:
- Changed the link for the "Go to live site" link in the published modal of review requests to open in a new tab.
- Also added `rel="noopener noreferrer"` for security purposes in this modal and in the collaborators modal.
1. Run `npm run dev` on this branch
2. Navigate to any approved review request and click on "Publish now"
3. Once the review request is published, the modal will appear. Click on "Go to live site"
4. Verify that the site opens in a new tab.
5. Navigate to the site dashboard of any site
6. Click on "Manage" for …
=> fix: open external links in a new tab

src/components/Header/AvatarMenu.tsx, src/components/Header/NotificationMenu.tsx
The `z-index` value is unset for the notifications and avatar menu dropdown, which would cause other items that have a `z-index` value defined greater than 0 to block parts of those dropdown menus.
**Bug Fixes**:
- The `z-index` value for the notification and avatar menu has been set to 10, which is a sufficiently high value to not be covered by any other components.
**BEFORE**:
**AFTER**:
1. Run `npm run dev` on this branch
2. Open any review request page
3. Verify that the review button no longer blocks the notifications menu and the avatar menu
*None*
=> fix: increase z-index for Menu.List in header items

src/components/Header/AllSitesHeader.tsx, src/layouts/layouts/SiteViewLayout/SiteViewHeader.tsx
The current "Get help" link is an external link, but the link is incorrect and does not open in a new tab.
**Bug Fixes**:
- The RouterLink component has been removed as it is an external link and not an internal application link
- The `isExternal` attribute has been applied to open the link in a new tab
1. Run `npm run dev` on this branch
2. Navigate to the all sites page, verify that the "Get help" link opens in a new tab
3. Navigate to the site dashboard of any site, verify that the "Get help" link opens in a new tab
*None*
=> fix: open the Isomer guide in a new tab

src/contexts/ReviewRequestRoleContext.tsx, src/layouts/ReviewRequest/Dashboard.tsx, src/layouts/ReviewRequest/components/ManageReviewerModal/ManageReviewerModal.stories.tsx, src/layouts/ReviewRequest/components/ManageReviewerModal/ManageReviewerModal.tsx, src/mocks/constants.ts, src/mocks/utils.ts
currently, users who are not the requestor are able to perform crud operations on the reviewers. This is too permissive and leads to issues wrt stale state.
This PR **disables** this functionality if the user is not the requestor
1. get `role` and disable the button(s) accordingly
=> fix(rr): disable adding admins if user isn't the requestor

src/components/Header.jsx, src/components/Header/NotificationMenu.tsx, src/layouts/layouts/SiteEditLayout/SiteEditHeader.tsx, src/layouts/layouts/SiteViewLayout/SiteViewHeader.tsx
The notification button uses `siteName`, which it obtains as props. this is passed down at present but because we use the notification button in our **legacy** `header` component, the `params` prop is **entirely optional** and there's no guarantee that it exists.
This causes a bug in pages which uses the legacy header, as `siteName` is `undefined`, leading to an erroneous query on the backend. 
1. remove `siteName` as a prop of the notification button and use the `useParam` hook to retrieve `siteName`.
- an alternate solution would be to use the `SiteEditHeader` rather than the legacy `Header` but it's not been tested with legacy pages yet and might have stylistic changes so the above solution was adopted
=> fix(notificationmenu): update button to get sitename using hook

src/layouts/ReviewRequest/Dashboard.tsx, src/layouts/ReviewRequest/components/Comments/SendCommentForm.tsx
This PR removes hardcoded values in comments and there's a corresponding backend commit which swaps router order.
This allows comments to work
swap hardcoded values for dynamic values
=> fix(comments): remove hardcoded value

src/routing/RouteSelector.jsx
previously, the banner did not have the ability to use markdown. this is a problem when we want to have external link
1. specify `useMarkdown` option
=> chore(routeselector): add ability to use markdown

.github/workflows/chromatic.yml
previously, our frontend workflow for chromatic triggered alot, even when there are unrelated file changes. this led to multiple rebuilds, which led to us busting our limit and designers being unable to review code.
1. use [github action](https://github.com/dorny/paths-filter) that detects if there are file changes
- we only care about changes that affect chromatic and hence, the list of folders are components + styles/theme.
=> chore(chromatic.yml): update to trigger when files are changed

src/components/CollaboratorModal/components/MainSubmodal.tsx, src/components/Header/ContactModal/ContactVerificationModal.tsx, src/hooks/collaboratorHooks/useListCollaboratorsHook.ts, src/layouts/ReviewRequest/Dashboard.tsx, src/layouts/ReviewRequest/components/ReviewRequestModal/ReviewRequestModal.tsx, src/mocks/constants.ts, src/types/collaborators.ts, src/utils/axios.ts
to be reviewed alongside BE PR [here](https://github.com/isomerpages/isomercms-backend/pull/568)
Previously, list collaborators uses a default error message which is uninformative to the user. this PR changes the error message to be extracted from the error body first, prior to falling back to a default. 
this also removes unused properties from our `CollaboratorsDto` type and shifts the parsing of `SiteMember.role` -> `role` to the backend
1. remove unused properties
2. use axios util and update it to allow default msg
=> chore(collaborators): error messages + parsing

cypress/e2e/editPage.spec.ts, cypress/e2e/resourceCategory.spec.ts, cypress/e2e/resources.spec.ts
Some specs were flaking due to a lack of assertions (which causes auto retry on the cypress side). This PR adds some assertions to the flakey tests as identified by a run of our e2e tests. 
This PR also adds a `blur` call to the form field to re-trigger FE validation.
1. add `should('be.visible')` to force cypress to retry till the dom stabilises
2. add a `blur` call to ensure form validation is retriggered.
=> test(specs assertion): add assertions into spec

src/hooks/pageHooks/useGetPageHook.jsx
we weren't calling the `useErrorToast` function previously, leading to a runtime error. (sidenote, this would've been caught by ts)
call the function
=> fix(usegetpagehook): calls `useErrorToast`

src/layouts/ReviewRequest/Dashboard.stories.tsx, src/layouts/ReviewRequest/Dashboard.tsx
See #1126 
Closes #1126
1. use `Skeleton` and check if data is loaded
=> chore(dashboard): add loading state

src/styles/isomer-cms/pages/Sites.module.scss
Content in sites dashboard gets hidden when window resizes:
https://user-images.githubusercontent.com/29480346/219262891-ebfe6312-61dc-4e15-afd1-d59e846cae7a.mov
This is because the page containers (`.sectionHeader` and `.sites`) have a fixed width.
1. Change invalid CSS `flex-direction: rows` to `flex-direction: row`; this is the CSS default so this doesn't change any behaviour
2. Instead of using `margin-left` and `margin-right` on individual `site` cards, use the [widely supported](https://caniuse.com/mdn-css_properties_column-gap_flex_context) `column-gap` to fix spacing between cards
3. Centre `.sitesContainer` using `auto` margins and give it a `max-width` so it doesn't grow too wide on bigger screens
4. Add some padding to `.sitesContainer` so it doesn't bump against the edge of …
=> style: remove fixed widths in sites dashboard

src/components/MediaCreationModal/MediaCreationModal.jsx, src/components/MediaSettingsModal/MediaSettingsModal.jsx, src/components/MediaSettingsModal/MediaSettingsSchema.jsx, src/layouts/screens/MediaSettingsScreen.jsx
This PR fixes an issue where newly created files were unable to be uploaded. This issue was due to the shared create/update media modal - we recently disallowed the changing of extension on renaming of existing images, by automatically appending  the extension to the filename of the existing file. However, for newly added items, they had no such extension, and this caused the uploaded file to have `.` appended to it. This PR fixes this behaviour for the creation flow.
This PR also restricts the renaming of newly uploaded images to prevent users from modifying their extension, and changes our duplicate filename check to be case insensitive.
=> Fix: remove . when no file extension

src/__tests__/utils.jsx, src/components/PageSettingsModal/PageSettingsSchema.jsx, src/components/PageSettingsModal/ResourcePageSettingsModal.tsx, src/utils/legacy.js
Currently, netlify links are lower casing. [To move towards Amplify infra](https://www.notion.so/opengov/Netlify-to-Amplify-Migration-01b9baff55ef4aebbe9f472fadf5a096?pvs=4), and ensure backward compatibility, all permalinks are going to be lower cased. 
Closes #1188 
Change permalink to lower casing. 
- Details ...
- [ X ] No - this PR is backwards compatible
Permalinks for pages are now only lower casing. Typing capital casing throws an error.
Previously, creating new pages within folders with CAPS has a default link in CAPS. This is no longer the case. 
Similar behaviour is observed when creating resource pages of type POST Content.
=> chore(permalinks): change permalink to lowercase

.env-example, .gitignore, .husky/pre-commit, README.md
While we do have checks post-commit to identify any secrets are committed, we should also attempt to prevent this even before a commit can occur.
After considering some solutions - https://github.com/awslabs/git-secrets and Git Guardian, we decided to go with GitGuardian since we are already using it.
We add Git Guardian as a pre-commit hook which scans commits for any leaked secrets before actually performing the commit.
There is a breaking change for local development since this commit makes Git Guardian setup somewhat mandatory.
- Details ...
No new dependencies are added to our package. Git Guardian will be installed on the OS-level instead as a brew package.
=> feat: adding gitguardian precommit hook

.github/mergify.yml
mergify `updated-at` should have opposite condition otherwise it keeps pinging
=> fix(mergify): update condition

src/layouts/Sites.tsx
`AnnouncementModal` using `!!email` to determine if users logged in via github or email; this is wrong and we should be using `!userId` 
- use `!userId`
=> fix(sites): change to using userId

src/theme/foundations/colours.ts
Duplicate base key is causing storybook build to fail
merge the base keys into a singular one
- Details ...
=> fix: duplicate base key

src/components/DirectorySettingsModal/DirectorySettingsSchema.jsx, src/components/PageSettingsModal/PageSettingsSchema.jsx, src/utils/validators.js
This PR fixes an issue with missing pages, which were showing up on the CMS but not on the actual site. On further investigation, we found that [jekyll has a list of restricted first characters for files/folders which will not be built](https://jekyllrb.com/docs/structure/) unless explicitly specified via the config file in the include directive. The special characters are (`.`, `~`, `#`, and `_`), all of which are already restricted for various reasons except for `#`. We have opted to restrict the use of `#` as the first character for subcollections and page titles, as this is the quickest way of resolving this issue - other methods we could require significant testing/engineering effort (either writing to the config file if we detect this special character, or decoupling file name and …
=> Is 59/fix/disallow files and subfolders starting with restricted characters

package-lock.json, package.json, src/App.jsx, src/constants/datadog.ts
**NOTE: HAVEN'T ADD ENV VARS TO 1PW YET!!! will add when PR approved**
Isomer had no monitoring last time, which made it difficult to understand user behaviour. In order to solve this, one possible way is to add datadog monitoring. This adds datadog RUM (realtime user monitoring) into the codebase, together with heatmaps 
Closes IS-4
1. install datadog sdk
2. initialise datadog sdk with new env vars
we require the below env vars to be updated in order for data tracking for dd
```
export REACT_APP_DATADOG_APP_ID=xxx
export REACT_APP_DATADOG_CLIENT_TOKEN=xxxx
export REACT_APP_VERSION=0.21.2
```
- `dependency` : `@datadog/browser-rum`
**notes**
- app blockers will block data reporting :(
=> feat(monitoring): adds RUM and heatmaps

cypress/e2e/editPage.spec.ts
Previously, `editPage.spec.ts` was failing due to our new CMS frontend. This was due to components changing, which made the selectors not function as intended. Also, vapt fixes caused us to omit file extensions, which led to tests failing.
Closes IS-63
1. change selectors 
2. add assertion to only proceed when loading is complete
3. omit extension for file names
**Notes**
there are some backend changes required in order for this PR to function properly. because our FE uses `!!userId` to determine if a user should be directed to the github login flow (which is what our tests work with), this requires a backend change to also return `userId` when it is the `E2E_USER`. separately, we should probably maintain 2 types of users for e2e (github + email) or, if we decide that we want to deprecate …
=> test(editpage.spec): fix for editpage.spec

cypress/e2e/images.spec.ts
Previously, our images tests were failing due to the new uploading functionalities on the cms - as we moved towards automatically determining the extension of images instead of having them be user determined, the titles our tests were looking for had to change to use the new image format instead.
This PR also adds additional album level tests and image moving tests to our original suite, which was fairly barebones.
=> fix: images tests and add additional image tests

cypress/e2e/sites.spec.ts
e2e were failing cos we were issuing requests to `v2` instead of `v1` now. 
Closes IS-71
- Change to use `setupDefaultInterceptors`, which listens on `v2` endpoints. 
- add an assertion that the `Loading sites` text should not be visible prior to attempting to click
=> [IS-71] chore(sites.spec): fix e2e

cypress/e2e/settings.spec.ts
This PR fixes our settings tests, which were failing because of the disabled google analytics (UA) field.  Closes IS-70
=> Fix: settings tests

src/constants/datadog.ts
Last time we had monitoring % at 20, this meant that some (actually most) of the sessions weren't recorded (events still logged, but session replay not there). because our cms isn't very stable right now, we want more info on user actions
set monitoring % to 100
=> chore(datadog): update rum session replay % to 100

cypress/e2e/workspace.spec.ts
many of the tests were failing due to the detached element issue
Closes IS-72
Added the force: true to force click on the DOM elements
- Details ...
Verified all tests in workspace e2e passes now:
=> Fix e2e for workspace

src/features/FeatureTour/FeatureTour.tsx, src/layouts/SiteDashboard/SiteDashboard.tsx, src/layouts/SiteDashboard/components/EmptyReviewRequest.tsx
This fix replaces the temporary hotfix for the feature tour conflict with the CMS FE modals (see https://github.com/isomerpages/isomercms-frontend/pull/1250)
Closes IS-150
Each component has a different zIndex. The feature tour elements should have a zIndex between that of the elements on CMS dashboard and workspace and the modals. This will prevent users from interacting with the feature tour components when modals are open
- Details ...
Run this locally and ensure you are able to use both the feature tour and modals without conflicts
=> Is 150 fix feature tour zindex

src/hooks/allSitesHooks/useGetAllSites.ts
We are hitting the API rate limit. 
It doesnt make sense to call this expensive call site on window refresh. As a low hanging fruit, not doing that. 
User needs to refresh the page in order to get the updated list of sites. This inaccuracy hit seems reasonable to improve perf. 
1. Open network tab
2. Notice you dont call `/sites` on window refresh
=> feat(getAllSites): optimise get all sites, dont reload on window focus

src/hooks/siteDashboardHooks/useGetCollaboratorsStatistics.ts, src/hooks/siteDashboardHooks/useGetReviewRequests.ts, src/hooks/siteDashboardHooks/useGetSiteInfo.ts
Problem
We are hitting the API rate limit.
Solution
It doesnt make sense to call this expensive call site on window refresh. As a low hanging fruit, not doing that.
Breaking Changes
User needs to refresh the page in order to get the updated site deets. This inaccuracy hit seems reasonable to improve perf.
Tests
Open network tab
Notice you dont call /dashboard on window refresh
=> feat(dashboard): Dont reload on window focus

src/layouts/ReviewRequest/Dashboard.tsx
This PR fixes an issue with the publish button not immediately reflecting the state of the reviewer's action. See video for current behaviour:
https://user-images.githubusercontent.com/22111124/236171845-5196365d-850a-4ea8-881c-e930184bbca4.mov
The issue is that the publish now button is determined by our backend review request state instead of the user's direct action - the behaviour of the button state has been replicated to the publish now button as well.
As a safeguard, to prevent users from being able to publish even if the approval state has failed, an additional guard has been added to the backend in PR #[752](https://github.com/isomerpages/isomercms-backend/pull/752), to be reviewed in conjunction with this PR.
=> Fix: publish button delay

src/layouts/Sites.tsx
See https://github.com/isomerpages/isomercms-backend/pull/754 for context
Closes IS-165
Conditionally render the "Updated at" field on '/sites' route
- Details ...
=> feat: make updated at field optional on sites page

src/layouts/ReviewRequest/components/ReviewRequestModal/ReviewRequestModal.tsx
This PR fixes an issue that occurs when attempting to make a pull request via the button in the header. The diff info is determined when the modal component is mounted, which happens on page load, even when the modal has not yet been opened. This means that users will not be able to see the changes directly after making an edit, which affects single changes the most since the pull request cannot be opened:
https://user-images.githubusercontent.com/22111124/236365515-4a6b3c10-47bc-4646-ae36-0a2d6b294918.mov
This behaviour would be made worse by our switch to not refetching on window focus - this would mean that users have to refresh their page to see any changes made. To fix this issue, we have 2 main options:
1. Invalidate the query key of the diff endpoint after every update to the repo …
=> Fix: refetch diff info when modal is opened

src/components/MediaSettingsModal/MediaSettingsSchema.jsx
This PR fixes a bug where our regex was not working properly for `.` in media file names. This was due to the change in behaviour where the user can no longer specify the extension of their file when uploading a new file, so the previous check to only run the regex on the portion before the last `.` no longer holds.
=> fix: media name regex check

src/layouts/layouts/SiteEditLayout/SiteEditHeader.tsx
The "Request Review" button should be disabled if there is an already existing PR in "Open" status
Closes IS-157
Fetch and filter the current list of PRs and if there exists a PR in Open state, we disable the button
- Details ...
You should be able to click on Review Request iff there are no open PRs. Else, the button should be disabled
=> Is 157 view request link does not bring user to the view request page

src/layouts/Workspace/Workspace.tsx
Previously `FeatureTour` was nested under `SiteEditLayout` despite not being a visual component. This resulted in a visual mismatch (see below)
shift `FeatureTour` to be outside `SiteEditLayout` (functionality works fine on local)
**before**
**after**
1. clear the `localStorage` of the feature tour key
2. go to a site w/ a review request pending on **email login**
3. navigate to the dashboard
4. ensure that the feature tour still works
5. go to the workspace
6. check that the components are visually consistent
=> fix(workspace): update feature tour hierarchy

cypress/e2e/files.spec.ts
This PR fixes our files test spec - it currently works on its own but not after being run sequentially with edit page, due to the partial match of the file being uploaded in the `editpage` spec (`singapore-pages` in `editpage`, `singapore` in `files`). The file being searched for in `files` has been changed to `singapore-file` in order to avoid this overlap.
=> fix: file name in test

netlify.toml, plugins/netlify/env/index.js, plugins/netlify/env/manifest.yml, plugins/netlify/env/package.json
Currently, engineers have to manually swap out the `REACT_APP_VERSION` on every release, which is annoying and prone to errors. 
Closes [IS-117]
Use a local netlify build plugin to inject the react app version prior to build as documented [here](https://answers.netlify.com/t/unable-to-set-npm-package-version-in-the-environment-variables/77584). 
[IS-117]: https://isomeropengov.atlassian.net/browse/IS-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Prior to testing, the deploy notes section below **must be done**
1. update the package version 
2. push the branch to `staging`
this was done with a fake package version of `0.0.0`, see below ss
1. remove the `REACT_APP_VERSION` env var from netlify (done for `staging`) since that is extra.
=> build(netlify): add plugin for netlify to inject app version

package-lock.json, package.json
The current datadog dashboard does not have source mappings, which results in the error logs not being very helpful for troubleshooting.
Closes [IS-100]
1. add the dependency into `package.json` 
2. configure build command in netlify + add env var. 
**before**
**after**
the site needs to be deployed first prior to running the below tets
- `DATADOG_API_KEY`: api key required to upload source maps. **not adding** to local dev/example env var on 1pw cos we won't be uploading source maps. this has been added on both `staging` and `production` on netlify
- `REACT_APP_URL`: url where the app is hosted. used to inject the path prefix for uploading source maps
**notes**
we might wish to change the `service` to an env var (or read from `package.json`) as it's being …
=> build(dd): add source maps for frontend 

src/components/Header.jsx, src/layouts/layouts/SiteEditLayout/SiteEditHeader.tsx
On the edit pages, request review button is still enabled when there is >= 1 PR in Open/Approved status
Closes IS-222
Add the same check we did for SiteEditHeader to Header component as well
- Details ...
Ensure that the review request button is disabled on all pages when there are >=1 PR in Open/Approved states
=> fix: add checks to Header component

cypress/e2e/settings.spec.ts, src/layouts/Settings/AnalyticsSettings.tsx
This PR fixes an issue where sites with facebook-pixel were unable to save their settings, due to a mismatch of expected type (number vs string). To be reviewed in conjunction with PR #[776](https://github.com/isomerpages/isomercms-backend/pull/776) on the isomercms backend repo, which has a more detailed writeup on the issue.
The change being introduced in the frontend is the facebook-pixel field enforcing that the length is 15.
=> fix: facebook-pixel expected type

src/api.js, src/services/CollaboratorService.ts, src/services/LoginService.ts
This PR enforces that our email params are converted to lowercase before being sent to the backend. See https://github.com/isomerpages/isomercms-backend/pull/785 for why this is necessary.
=> Fix: convert email to lower case

src/layouts/ReviewRequest/components/RequestOverview/RequestOverview.tsx
files/images don't have a meaningful diff so we should disable the button
- disable button (forgot to push prior to merge)
=> chore(request overivew): don't show diff for files/images

src/services/SiteLaunchService.ts
We want to trial out the site launch features with a subset of users. 
This PR aims to get early feedback on a hacky approach that the upcoming site launch PRs aims to implement this. 
We store the repos that we intend to trial this on as an env var in the FE separated by commas, and this state is held only in the FE.  
Benefits: 
+ easy to implement and subsequently remove
+ don't have to redeploy to add agencies that want to trial this out, just need change the env var
Limitations: 
- super hacky 
- technically backend APIs exposed to all users (but not really a concern since its an authenticated route anyways)
Ideally, we would leverage on a platform like Darkly to implement feature flags like this. While that is still a possible in the future, am opting for a more brute-force quicker …
=> feat(featureFlag): Site launch implementation

cypress/e2e/collaborators.spec.ts, cypress/e2e/editPage.spec.ts, cypress/e2e/files.spec.ts, cypress/e2e/folders.spec.ts, cypress/e2e/images.spec.ts, cypress/e2e/move.spec.ts, cypress/e2e/resourceCategory.spec.ts, cypress/e2e/resources.spec.ts, cypress/e2e/settings.spec.ts, cypress/e2e/sites.spec.ts, cypress/e2e/workspace.spec.ts, cypress/fixtures/constants.ts, cypress/fixtures/users.ts, cypress/support/index.d.ts, cypress/support/session.ts, src/App.jsx
**note: this requires the corresponding [be](https://github.com/isomerpages/isomercms-backend/pull/782) PR**
current e2e tests only cover the github flow. this PR adds in collaborator tests that cover the email login flow.
1. add in spec for collab tests
- `CYPRESS_BACKEND_URL` : backend url of our website, required to make the request to create a user
=> test(e2e): add initial collaborators e2e tests

src/layouts/ReviewRequest/components/DiffView/DiffView.stories.tsx, src/mocks/constants.ts
chromatic cannot render our diff view cos too big ._. also, because the diff view is randomly generated atm, this means that misc changes also incur a deploy to chromatic (cos the diff view value changed)
1. hard code `const` values for display
2. change # lines to 10 instead of 100 ._.
=> fix(constants): update diff values to be constant

src/layouts/Settings/AnalyticsSettings.tsx
**blocked on BE PR**
See [this](https://opengovproducts.slack.com/archives/C01D7PZLGR3/p1686531602263399) comment for context. basically CMS is too restrictive and we need to allow 16 digits also.
change fe validation to allow 16 digits
=> fix(analytics settings): change pixel to allow 15 - 16 digits

cypress/api/collaborators.api.ts, cypress/api/constants.ts, cypress/api/index.ts, cypress/api/pages.api.ts, cypress/api/reviewRequest.api.ts, cypress/e2e/collaborators.spec.ts, cypress/fixtures/constants.ts, cypress/fixtures/selectors/collaborators.ts, cypress/fixtures/selectors/common.ts, cypress/fixtures/selectors/index.ts, cypress/support/index.d.ts, cypress/support/session.ts, cypress/utils/collaborators.ts, cypress/utils/header.ts, cypress/utils/index.ts, cypress/utils/modal.ts, cypress/utils/navigation.ts, scripts/build.js, src/types/pages.ts
While writing the scaffold for dashboard tests, i realised that alot of our code could be reused across test specs. in order to facilitate this code sharing, utility code/constants in `collaborators.spec` have been sharded out into a utils + constants file, which will be used later on.
Similarly, whilst working on `dashboard.spec`, some selectors + util functions were also sharded out as they could be reused later on (notably comments/notifs)
- Shard out constants, utils and selectors 
- constants and selectors differ in that `constants` are a value, whereas `selectors` are meant to extract some HTML element 
- prefer util functions over commands to prevent pollution of `cy` namespace (see [here](https://github.com/isomerpages/isomercms-frontend/pull/1295#issuecomment-1582156373)) 
- This …
=> ref(e2e): test structure

cypress/e2e/dashboard.spec.ts, cypress/support/index.d.ts
Isomer doesn't have e2e tests at present. as part of the effort to add more e2e tests, this PR scaffolds dashboard tests. 
Closes IS-251
1. Add test cases for a few obvious cases
2. Add remaining test description + skip
**Notes**
1. for existing test cases - just see if there are additional conditions that we should be checking for. using `cypress:open` should allow the tests to be ran successfully
2. for test descriptions - check to see if there's any i've missed out.
=> test(e2e): scaffold dashboard tests 

.github/workflows/chromatic.yml
Chromatic builds keep hitting the quota
Comment `!run-chromatic` to trigger chromatic builds  
This is hard to test immediately since this event will only trigger a workflow run iff `chromatic.yml` is in on [default branch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment). To be clear, commenting `!run-chromatic` in this PR here will not trigger the workflow. 
However, this is pretty much a copy paste of the code already existing in for our [e2e triggers](https://github.com/isomerpages/isomercms-frontend/blob/develop/.github/workflows/trigger-e2e.yml) that we know works. 
I have also tried this code in my own [forked repo here](https://github.com/kishore03109/isomercms-frontend/pull/1) as a quick sanity check that this …
=> fix(chromatic cicd): fix over-building chromatic

cypress/e2e/dashboard.spec.ts, cypress/e2e/reviewRequests.spec.ts
Previously, rr tests were in `dashboard.spec.ts` - this PR shifts them out to be in their own spec file.
Closes IS-254
shift tests involving rr into another file, add a `before` + `beforeEach` hook to ensure pre-conditions satisfied for rr tests, nothing was changed in spec itself
=> test(spec): shard out tests for rr

README.md, cypress/SETUP.md
No docs previously for how to setup e2e test, which was confusing. This PR adds doc for setting up email + github e2e tests.
add doc
=> docs(setup): add docs for e2e setup

src/hooks/pageHooks/useCreatePageHook.jsx, src/hooks/pageHooks/useUpdatePageHook.jsx, src/types/error.ts, src/utils/axios.ts
This PR handles the v2 error returned by BE from CollectionPageService. Related PR: 
Closes IS-212
Checks if the returned err is a V2 err and displays the appropriate error message in toast.
- Details ...
Can test by commenting out special characters validation in `src/components/PageSettingsModal/PageSettingsSchema.jsx` and try to create and update a page with invalid filename (e.g. `SampleFile~~~`)
The error toast should show the error code and description returned by BE.
Deploy together with https://github.com/isomerpages/isomercms-backend/pull/802
=> feat: handle V2 errors for create and update pages

cypress/support/settings.ts
`setDefaultSettings` was using the same session creds as github but it is separate. this lead to a divergence in behaviour when `userType` was added as validation for e2e users, which causes a 401.
use `setGithubSessionDefaults`
=> fix(settings): use gh session defaults

cypress/support/session.ts, cypress/support/settings.ts, cypress/utils/cookies.ts, cypress/utils/session.ts
With Cypress upgrade, setting cookies needs an explicit domain set. In the absence of a domain, the cookies are not forwarded from FE to BE which causes the auth checks to fail and hence log out of the E2E tests.
Closes Is-270
Create an util function that injects domains into the cookies from the env var (`CYPRESS_BACKEND_URL`)
- Details ...
Ensure E2E tests run properly both against local and staging
=> feat: set cookies with domain

src/components/pages/EditorModals.jsx, src/components/pages/MarkdownEditor.jsx, src/layouts/EditPage.jsx
With the upgrade of mde editor to v5 in core-deps PR (https://github.com/isomerpages/isomercms-frontend/pull/1202/), the editor’s insert image and hyperlink does not seem to work.
Closes IS-271
I removed the use of `mdeRef` which no long contained the `codemirror` object we were looking for inside the ref. I suppose this is due to breaking changes from v4 to v5. See https://www.npmjs.com/package/react-simplemde-editor?activeTab=readme#autosaving for more information.
From docs, the new suggested method to retrieve the editor or codemirror is to use the hooks & callbacks provided.
Have tested this locally via E2E on editPage. Results show all tests are passing:
Note: Due to React's Strict Mode, the file selection dialog (`MediaCreationModal`) gets re-rendered twice in development. However, …
=> IS-271: fix bugs on simple mde editor

src/contexts/SiteLaunchContext.tsx, src/layouts/SiteDashboard/SiteDashboard.stories.tsx, src/layouts/SiteDashboard/SiteDashboard.tsx, src/layouts/SiteLaunchPad/SiteLaunchPad.stories.tsx, src/layouts/SiteLaunchPad/SiteLaunchPad.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchCheckList.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchDisclaimer.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchInfoGathering.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchPadBody.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchPadTitle.tsx, src/layouts/SiteLaunchPad/index.ts, src/routing/RouteSelector.jsx, src/theme/foundations/colours.ts, src/types/siteLaunch.ts
[Figma](https://www.figma.com/file/7OtNYkc4s9BkFk05ConEbd/%E2%AD%90-V1.5?type=design&node-id=9701%3A174582&t=IxYpSgyOgFghSKmQ-1) for site launch pad, without the checklist pages
Similar to #1296, this PR builds a storybook component on the site launch pad page. 
This is meant to be more of a UI focused PR only, the functionality + integration with backend will be introduced in a separate PR instead. Considered to be safe to merge to master since it be hidden behind a feature flag. 
https://github.com/isomerpages/isomercms-frontend/assets/42832651/ee6019c1-8456-4a94-a2ac-25ac40a22f9d
NOTE: The pages will loop back because the checklist page is not tackled in this PR (done in #1297)
New Storybook page for SiteLaunchPad
To view the site launch pad directly
1. add your site name to the env …
=> Feat(siteLaunchPad): Disclaimer pages Storybook

.eslintrc.json
Currently, eslint is not configured to warn properly. Suspect this is due to the recent change of made to eslint config in package.json. 
add warning
=> fix(eslint): warn for exhausive deps

src/contexts/DirtyFieldContext.tsx, src/layouts/Settings/Settings.tsx, src/layouts/Settings/components/OverrideWarningModal.tsx, src/layouts/layouts/SiteEditLayout/SiteEditHeader.tsx, src/layouts/layouts/SiteEditLayout/SiteEditLayout.tsx
See [IS-263](https://isomeropengov.atlassian.net/browse/IS-263?atlOrigin=eyJpIjoiZjI4NzA5YzA4ZjFmNGU0OWIwOWNjN2Q2NTM2MDMzZjgiLCJwIjoiaiJ9)
1. add context between child component that knows the state (`Settings`) and the component that triggers the modal warning. We require the context because the `set/get` have a few degrees of separation + we need to pass data from the child back up 
2. render modal when state is `dirty` and trigger redirect only on ack
[IS-263]: https://isomeropengov.atlassian.net/browse/IS-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(settings): show warning modal on leaving when there are dirty fields

src/components/Header.jsx, src/components/MenuDropdownButton/MenuDropdownButton.stories.tsx, src/layouts/layouts/SiteEditLayout/SiteEditHeader.tsx
Following up from @NatMaeTan 's comments from [Reviewing Build 1439 • isomerpages/isomercms-frontend](https://www.chromatic.com/test?appId=61fcc8e14c3af9003a102ac9&id=64382b0ca3055f62d610a93c)
Closes IS-225
Update button text
- Details ...
- Ensure that the buttons for all staging reads as "Open Staging"
=> feat: update text to be Open Staging

src/hooks/reviewHooks/useGetReviewRequest.ts, src/layouts/ReviewRequest/Dashboard.tsx, src/layouts/ReviewRequest/components/Comments/CommentsDrawer.tsx
Previously, we relied on redirection of users away from the review request to prevent them from taking any action when the review request is invalid. However, this leads to a delay between content paint and redirection (as we want the user to be able to interact with elements on the page), which results in users being able to access a old merged or closed rr, open the comments and see the comments prior to redirect. 
pass an `isDisabled` prop. technically we could ping the server using `getReviewRequest` and check status in `CommentsDrawer` but because the component seems like its state should be controlled by the parent, prop passing is preferred instead (same computed data used for redir + disablign icon button)
next, if a rr fails to fetch from backend, we get the error message and …
=> fix(comments): disable comment drawer if rr has invalid status

cypress/e2e/dashboard.spec.ts, cypress/e2e/reviewRequests.spec.ts, cypress/fixtures/constants.ts, cypress/utils/dashboard.ts, cypress/utils/header.ts
Lacking E2E test for dashboard
Closes IS-260
Adds E2E tests for dashboard
- Details ...
Ensure that `dashboard.spec.ts` E2E test passes successfully
=> feat: E2E tests for dashboard

src/hooks/settingsHooks/useGetSettings.ts
This PR fixes an issue with our env vars - netlify passes env vars as strings, which means that interpreting it as a boolean value does not work as expected. This PR modifies the way we parse the `REACT_APP_IS_SITE_PRIVATISATION_ACTIVE` to ensure we parse the boolean value correctly.
=> Fix: parse env var from string to boolean

.env-example, package.json, src/components/FeedbackModal/FeedbackModal.stories.tsx, src/components/FeedbackModal/FeedbackModal.tsx, src/components/FeedbackModal/index.ts, src/constants/localStorage.ts, src/hooks/useFeedbackDisclosure.ts, src/hooks/useRedirectHook.jsx, src/layouts/layouts/SiteEditLayout/SiteEditLayout.tsx, src/utils/pages.ts
right now isomer has no way of collecting feedback from users. this adds a modal that shows an embedded form, with some additional logic to avoid repetitive pings on the user.\
see the modal [here](https://www.chromatic.com/component?appId=61fcc8e14c3af9003a102ac9&csfId=components-feedbackmodal&buildNumber=1868&k=64ba05a458dfcb14aa7fc25f-1200-interactive-true&h=12&b=-3)
Closes IS-324
1. add modal, set it on `SiteEditLayout` -> this is because the `SiteEditLayout` is set on almost all editing layouts for our CMS
2. write hook to determine when to trigger the modal
- currently, this is in intervals of 3 wks since the last seen timing (or if it's the first ever view) + whether the env var is set. the interval of 1 wk was chosen so that there's enough time lapse between toggles and so that we …
=> feat(form): add NPS modal

cypress/api/reviewRequest.api.ts, cypress/e2e/comments.spec.ts, cypress/utils/dashboard.ts
Added E2E tests for comments feature of review requests.
Closes IS-258
**Note**
Occasionally `cy.request` fails and return undefined for reasons unknown. This will cause the tests to break.
Requires #1338 to be merged first.
=> feat(e2e): e2e tests for comments

cypress/e2e/collaborators.spec.ts, cypress/e2e/comments.spec.ts, cypress/e2e/notifications.spec.ts, cypress/e2e/reviewRequests.spec.ts, cypress/fixtures/constants.ts, cypress/support/session.ts
The terms collaborator and contributor has semantic differences our our code base.
To be reviewed tgt with [be pr](https://github.com/isomerpages/isomercms-backend/pull/857)
Changing collab to contri naming here for calrity. 
- Details ...
Ran collaborator tests spec here, same result as last week during release.
=> chore(e2e): change naming for clarity

cypress/SETUP.md
Currently, we are seeding the rows manually for our e2e tests. However, writing directly to DB is generally not good eng practice and can cause problems like [Postgres's primary key sequence going out of sync](https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync). 
This PR aims to alievate that by just providing 2 commands to run instead.
1. run 
```
INSERT INTO sites (name, site_status, job_status, creator_id)
VALUES ('e2e email test site 2', 'INITIALIZED', 'READY', 1);
INSERT INTO repos (name, url, created_at, updated_at, site_id)
SELECT 'e2e-email-test-repo 2', 'https://github.com/isomerpages/e2e-email-test-repo-2', NOW(), NOW(), id FROM sites WHERE name = 'e2e email test site 2';
```
2. verify that rows are properly added in …
=> feat(setup.md): add command

cypress/e2e/collaborators.spec.ts, cypress/e2e/comments.spec.ts, cypress/e2e/notifications.spec.ts, cypress/e2e/reviewRequests.spec.ts, cypress/fixtures/constants.ts, cypress/support/session.ts
This reverts commit 7ad153bc452ba7be24ab1dea982f5cd9741146b9.
I shot myself in the foot here @.@ 
The pain point I was trying to alleviate here was that `setEmailSessionDefaults` forces `collab@e2e.gov.sg` to be a contributor role, and my (wrong) assumption was that we were trying to maintain that invariant, so I thought it would be better to name it as such for clarity. After talking with chin, realised that we intend to make this collab also have the admin role if needed (or at least the intention behind this design is), which makes the changes introduced in #1362 confusing as I can now have a contributor who has admin rights. 
Revert changes. Tbh, it doesnt really solve the pain point I intended to solve, but I have a separate PR for this coming up!
=> Revert "refactor(e2e): change naming (#1362)"

src/layouts/SiteLaunchPad/SiteLaunchPad.stories.tsx, src/layouts/SiteLaunchPad/SiteLaunchPad.tsx, src/layouts/SiteLaunchPad/index.ts, src/routing/RouteSelector.jsx
Now that there are different flows for the site launch flow, it would make sense to have various flows for the corresponding storybooks for faster reviewal process for upcoming PRs. 
Individual pages have their own storybook.
=> feat: storybook improvement for site launch pad

src/hooks/siteDashboardHooks/useGetSiteLaunchStatus.ts
During the site launch process, users would have to do a hard refresh to get the lastest site launch results. This is not ideal.
Refresh behaviour every 5 mins. tbh, the 5 mins is an arbitarary number, we can adjust this param as this feature is more used by our users in the future. This is just to prevent the need for a hard refesh when the launch is success.
=> feat(site launch): add in refetch behvaiour

src/layouts/SiteDashboard/SiteDashboard.tsx, src/layouts/SiteLaunchPad/SiteLaunchPad.tsx, src/utils/siteLaunchUtils.ts
No access controls for site launch feature. 
Only allow site admins to launch sites. Currently, our CMS defines admins as someone whose email ends with a `.gov.sg`. Can be reviewed with [be pr](https://github.com/isomerpages/isomercms-backend/pull/873)
View of non-admin email user: 
View of contributor access site launch pad page: 
https://github.com/isomerpages/isomercms-frontend/assets/42832651/8f294c51-1510-4cfe-ae2b-5eb0872c01cb
=> IS-349-FE-only-admins-can-launch-sites

cypress/e2e/homepage.spec.ts, cypress/fixtures/constants.ts, cypress/fixtures/selectors/dnd.ts, cypress/utils/dnd.ts, package-lock.json, package.json, src/components/homepage/HeroDropdown.jsx, src/components/homepage/HeroSection.jsx, src/layouts/EditHomepage.jsx
Previously, homepage did not have any e2e tests. This PR adds e2e tests for homepage.
1. change dnd package - old dnd package had an issue with react strict mode, which causes it to crash on local.
2. add tests for special cases and drag/drop functionality
- see the base drag and drop spec from react beautiful dnd [here](https://github.com/atlassian/react-beautiful-dnd/blob/master/cypress/integration/reorder.spec.js) 
- other special cases are given on the ticket and guarntee some baseline behaviour
=> test(e2e): add homepage 

src/components/Header/Header.stories.tsx
Chromatic builds are failing + keeps building dev. Not 100% sure why, but the facts are:
1. We know that the way Chromatic works is that it compares UI changes against a baseline
2. Chromatic keeps building develop when `!run-chromatic` is commented on the PRs
3. There exists errors in the current develop. 
4. By extension, our baseline (develop) has errors.
This PR attempts to test the hypothesis that is the components are fixed, does the chromatic functionality gets back up. However, I cannot test this out until this is merged into develop. 
[Note: this is a current blocker for DS upgrades, UI review of site launch changes that affect the current sprint]
=> fix(header): fix context for storybook

src/hooks/settingsHooks/useUpdateSettings.ts, src/layouts/Settings/Settings.tsx
We have a bug in production, see video here: 
https://github.com/isomerpages/isomercms-frontend/assets/42832651/ab2ce646-ed4a-483a-89ed-a2b39705a9d7
This is not because of design system, I was able to replicate this even with chakra ui's toast. This seems to suggest the bug lies in how we are using this hook. video here:
https://github.com/isomerpages/isomercms-frontend/assets/42832651/c3023947-426c-4b45-bc94-496a7acacad4
I think I know the cause for this, please feel free to correct me on this ya. 
1. This does not happen at all the places of the code base. 
eg.
https://github.com/isomerpages/isomercms-frontend/assets/42832651/43a853dd-daec-4fe8-9d7c-7ab2cf2eeddc
2. There exists a useEffect in `Settings.tsx` that states
```
// Reset cache on success
useEffect(() => {
if (isSuccess) {
// …
```
=> fix(useToastHook): don't re-render text field on focus

src/components/FeedbackModal/FeedbackModal.tsx, src/components/Rating/Rating.tsx, src/contexts/LoginContext.tsx, src/hooks/useFeedbackDisclosure.ts, src/hooks/useSubmitFeedback.ts, src/services/FeedbackService.ts, src/theme/components/Rating.ts, src/theme/components/index.ts, src/types/feedback.ts, src/types/user.ts
**NOTE: There's an extra commit because the previous PR was merged into `develop`**
**Please skip `useFeedbackDisclosure`**
**To be reviewed w/ BE PR** ([here](https://github.com/isomerpages/isomercms-backend/pull/863))
Previously we were using FormSG as a backend. This updates the nps ui to the one in the figma and hits a backend endpoint.
1. add more data to `LoginContext` so we know the `userType` 
2. revamp UI
3. Add calls out to backend to hit our new endpoint 
**Notes**
This PR is blocked by the design system upgrade
=> feat(nps): update UI

scripts/build.js
The reset e2e task was resetting an incorrect branch on e2e-test-repo, which causes e2e tests to not start from a clean slate and throws unrelated errors when running e2e tests.
**Bug Fixes**:
- The reset-e2e test was resetting the `master` branch, when it should be resetting the `staging` branch (to match with the value of `BRANCH_REF` in the backend, as that is the branch that the CMS edits).
- Run some e2e tests, then run `npm run reset-e2e` and verify that the e2e-test-repo has been correctly reset
*None*
=> fix(e2e): fix branch to reset e2e test repo on

.github/mergify.yml
Mergify keeps going to old PRs and pinging the team for reviews, when they have already been merged or closed.
Fix the conditions to only ping the team for stale and open PRs.
=> ci(Mergify): only request reviews for stale open PRs

cypress/api/collaborators.api.ts, cypress/e2e/reviewRequests.spec.ts, cypress/utils/collaborators.ts
This PR fixes our review request tests so that it's no longer dependent on the number of collaborators - previously we were removing collaborators via the UI, which caused the tests to break if we did not have the correct number of collaborators. This PR modifies the util method `removeOtherCollaborators` to make an api call to our backend directly in order to bypass this issue.
=> fix: move removeOtherCollaborators to use api call directly

src/styles/isomer-cms/elements/breadcrumb.scss, src/styles/isomer-cms/elements/form.scss, src/styles/isomer-cms/elements/modal.scss, src/styles/isomer-cms/pages/Editor.module.scss, src/styles/isomer-template.scss, src/styles/preview-panel.scss
There are 2 user-facing problems, post design system upgrade (tbh idk why the upgrade causes it too).
Firstly, the homepage title was extremely small.
Secondly, hovering over the key-highlights section does not display the cursor as a pointer.
Closes IS-413
1. For the homepage title, it was observed that the css variables required were missing. to fix this, the actual css file was inspected and the variables defined therein was **copied** over. Do take note that somehow, `sgds` styling is applied **over** our template styling despite the the `isomer-template` import occurring later... (see `.preview-panel`)
**Hero title post removal**
2. Removed `cursor: default` in our **template** styling so that the cursor will be `pointer` when hovering over key-highlights. To verify this, i checked …
=> fix(preview): update styling

.github/workflows/chromatic.yml
Currently, while the GH actions pass for comment based trigger, it keep building develop. The issue stems from `actions/checkout@v1` checks out the branch that tiggered the workflow. However, the `issue-comment` seems to be a separate [trigger by itself](https://github.com/actions/checkout/issues/331), and as such this feature does not work as intended.  
Use solution as described [here](https://github.com/actions/checkout/issues/331#issuecomment-1438220926). This leverages on the fact that "issue number" === "pr number".
I cannot test this unless this code since [this event will only trigger a workflow run if the workflow file is on the default branch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows).
=> fix(chromatic): comment based chromatic builds

src/layouts/SiteDashboard/SiteDashboard.tsx, src/layouts/SiteLaunchPad/SiteLaunchPad.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchCheckList.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchDisclaimer.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchInfoGathering.tsx, src/types/siteLaunch.ts, src/utils/site-launch/domain-nature.ts
During the user trial, user was confused on the format in which to add in the url  + which option to choose regarding the `www` vs `non-www` (this was already a power user of isomer who already had experience launching numerous sites before. 
This PR addresses that pain point to make the flow clearer. Note that the general rule of thumb here is that 3rd level domains -> have www, 4h level -> no www
The exception here are schools with `<blah>.moe.edu.sg`, which we have www at the 4th level, and no www at the 5th level and above.
This PR also adds a bit of loose URL validation (commented in the PR). My hunch here is that strict url validation is not a requirement here, and thus I rather keep this loose for flexibility + avoid false negatives. …
=> feat(site launch): recommending www domain 

src/contexts/SiteLaunchContext.tsx, src/layouts/SiteDashboard/SiteDashboard.stories.tsx, src/layouts/SiteDashboard/SiteDashboard.tsx, src/layouts/SiteLaunchPad/SiteLaunchPad.stories.tsx, src/layouts/SiteLaunchPad/SiteLaunchPad.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchCheckList.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchDisclaimer.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchFinalState.tsx, src/layouts/SiteLaunchPad/components/SiteLaunchInfoGathering.tsx, src/mocks/constants.ts, src/types/siteLaunch.ts
There exists integration work to get the functionality of the final screens to work. This PR addresses this. 
The page logic is shifted over to the main dashboard page. This is because the behaviour of when the final screens are shown is dependent on the api call + it was needed throughout multiple components, and this this approach was taken to prevent prop drilling.  
- Details ...
There are 4 main cases I am testing this flow on. For ease of testing, I am manually refetching the react query key, but in reality this is refetched once every 5 mins. I am also mutating the database entries directly cuz actual site launch is slow.
concretely, these are the mapped DB values to what the `siteLaunchDto` will have: 
`site_status` = `INITALIZED` and `job_status` = `READY` -> …
=> feat(sl): integrate screens with be

src/layouts/EditPage.jsx, src/utils/cspUtils.js
This PR fixes an issue where `checkCSP` could be run before the csp was retrieved. This PR adds an additional check that both csp and editorvalue have loaded before the editPage content is populated.
Also fixes an issue where we were searching for the wrong string for *
This issue doesn't seem to occur consistently - it seems that the cause might be a delay in retrieving csp, so we can trigger it by setting an extra delay on the getCsp hook. 
Before: content loads immediately, images show up as blocked
https://github.com/isomerpages/isomercms-frontend/assets/22111124/7388554d-823e-4dc9-9045-8843b9f6e4f9
Before (even longer delay for csp to load): 
https://github.com/isomerpages/isomercms-frontend/assets/22111124/4cce1d2b-430f-4e7b-a9a7-d7f3f94231b4
After: content takes time to load in …
=> fix: conditional for checkCSP 

cypress.config.ts
E2e keeps crashing -> not productive 
redce mem usage + enable experimental feature. Not too worries about the experimental feature since the testing of e2e is internal and as such we can be more risk adverse on this. 
Before this, I wasnt able to even complete 4 tests for `move`, after this change the entire test suite was able to run.
=> fix(e2e): reduce mem usage

package-lock.json, package.json
This PR fixes an issue where errors on dev were showing up in an overlay -
This prevents us from running tests suites locally. It is likely that this issue was due to the default behaviour of `webpack-dev-server` changing to automatically include the overlay when errors are encountered. This PR explicitly downgrades the package so that we can run tests normally on local.
=> chore: downgrade webpack-dev-server

package-lock.json, package.json, src/components/homepage/HeroSection.jsx, src/components/homepage/InfobarSection.jsx, src/components/homepage/InfopicSection.jsx, src/components/homepage/ResourcesSection.jsx, src/layouts/EditHomepage.jsx, src/layouts/components/Editable/Editable.tsx
Previously, the new components were introduced but not used. This PR replaces the existing stuff in `EditHomepage` w/ the new components
The steps to replacement will be listed below for clarity: 
1. Replace `Draggable` with `Editable.Draggable` as resp shifted
2. for each component, shift the creation within the `map` loop into 2 segments - first, creating the `Droppable` (this is the actual dnd stuff) and secondly, creating the body (this is the `form` - retained existing code as-is)
3. for each `<Editor_type>Section.jsx`, the code dictating the expand/collapse logic was removed. (shifted into respective `AccordionItem`)
- see #1403 for base list
no vid cos laze
=> ref(homepage): use new components

src/components/homepage/HeroSection.jsx, src/layouts/EditHomepage.jsx
Currently, our existing homepage has the site notification on top **as a separate block.** However, the figma wants the site notification to be shifted into the hero sectoin
Closes IS-428
1. **Temporary measure**: shift notification section into `HeroSection` and add a prop for `notification`
2. For stuff in `HeroSection` where we were using our own home-rolled `Form` components prior to design system, shifts those to design system **with the exception of `FormFieldMedia`**. This is because `FormFieldMedia` is more involved + has modal so deferred fo rnow
3. in `EditHomepage`, removed unused code 
Screenshots:
=> feat(homepage): subsume site notif

src/layouts/EditHomepage.jsx, src/layouts/components/Editable/Editable.tsx
There are a couple of styling issues which do not line up with design. These will be described below. In addition, an error border is added to the accordion when collapsed.
**Design issues**
1. Hover states are applied across the **whole accordion** - this means that on expansion, the hover state is applied to the body also
2. padding issues wrt the `DragHandle` 
1. For hover states, apply the `hover` conditionally only on the `Flex` wrapper for the accordion header (idk if this term makes sense). This necessitates the render prop pattern to access internal state on the `AccordionItem` - see [here](https://chakra-ui.com/docs/components/accordion#accessing-the-internal-state) 
- current (and correct) behaviour is to have `hover` **only on collapsed states**
2. For the `DragHandle`, it has …
=> ref(editable): style fixes + error hover

src/contexts/DragDropContext.tsx, src/hooks/useDrag.tsx, src/layouts/EditHomepage.jsx, src/layouts/components/Editable/Editable.tsx, src/layouts/components/Homepage/HeroBody.tsx, src/layouts/components/Homepage/HeroDropdownSection.tsx, src/layouts/components/Homepage/InfobarBody.tsx, src/layouts/components/Homepage/ResourcesBody.tsx, src/types/homepage.ts
Currently, our hero component has an outdated design. Design has a new version of the hero dropdown, which is implemented in this PR.
Closes IS-386
1. Define new component, `HeroBody`, that wraps both `Dropdown` and `Highlights` 
- this could potentially take `children` and only do styling + the 3 forms which, in hindsight, seems like a better solution tbh
2. Define new component, `HeroDropdownSection`, that does the actual dnd stuff + handles the form fields for the dropdown as a whole. 
3. Adds a new `DragDropContext` - we require this because `Editable.Draggable` requires a `onDragEnd` prop, which is defined _very_ high up the component tree but is the sole "source of truth" for dnd logic. This is similar in function to `react-hook-form`'s `FormProvider`, which just does a re-export of …
=> ref(homepage): adds new dropdown component for hero

.github/workflows/chromatic.yml
Chromatic keeps building unnecessarily, even if the trigger words are not being used.
**Bug Fixes**:
- The Chromatic action has been adjusted to only run the Chromatic-related tasks if the pre-requisite conditions were met.
- The checkout mechanism has also been adjusted.
- This way to checkout was [suggested in this PR](https://redirect.github.com/actions/checkout/pull/1248).
- It is also verified that the full commit history is available [in this action run](https://github.com/dcshzj/test-checkout/actions/runs/5947111945/job/16128699082) (which is what Chromatic needs).
A little hard to test, can only merge and hope for the best.
*None*
=> fix(chromatic): only proceed if conditions are met

.github/workflows/chromatic.yml
Chromatic builds do not run on pushes to the `develop` branch, which causes Chromatic to be unable to update its baseline.
**Bug Fixes**:
- Chromatic now builds for pushes to the `develop` branch, so that the baseline can be updated on Chromatic
- It is important that this gets done, as we no longer build Chromatic automatically on every pull request. This means that there may be frontend changes that land into the `develop` branch, but Chromatic does not know. We cannot guarantee that everyone will force a Chromatic build for their PRs, which may cause the baseline to be incorrect over time.
I hope it works, can only know after merging.
*None*
=> fix(chromatic): trigger build for push to develop for Chromatic baseline

src/layouts/FeatureFlaggedHomepage.tsx, src/layouts/LegacyEditHomepage/LegacyEditHomepage.jsx, src/layouts/LegacyEditHomepage/components/HeroButton.jsx, src/layouts/LegacyEditHomepage/components/HeroDropdown.jsx, src/layouts/LegacyEditHomepage/components/HeroSection.jsx, src/layouts/LegacyEditHomepage/components/InfobarSection.jsx, src/layouts/LegacyEditHomepage/components/InfopicSection.jsx, src/layouts/LegacyEditHomepage/components/KeyHighlight.jsx, src/layouts/LegacyEditHomepage/components/NewSectionCreator.jsx, src/layouts/LegacyEditHomepage/components/ResourcesSection.jsx
Previously, when we merged the feature flagged PR, i only copy pasted the `EditHomepage.jsx` file. however, within `EditHomepage.jsx`, it was also referencing other files that had been previously deleted. This wasn't an issue as it branched off a base that had said legacy files, but on merge back to `develop`, the legacy files got deleted, which led to an error.
1. add legacy files in
2. fix import
=> fix(legacyedithomepage): add back missing imports

src/layouts/components/Editable/Editable.tsx
It is difficult to identify the different caveats and/or preconditions associated with the `Editable` components. 
add jsdoc to the different confusing `Editable` elements so that on hover, ppl can read and get context.
=> docs(editable): add docs for `Editable` 

src/layouts/EditHomepage.jsx, src/layouts/components/Editable/Editable.tsx, src/layouts/components/Homepage/HeroDropdownSection.tsx, src/layouts/components/Homepage/HeroHighlightSection.tsx
Previously, we hid the `DragDropContext` inside our `Droppable` to allow simpler api for devs, as only 1 level of drag and drop was supported. However, new pages require nested dnd, which means that this is no longer feasible.
- shift out the context.
=> fix(editable): shift out context to allow nested dnd

cypress/e2e/collaborators.spec.ts, cypress/e2e/comments.spec.ts, cypress/e2e/resources.spec.ts, cypress/e2e/workspace.spec.ts, cypress/utils/collaborators.ts
Workspace tests look for Folders impact navigation on your site. even though the string no longer exists on the workspace
Resource tests look for "Successfully deleted directory", but should be "Successfully deleted item"
Collaborator tests use removeFirstCollaborator instead of removeOtherCollaborators
Closes IS-417
Update the assertions
- Details ...
Ensure E2E tests for workspace, resources and collaborator specs pass
=> IS-417 - Fixing Selector Issues in E2E tests

src/layouts/EditHomepage.jsx, src/layouts/EditHomepage/EditHomepage.jsx, src/layouts/EditHomepage/HomepagePreview.tsx, src/layouts/EditHomepage/constants.ts, src/layouts/EditHomepage/index.ts, src/layouts/EditHomepage/utils.ts, src/types/homepage.ts
There were many constants whose reference wasn't clear in `EditHomepage`. This PR shifts them out for clarity and exposes a helper method to construct the error message.
1. shift constants out to `ts` file. 
2. expose util method for getting error object.
=> chore(edithomepage): shift constants out

src/__tests__/RouteSelector.spec.jsx, src/layouts/EditContactUs.jsx, src/layouts/FeatureFlaggedContactUs.tsx, src/layouts/LegacyEditContactUs.jsx, src/layouts/components/ContactUs/CardsSection.tsx, src/layouts/components/ContactUs/ContactCard.tsx, src/layouts/components/ContactUs/GeneralInfoSection.tsx, src/layouts/components/ContactUs/LocationCard.tsx, src/layouts/components/Editable/AddSectionButton.tsx, src/layouts/components/Editable/Editable.tsx, src/routing/RouteSelector.jsx, src/utils/validators.js
Closes IS-474.
- The contact us page editor has been refactored to make use of the new stylings. This is placed behind a feature flag for now.
**BEFORE**:
**AFTER**:
*None*
=> ref(contactus): stylings for contact us page editor

src/layouts/components/Editable/Editable.tsx
Minor change to the draggable icon button to make pointer-events:none - this is required to support nested drag and drop for our current workaround
=> chore: set pointerEvents to none for draggable icon button

src/constants/featureFlags.ts, src/layouts/FeatureFlaggedContactUs.tsx, src/layouts/FeatureFlaggedHomepage.tsx, src/layouts/FeatureFlaggedNavBar.tsx, src/types/featureFlags.ts
Previously we were using manual feature flags, we want to adopt growth book (gb) now to use a % based rollout.
use growthbook sdk + define constants
=> feat(feature-flag): add feature flag from gb

src/layouts/components/Homepage/HeroBody.tsx, src/layouts/components/Homepage/InfopicBody.tsx
`notifications` and `infopic` had `optional` tags, which should be removed per design
set `isRequired` to `true` even though it isn't really :(
=> fix(edithomepage): remove optional tags

.github/workflows/chromatic.yml
Chromatic snapshots are expensive and we should have a way to get a snapshot only when we really need one.
**Features**:
- A second attempt of triggering Chromatic snapshots via a PR comment. Here's what changed from previously:
- A new `branchName` configuration has been added. This is needed to let Chromatic be aware of where the snapshot is coming from. Without this configuration, Chromatic will pull from the `GITHUB_REF` environment variable, which is always `develop` when [on the `issue_comment` workflow](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment). This causes Chromatic to constantly rebuild the `develop` branch and causing our baselines to always reset.
- A new `autoAcceptChanges` configuration has been added. …
=> feat: re-introduce comment-based trigger for Chromatic

src/layouts/components/ContactUs/ContactCard.tsx, src/layouts/components/ContactUs/GeneralInfoSection.tsx, src/layouts/components/ContactUs/LocationCard.tsx, src/layouts/components/Editable/AddSectionButton.tsx, src/layouts/components/Editable/Editable.tsx
Closes IS-538.
- Some padding and copy changes were made based on the feedback obtained from @sehyunidaaa.
*None*
=> chore(contactus): styling fixes based on design feedback

src/layouts/EditHomepage/EditHomepage.jsx
Previously, the dropdown title could not be edited properly
Closes IS-547
spread the correct property
=> fix(edithomepage): spread correct property

src/layouts/components/ContactUs/LocationCard.tsx, src/layouts/components/Editable/Editable.tsx, src/layouts/components/NavBar/GroupMenuBody.tsx
Previously, when we cancelled deletion of a sub-menu, there would be a cursor popping up on the button due to usage of `contentEditable`. 
Make only the **top portion** of the accordion teh drag handle. this was preferred over making the icon the drag handle as it preserves existing behaviour on production. 
as users have been trained that the entire card can be dragged, we don't want to break that existing mental model. users are also unlikely to drag the body due to the large # of inputs there and small draggable area, so this is a compromise we're (me + design) is ok with for now. 
**Video**:
**old behaviour w ss**
link [here](https://www.notion.so/opengov/Restyling-feedback-3a4dc84523ff44529e0644ae85b4e0ca?pvs=4#9f212ed8d4e94acfb2253e9d8f2f3572)
**new behaviour**
=> fix(editable): change drag handle to be on top part only

src/layouts/components/ContactUs/ContactCard.tsx, src/layouts/components/ContactUs/LocationCard.tsx, src/layouts/components/Editable/Editable.tsx, src/layouts/components/Homepage/HeroDropdownSection.tsx, src/layouts/components/Homepage/HeroHighlightSection.tsx, src/layouts/components/Homepage/InfopicBody.tsx, src/layouts/components/NavBar/GroupMenuBody.tsx
nested cards (yeet) merged ytd but only for contact-us 
buttons are full width on hover for contact-us 
use `isNested` prop + fix `boxShadow` for nested cards
remove `w = 100%` for full width buttons
make infopic take full width for form field media
=> fix: styling

src/layouts/components/Editable/Editable.tsx
The hover and focus states for the title text in a nested editable accordion was not implemented properly.
**Bug Fixes**:
- The group hover selector is now fixed
- The font colour change for the title text on focus state is now supported
https://github.com/isomerpages/isomercms-frontend/assets/27919917/dd8d596f-6b5d-4931-9da1-d3ad45a1c4c8
*None*
=> fix(editable): hover and focus states for title text

src/layouts/EditHomepage/EditHomepage.jsx, src/layouts/components/Homepage/HeroDropdownSection.tsx
Previously the highlight section was missing properties due to a missing spread after rebase (sadge). This led to the input being blank on initial load (edits etc will still work)
spread the property of `section.hero`
=> fix(edithomepage): spread properly

src/layouts/EditHomepage/EditHomepage.jsx, src/layouts/components/Homepage/HeroBody.tsx, src/layouts/components/Homepage/HeroDropdownSection.tsx
Previously we default to `highlights` - however, a bug existed where if you had empty highlights, adding the highlight options would not work **on preview** (because our preview checks using the `!hero.dropdown` property 
update `HeroBody` component so that we take an `initialSectionType` so it fits with how preview does the dropdown/highlight
=> fix(herobody): solves empty highlight deafult issue

src/layouts/EditContactUs.jsx
Closes IS-532.
**Bug Fixes**:
- On the backend, the `feedback` key [needs to be a string, even if it is not required](https://github.com/isomerpages/isomercms-backend/blob/9cb60e6623f7abb86166c0bf9d046d6123d892ce/src/validators/RequestSchema.js#L20). However, because of the use of `_.cloneDeep()`, the `feedback` key will be deleted if the user did not specify a feedback URL, which causes a validation error. This change enforces that the `feedback` key is always present and sets it to be an empty string if not provided.
*None*
=> fix(contactus): ensure feedback key is present as string

package-lock.json, package.json, src/utils/siteColorUtils.js
The site colours are not available in SCSS as they are only available at runtime. This meant that we cannot make use of CSS classes that needs to change based on the site colours defined by the user.
- This change adds the primary and secondary colours that can be set by the user for the site as CSS variables.
- The secondary colour hover has also been implemented the same way as the template, which is to lighten by 10%.
- `tinycolor2` : Library for performing SCSS's lighten on a provided HEX code
=> fix(styles): introduce site colors as CSS variables

src/layouts/EditHomepage/HomepagePreview.tsx, src/styles/isomer-template/helpers.scss, src/styles/isomer-template/homepage/announcements.scss, src/styles/isomer-template/styles.scss, src/templates/homepage/AnnouncementsSection.tsx, src/types/homepage.ts
Closes IS-517.
**Features**:
- The homepage editor now has the ability to preview a new announcements component.
No tests are currently available, as the announcements component can only be previewed once the left sidebar is updated to support editing of the new announcements component.
*None*
=> feat(homepage): add preview for announcements component

src/templates/homepage/AnnouncementsSection.tsx
The announcements component on the template has an extra padding that is missing in the CMS homepage preview.
- The missing padding has been added to the announcements preview component.
*None*
=> chore(announcements): add missing padding for item

src/layouts/components/Homepage/HeroBody.tsx
we need to add new layout options for hero banner
- Add panels on the hero section first
- changed hero body so that it contains the new options now
=> feat(herobody): add first pass of layout

src/layouts/components/Homepage/HeroBody.tsx, src/styles/isomer-template.scss, src/styles/templates/components/hero.scss, src/styles/templates/theme/background.scss, src/styles/templates/theme/layout.scss, src/styles/templates/theme/margin.scss, src/styles/templates/theme/padding.scss, src/styles/templates/theme/text-styles.scss, src/templates/homepage/HeroSection/HeroCenteredLayout.tsx, src/templates/homepage/HeroSection/HeroImageOnlyLayout.tsx, src/templates/homepage/HeroSection/HeroSection.tsx, src/templates/homepage/HeroSection/HeroSideLayout.tsx, src/types/hero.ts, src/types/homepage.ts
Previously, homepage did not have any previews for the hero side layout. This PR adds the previews in.
1. add template component from preview
2. add css styling for template component
- this is a **stop gap** measure cos this PR came out **before** the PR for helpers so i'll have a PR post-merge to update. (easier to do then)
=> feat(homepage): add previews for side layout

src/templates/homepage/HeroSection/HeroCenteredLayout.tsx, src/templates/homepage/HeroSection/HeroDropdown.tsx, src/templates/homepage/HeroSection/HeroSection.tsx, src/templates/homepage/HeroSection/HeroSideLayout.tsx
The existing hero section does not have a dropdown. This adds the preview component for the dropdown in.
Copy paste over the dropdown from the template code (with modification so it can be consumed by react)
=> feat(hero-section): adds dropdown

src/templates/homepage/HeroSection/HeroImageOnlyLayout.tsx, src/templates/homepage/HeroSection/HeroSection.tsx
Currently our image only layout only has support for highlights and not dropdown. This PR adds it in
Follow conditionals from template and add the `HeroDropdown` in to `HeroImageOnlyLayout`
=> feat(heroimageonlylayout): add dropdown

src/constants/homepage.ts, src/layouts/components/Homepage/HeroBody.tsx, src/styles/templates/components/hero.scss, src/templates/homepage/HeroSection/HeroButton.tsx, src/templates/homepage/HeroSection/HeroCenteredLayout.tsx, src/templates/homepage/HeroSection/HeroSection.tsx, src/templates/homepage/HeroSection/HeroSideLayout.tsx
We have a floating variant of the homepage with extra padding on side. This PR adds that in; this PR also fixes a erroneously placed button, where it should be placed _outside_ of the div to maintain same structure
1. use same components for floating homepage but add a `div` wrapper 
2. shift `HeroButton` out 
3. shift conditional to **not** be included in `div` with `className=mb8`
=> feat(homepage): add floating variant

src/constants/featureFlags.ts, src/layouts/EditHomepage/HomepagePreview.tsx, src/layouts/components/Homepage/HeroBody.tsx, src/templates/homepage/HeroSection/HeroSection.tsx
we want to gate our hero banner variant behind a flag for now so that users **cannot** toggle and anyhow change the variant.
1. add feature flag in
2. add default args to template (previously caller passed in default); for **preview**, there's already a default added last time (unseen cos no diff)
=> chore(hero): add feature flag for hero banner

.github/workflows/chromatic.yml
Path checking is done for both push and issue_comment currently, which is not ideal since if I do a `!run chromatic`, I really want Chromatic to run, regardless of whether there is a need to. We as humans need to take back control from the system.
- Restrict the path changed checking to only push events.
Minor fix, only testable after merge.
*None*
=> fix(chromatic): only do path checking on push

.github/pull_request_template.md
It is becoming harder for one eng to keep track of all the other feature flags that are avail. It is also well known a lot of production bugs in big tech companies are results for failed roll outs for experiments. (eg, amplify build times vs repo privatisation) 
Eng to manually tick off that their features are compat with the permutations of the features (or at least spend some time thinking intentionallu about it) 
- Details ...
=> feat(template): add ffs as a manual check-in

src/layouts/EditHomepage/EditHomepage.jsx
Closes IS-519.
**Features**:
- A new help overlay has been added for the new announcements block.
**AFTER**:
*None*
=> feat(announcements): add help overlay

src/styles/isomer-template/components/homepage/_announcements.scss, src/styles/isomer-template/theme/_breakpoints.scss, src/templates/homepage/AnnouncementsSection.tsx
The announcements preview on the frontend and the announcements component on the template has diverged.
- Synchronise the changes made to the template:
- Match padding and margin values to be exactly how it was done in Figma (using margins instead of paddings when Figma used them as such)
- Centre-align text, so that on text overflow, the text remains centred
*None*
=> chore(announcements): sync changes from template

src/layouts/EditHomepage/EditHomepage.jsx
This PR adds a help overlay for texts cards. It also adds a feature flag into the text cards component.
=> feat: add help overlay and add feature flag

src/hooks/useDrag.tsx, src/layouts/EditHomepage/EditHomepage.jsx, src/types/homepage.ts
Replaces behaviour in `useDrag` for homepage to allow for handling section subitems without changing the existing behaviour. This PR modifies the `switch/cases` to `if/else` instead to allow for types of the form `<subitem name>-<number>`.
=> chore: refactor homepage to if/else to preserve existing behaviour

src/layouts/EditHomepage/EditHomepage.jsx
when the entire announcemnt block close, the `announcemnetScrollRef` never reset. 
reset it when the entire announcemnt section is deleted
- Details ...
**BEFORE**:
**AFTER**:
https://github.com/isomerpages/isomercms-frontend/assets/42832651/7ba4eb3e-8ef3-4271-b990-1e9a8f1f2668
=> fix(announemnt): fix announcemnt bug

.env-example, src/constants/featureFlags.ts, src/hooks/settingsHooks/useGetSettings.ts, src/layouts/Settings/Settings.tsx, src/types/featureFlags.ts
Site privatisation is feature-flagged via env var now with just a boolean. We want to move this to growthbook and to allow site-level whitelist.
Closes IS-577
Moved to growthbook with new feature flag and json response of all the whitelisted sites for repo privatisation feature.
- Details ...
**Removed environment variables**:
- `REACT_APP_IS_SITE_PRIVATISATION_ACTIVE` : removed in favour of new feature flag on GB
=> IS-577: Move site privatisation to growth book

src/constants/featureFlags.ts, src/routing/RouteSelector.jsx, src/types/featureFlags.ts
This PR moves warning banner from an env var toggle to growthbook, to enable quicker rollout of banners without having to rebuild.
=> chore: move warning banner to growthbook

.env-example, src/constants/featureFlags.ts, src/hooks/useFeedbackDisclosure.ts, src/types/featureFlags.ts
This PR moves the toggle for nps form to growthbook.
=> chore: move nps form to growthbook

src/layouts/EditHomepage/EditHomepage.jsx
UI polish, currently weird that 
non empty text with empty url leads to error
but 
non empty url with empty test leads to NO error
quick validation
- Details ...
=> fix(announcements): add validation url

src/styles/isomer-template/theme/_text-styles.scss
`h1` has a mobile version for smaller screens; this was previously done as `h1-small` but it should have been automatically shifted to a smaller size.
replace `h1-small` with a media query so that it automatically resizes
=> refactor(text-styles): update to have mobile

src/templates/homepage/HeroSection/HeroCenteredLayout.tsx
Hero centered layout had no optional chaining for `dropdown` 
add `?`
=> fix(herocenteredlayout): make dropdown optional

package-lock.json, package.json, scripts/build.js, scripts/reset-e2e.js, scripts/run-e2e.js
Part of IS-446.
- Resetting e2e test repos now uses a new backend endpoint instead of calling GitHub API directly. This was done in https://github.com/isomerpages/isomercms-backend/pull/950.
**REMOVED dev dependencies**:
- `btoa`
=> fix(e2e): utlise new backend endpoint to reset e2e repos

.github/workflows/ci-e2e.yml, package.json, scripts/build.js
Part of IS-446.
**Features**:
- The e2e tests now run in parallel using GitHub Actions' job matrix strategy. This is split into 3 jobs:
- `run-email`: To run email login-specific tests on `e2e-email-test-repo`. This is defined to be `collaborators`, `comments`, `dashboard`, `notifications` and `reviewRequests` and will need to be manually updated when new test specs are created that are specific for email login functionality that requires the `e2e-email-test-repo`.
- `run`: To run the rest of the test specs (i.e excluding those above) on the GGS-whitelisted `e2e-test-repo`.
- `run-notggs`: To run the rest of the test specs (i.e excluding those above) on the not-GGS-whitelisted repo `e2e-notggs-test-repo`. Note that this will no longer exist once > 70% of our sites …
=> feat(e2e): run e2e tests in parallel and support notggs repo

src/layouts/components/ContactUs/GeneralInfoSection.tsx
The spacing used on the general information section does not match that on Figma.
**Bug Fixes**:
- The spacing is now fixed.
**BEFORE**:
**AFTER**:
*None*
=> chore(contactus): fix spacing of error message on general information section

src/styles/isomer-template.scss
The footer was changed on the template
- Changes to the template made in https://github.com/isomerpages/isomerpages-template/pull/327 are synced over to the CMS frontend.
No tests, there is no impact to the user since we do not show the footer styles on the CMS frontend.
*None*
=> chore(template): sync footer spacing changes from template

src/layouts/EditContactUs.jsx
Closes IS-471.
**Bug Fixes**:
- The location section of the contact us frontmatter is now optional, so an error toast is shown when the contact information section is empty.
- Corresponding backend change: https://github.com/isomerpages/isomercms-backend/pull/957
**BEFORE**:
**AFTER**:
*None*
=> fix(contactus): allow location section to be empty but not contact information

src/components/OverwriteChangesModal/OverwriteChangesModal.stories.tsx, src/components/OverwriteChangesModal/OverwriteChangesModal.tsx, src/components/OverwriteChangesModal/index.ts, src/layouts/EditPage.jsx, src/layouts/Settings/components/OverrideWarningModal.tsx
Part of ticket 629 (intentionally not linking since JIRA will think the task is done).
- The overwrite changes warning modal that used to be present in EditPage has now been abstracted out into its own component. This is to allow other editing pages to be able to use the same override modal.
*None*
=> refactor(editpage): abstract out overwrite changes warning modal

src/components/OverwriteChangesModal/OverwriteChangesModal.tsx, src/hooks/homepageHooks/useUpdateHomepageHook.ts, src/layouts/EditHomepage/EditHomepage.jsx, src/layouts/Settings/components/OverrideWarningModal.tsx
Closes IS-629.
**Features**:
- The homepage now has an override modal to override changes if a 409 Conflict is detected.
*None*
=> feat(homepage): allow user to override changes when there is a conflict

src/hooks/mediaHooks/useGetMultipleMediaHook.tsx
Image preview does not load newly uploaded images correctly.
**Bug Fixes**:
- Adjust query key to load media that were just uploaded.
*None*
=> fix(media): adjust query key to load image in preview on upload

src/utils/images.ts
Media sources with spaces do not get replaced and shows not found.
**Bug Fixes**:
- Media srcs with spaces now work
Test #1580 but with spaces in the file name and/or album name.
*None*
=> fix(media): support replacement of media src with spaces

src/layouts/EditNavBar.jsx
Some queries from `useQueries` get returned even though they are still loading, causing the `data` attribute to be undefined.
**Bug Fixes**:
- All the queries returned are checked to ensure that they are fully loaded before further processing is performed.
Test with #1592 and ensure that the navbar has a folder group.
*None*
=> fix(navbar): ensure all queries are loaded first

src/hooks/directoryHooks/useGetSecondLevelFoldersAndPages.ts, src/layouts/EditNavBar.jsx
Because `secondLevelData` is not part of the `useEffect` hook, it can lead to race conditions if `secondLevelData` is still loading.
**Bug Fixes**:
- Switch from using `useQueries` to a single query with a `Promise.all`, so that we can deterministically ensure that all Promises are completed before it gets returned.
*None*
=> fix(navbar): fix race condition when retrieving second level data

cypress/support/settings.ts
Previously, we only had 1 e2e test repo. now, we have 3, which results in the command not hitting the correct repo. this results in an await call that never happens, leading to cascading failures.
use env var
=> fix(settings): use env var for spec command

src/components/CollaboratorModal/components/MainSubmodal.tsx, src/routing/ApprovedReviewRedirect.tsx, src/types/collaborators.ts, src/utils/collaborators.ts, src/utils/index.ts, src/utils/siteLaunchUtils.ts
Closes IS-654.
**Features**:
- A new collaborator role `ISOMERADMIN` has been added to identify users in the IsomerAdmins table. This additional role allows Isomer admins to have access to sites and act as if they are an admin of that particular site. Review in conjunction with https://github.com/isomerpages/isomercms-backend/pull/982.
*None*
=> feat: allow Isomer admins to edit on email-login

cypress/e2e/collaborators.spec.ts
This PR removes a test which is no longer relevant after the change in behaviour for adding new collaborators to no longer check for an existing user.
=> chore: remove extra test

src/components/Header.jsx
The siteName param was given as an object to the `useGetStagingUrl` hook, which causing the "Open Staging" button to not work when editing pages.
**Bug Fixes**:
- The params input has been fixed and the "Open Staging" button works now.
*None*
=> fix(header): adjust siteName function params

src/hooks/pageHooks/useGetPageHook.jsx, src/hooks/pageHooks/useUpdatePageHook.jsx
The edit page does not invalidate the correct key for some reason.
**Bug Fixes**:
- The edit page query key has been adjusted to put the site name and file name in the query key directly instead of being nested inside the object. I'm not sure why objects do not work, [when the docs claim that they do](https://tanstack.com/query/v4/docs/react/guides/query-keys#query-keys-are-hashed-deterministically), might be an upstream bug.
*None*
=> fix(editpage): change query key from object to array

src/constants/featureFlags.ts, src/constants/localStorage.ts, src/hooks/homepageHooks/index.ts, src/hooks/homepageHooks/useFrontmatterSections.ts, src/layouts/EditHomepage/EditHomepage.jsx, src/layouts/EditHomepage/utils.ts, src/layouts/Sites.tsx, src/layouts/components/Homepage/HeroBody.tsx, src/layouts/components/Homepage/constants.ts, src/types/featureFlags.ts
We have no way of rolling back blocks at present, which means that we are unable to undo changes safely. 
Add a hook that sanitises the frontmatter if the given blocks are not inside the whitelist. This is done through: 
1. checking if the current blocks provided by frontmatter are permitted by our whitelist (and storing it inside `localStorage`) 
2. checking if existing blocks in `localStorage` are now permitted and merging with ^ 
3. presenting this back to the user. 
added **all** blocks to feature flag, not just new blocks. lets us rollback as required. also, `Hero` doesn't rollback the variants but the block as a whole :monkas: maybe not ideal but the alternative is quite abit of work and doesn't add that much value too
=> feat(blocks): rollback handler

src/components/HyperlinkModal.jsx, src/components/PageSettingsModal/PageSettingsModal.tsx, src/components/PageSettingsModal/ResourcePageSettingsModal.tsx, src/contexts/EditorModalContext.tsx, src/layouts/EditPage/EditPage.tsx, src/layouts/EditPage/EditPageLayout.tsx, src/layouts/components/Editor/components/LinkBubbleMenu.tsx, src/layouts/components/Editor/components/MenuBar.tsx, src/layouts/components/Editor/styles.scss, src/types/pages.ts
Existing flows for file insertion/link insertion make use of a modal. This has been changed to allow copy pasting, which might be confusing to the user. 
- For files, we insert a **default** text of `file` if **there is no text in the selection**. 
- For links, show the existing hyperlink modal on menu button click (existing flow of highlighting the text and pasting link still works as expected)
-  For the modal that appears after `change link` button is clicked (link bubble menu), if the user deletes their link, the link will be unset by default.
=> feat(editor): change some user flows to fit existing flows

src/layouts/Media/components/MediaDirectoryCard.tsx, src/layouts/ResourceRoom/components/CategoryCard.tsx, src/layouts/Workspace/components/Cards/FolderCard.tsx
Implement UI changes for album tile. Currently, our "edit" in the dropdown is just equivalent to clicking the tile and "settings" just does rename of the folder.
Closes IS-678
Took the liberty to update across images + files, resource room and workspace.
UI should look like this. For full design see Figma link on ticket IS-678
- Details ...
**BEFORE**:
**AFTER**:
=> IS-678: UI changes for album tile

src/components/pages/MarkdownEditor.jsx, src/constants/featureFlags.ts, src/layouts/EditPage/EditPageLayout.tsx, src/layouts/EditPage/FeatureFlaggedEditPage.tsx, src/layouts/EditPage/MarkdownEditPage.tsx, src/layouts/EditPage/TiptapEditPage.tsx, src/layouts/EditPage/index.tsx, src/layouts/EditPage/utils.ts, src/layouts/LegacyEditPage.jsx, src/services/PageService.jsx, src/types/featureFlags.ts
Our current new RTE has no feature flag. In addition, the new modals are not added. This PR adds them back.
1. Add feature flag
2. Shift stuff (the checks) out into utils
3. add checks into layout
4. reuse layout on legacy + new pages.
=> feat(ff): add feature flag for editpage

src/hooks/mediaHooks/useDeleteMultipleMediaHook.tsx
After deleting, the list of media files do not get refreshed.
**Bug Fixes**:
- Invalidate the `GET_ALL_MEDIA_FILES_KEY` query key as well.
*None*
=> fix(media): add additional query key to invalidate

src/routing/ProtectedRoute.tsx
Previously we didn't have a dep in protected route, which might have led to `siteName` not being in growthbook
Add to `useEffect`
=> fix(protected-route): add missing deps

src/layouts/screens/DeleteWarningScreen.jsx
Enhance current delete modal for images (also for files, resource categories and pages)
Closes IS-685
Enhance delete modal as per this UI
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> IS-685 enhance delete images

src/layouts/components/Editor/components/MenuBar.tsx
The menu bar was rendering twice, which required 2 clicks to active modals. 
Closes IS-742
Removed the `uuid`. This is because on state change (clicking etc), the uuid function fires again, which leads to a new key. This, in turn, causes react to re-render the component, leading to the first click being dropped.
=> fix(menubar): remove uuid

src/layouts/EditPage/TiptapEditPage.tsx
Editor width should be `45vw` instead of `50%`; changing it on `TiptapEditPage` first to avoid potential design regression on the markdown editor 
Closes IS-718
update props
=> refactor(tiptap-editor): update width

src/layouts/Login/components/OtpForm.tsx
When logging in via email, the OTP field does not gain auto focus, which requires the user to perform an additional click.
- The OTP input field now gains auto focus after the user presses submit for the email, reducing the need to click the OTP field again.
- Clicking on the form label also directs the user correctly to the OTP input field.
*None*
=> chore(login): automatically focus on input field

src/layouts/components/Editor/styles.scss
Currently, our editor height is shorter than what is shown. This leads to confusion when users click out of the editor (perhaps at whitespace at the bottom) but are unable to edit.
Closes IS-715
change `tiptap` height to `100%`
=> fix(editor): change inner prosemirror stuff to have 100% height

src/components/media/MediasSelectModal.jsx, src/services/DirectoryService/DirectoryService.ts, src/types/folders.ts
Our images modal in FE is broken when search is used due to pagination. 
Review this tgt with [ee](https://github.com/isomerpages/isomercms-backend/pull/1026) 
Also our sort by didnt work particaulry well due to casing, that has been modified as well
Screenshots 
[ ] Go into a repo with lots of images (at least > 15 since thats what we paginate by)
[ ] Search for any image that would be > 15th index when alphabeticaly ordered. (eg. seach for an image that start with z) 
[ ] ensure that you can see the image in the modal
=> fix(image): search pagination

src/utils/siteColorUtils.js
The preview does not show the headings properly in the site colours.
Fixes IS-567.
**Bug Fixes**:
- The site colours CSS rule is now properly injected in the site colour utilities. This rule is taken from the custom.scss files that every repo should be using: https://github.com/isomerpages/site-creation-base/blob/b7b29561760891bdfa5ba7f7d5fb78e9725d53a2/misc/custom.scss#L257-L272
**BEFORE**:
**AFTER**:
*None*
=> fix(preview): use site colours for headings in preview

src/components/Attachment/AttachmentDropzone.tsx, src/components/CreateMediaFolderModal/CreateMediaFolderModal.stories.tsx, src/components/CreateMediaFolderModal/CreateMediaFolderModal.tsx, src/components/CreateMediaFolderModal/index.ts, src/components/DeleteMediaModal/DeleteMediaModal.tsx, src/components/DirectorySettingsModal/DirectorySettingsSchema.jsx, src/components/ImagePreviewCard/ImagePreviewCard.tsx, src/components/MediaCreationModal/MediaCreationModal.tsx, src/components/MoveMediaModal/MoveMediaModal.tsx, src/hooks/directoryHooks/useCreateDirectoryAndMoveFilesHook.ts, src/hooks/moveHooks/useMoveMultipleMediaHook.tsx, src/layouts/Media/Media.tsx, src/layouts/Media/components/FilePreviewCard.tsx, src/types/media.ts, src/utils/media.ts
Closes IS-746.
**Features**:
- A new flow to create album with selected media has been introduced.
- The existing create album modal has also been enhanced.
**BEFORE**:
**AFTER**:
*None*
=> feat(media): allow create album with selected media

src/components/pages/MarkdownEditor.jsx, src/components/pages/editor.scss, src/styles/isomer-cms/pages/Editor.module.scss, src/styles/isomer-template.scss
Overflow on editor leads to the editor overflowing, which leads to a less than ideal experience for our users
1. Fix css styling for `pageEditorSidebar` to have a fixed height
2. shift editor styling to own file instead of residing in `isomertemplate.scss` -> this is to avoid obscuring as it's not a part of the preview per se. also we cannot use css modules cos this needs to target the raw class (`.CodeMirror`) and not the mangled version
- go to the old editor
- paste some content in until it overflows
- editor should be scrollable
=> fix(markdown): update styling to remove overflow

src/layouts/EditPage/TiptapEditPage.tsx, src/layouts/components/Editor/components/MenuBar.tsx, src/layouts/components/Editor/components/MenuItem.tsx
Previously, we were relying on the `title` prop to show the tooltip (this is HTML spec). However, this led to a significant delay before the tooltip showed.
Closes IS-743
Change to use chakra tooltip. Design system tooltip **does not work** (see [here](https://github.com/opengovsg/design-system/issues/546))
=> fix(editor): refactor to use `tooltip` 

src/components/ImagePreviewCard/ImagePreviewCard.tsx, src/components/media/MediaModal.jsx, src/components/media/MediasSelectModal.jsx, src/layouts/Media/components/FilePreviewCard.tsx, src/layouts/Media/components/MediaDirectoryCard.tsx
This PR modifies the existing image select modals (present in edit page and fields which involve selecting a media item, e.g. resource page creation and settings) to reuse the same media components present in the general media layout.
To support this, the specific components (`MediaDirectoryCard`, `ImagePreviewCard` and `FilePreviewCard`) have also been modified to allows variants which do not contain the checkbox/menu.
The file preview card has also been fixed to display a highlight border when selected/checked. (Resolves IS-773)
Before:
After:
=> Fix/is 689 reuse image/album tiles

src/layouts/components/Editor/components/MenuBar.tsx
had a lot of stuff we dont use, remove them 
NOTE: we should not remove the nodes from starter kit, cuz that means that every <code> will crash the editor 
Which actually suggests that compat with different html elements is a non-trivial tasks for pages that are already populated with HTML. I dont have an exhaustive list with me at the moment, will put it as part of QA.
=> feat(tiptap): rm redundant logos

src/components/MediaCreationModal/MediaCreationModal.tsx, src/components/media/MediaModal.jsx
Closes IS-763.
Closes IS-779.
**Bug Fixes**:
- The user is now brought back to the select media modal after uploading files.
- Any closure of the upload files modal also brings the user back to the select media modal.
*None*
=> fix(media): bring the user back to the select media modal screen after upload

src/components/EditorEmbedModal/EditorEmbedModal.tsx, src/constants/tiptap.ts, src/layouts/EditPage/EditPage.tsx, src/layouts/components/Editor/extensions/FormSG/FormSG.ts, src/layouts/components/Editor/extensions/FormSG/FormSGView.tsx, src/layouts/components/Editor/extensions/FormSG/index.ts, src/layouts/components/Editor/extensions/Iframe/Iframe.ts, src/layouts/components/Editor/extensions/index.ts
The FormSG embed does not use a proper Tiptap node to display, causing the attribution to be removed as part of the hacky workaround.
**Features**:
- The FormSG embed now uses a proper Tiptap node to represent the content.
*None*
=> feat(rte): use proper node for FormSG embed

src/layouts/EditPage/MarkdownEditPage.tsx, src/layouts/LegacyEditPage.jsx, src/styles/isomer-cms/pages/Editor.module.scss
make it symmetry
non-tip tap enabled
tip-tap enabled but they choose not to have it
=> IS-780 fix(height): fix editor + preview heights

src/layouts/components/Editor/components/LinkBubbleMenu.tsx
Update link modal not updating + does not have proper defaults
Use `.extendMarkRange("link")` instead, this is a direct copy paste from their [demo](https://tiptap.dev/api/marks/link). 
For default values, re-update every time the modal is opened. 
https://github.com/isomerpages/isomercms-frontend/assets/42832651/5a80f0fe-d63a-46a6-a792-8cf5c6c1ed3c
=> fix(updateLinkModal): update link + proper default

src/components/EditorEmbedModal/EditorEmbedModal.tsx, src/layouts/EditPage/EditPage.tsx, src/layouts/components/Editor/extensions/Instagram/Instagram.ts, src/layouts/components/Editor/extensions/Instagram/InstagramView.tsx, src/layouts/components/Editor/extensions/Instagram/index.ts, src/layouts/components/Editor/extensions/index.ts
The Instagram embed is done in a hacky manner whereby we replace it with our own custom iframe, which we cannot guarantee to support.
**Features**:
- The Instagram embed is now a full Tiptap Node.
*None*
=> feat(tiptap): add Instagram embed proper node handler

src/utils/siteColorUtils.js
Resolves IS-762. This PR fixes an issue where colours were not being updated properly on the preview in 2 cases:
- User navigates to one site, loads a page, then visits a different site and loads a page - still uses original colour scheme
- User loads a page, then navigates to settings and changes colours - upon returning to any page the colours are still old
This issue was caused because any changes only added on a new stylesheet, but this had lower priority than the original stylesheet, meaning that colours would stay the same until refreshed.
To fix this, the custom inserted stylesheet is explicitly deleted at the start of the insertion if it exists prior - this allows the site colours to remain updated.
Tests:
=> Fix: colours stylesheet

src/components/Header/ContactModal/ContactVerificationModal.tsx, src/layouts/Login/LoginPage.tsx, src/layouts/ReviewRequest/components/Comments/SendCommentForm.tsx
Resolves IS-777.
This PR fixes an issue introduced by a change to the behaviour of `react-hook-form` - it no longer returns `isSubmitting` to false when an error is thrown (see [link](https://github.com/orgs/react-hook-form/discussions/9879)). As we make use of react-query, which handles promises rejection (and requires promises to throw on failure), we need to add an additional catch statement for each of the places where we make use of `isSubmitting` to determine whether the submit button is disabled. Note that error handling is already tackled in each of these places, hence the catch without doing anything else - this is purely to ensure that react-hook-form returns to the correct state.
Affected components:
=> fix: submitting state for react-hook-form

src/components/CreateMediaFolderModal/CreateMediaFolderModal.tsx, src/layouts/Media/Media.tsx
Users are not able to create folders when the folder is empty.
**Bug Fixes**:
- The link to create a new folder when inside an empty folder is now fixed and correctly points to opening the create media folder modal.
- The media folder modal has also been fixed to not show the select images/files portion if there are no files to begin with.
**BEFORE**:
**AFTER**:
*None*
=> fix(media): allow creating folders in empty folder

src/components/CreateMediaFolderModal/CreateMediaFolderModal.tsx
The button remains disabled even when adding content, when the folder does not have any images/files.
**Bug Fixes**:
- Fix the logic to also check if there are even images/files for users to select from.
*None*
=> fix(media): fix logic for disabling button in create media folder modal

src/components/EditorCardsDrawer/EditorCardsDrawer.tsx, src/components/EditorCardsDrawer/index.ts, src/components/EditorDrawer/EditorDrawer.tsx, src/components/EditorDrawer/index.ts, src/components/MiniDrawer/MiniDrawer.tsx, src/components/MiniDrawer/index.ts, src/contexts/EditorDrawerContext.tsx, src/layouts/EditPage/EditPage.tsx, src/layouts/EditPage/EditPageLayout.tsx, src/layouts/EditPage/TiptapEditPage.tsx, src/layouts/components/Editor/components/CardsBubbleMenu.tsx, src/layouts/components/Editor/extensions/TrailingNode.ts, src/types/editPage.ts
Card grid block
**Features**:
- Adds a new mini drawer component to support editing within a form outside of the Tiptap editor.
**Note: This PR is part of a stack of changes, refer to #1707 for the complete write-up:**
1. #1701 
2. #1704 **<--- YOU ARE HERE**
3. #1705 
4. #1706
5. #1707
*None*
=> feat(cards): introduce drawer to support sub-editing

src/layouts/EditPage/MarkdownEditPage.tsx
Some styles don't work as expected - due to the width of the preview being set to a fixed width and the editor having a max width, there might be missing space on the right hand side when the viewport is extremely big.
1. set min width of the preview (so it will always take that amount of space) 
2. set editor to `w=100%`
=> fix(markdowneditpage): fix styling on big screens

src/constants/featureFlags.ts, src/layouts/components/Editor/components/MenuBar.tsx, src/types/featureFlags.ts
The complex blocks are blocking the release of the other fixes for the RTE.
**Features**:
- The complex blocks are now feature-flagged and hidden by default.
**Bug fixes**:
- Fixed left padding so that the second line looks aligned to the first when the menu bar overflows.
*None*
=> feat(editor): feature flag complex blocks

src/layouts/components/Editor/components/ImageBubbleMenu/ImageBubbleMenu.tsx, src/layouts/components/Editor/extensions/FormSG/FormSGView.tsx, src/layouts/components/Editor/extensions/Iframe/IframeView.tsx, src/layouts/components/Editor/extensions/Instagram/InstagramView.tsx
1. if embed source too long, it overflows 
2. image resizing doesn't work _yet_
1. add `maxW` prop so it knows when overflow.
2. comment out image resizing for now 
**before**
**after**
=> fix(embed-views): add a max width

src/layouts/components/Editor/components/ImageBubbleMenu/ImageBubbleMenu.tsx, src/layouts/components/Editor/components/ImageBubbleMenu/ResizeImagePopover.tsx, src/layouts/components/Editor/extensions/Image/Image.ts
Closes [IS-712]
The existing (commented out) image resizing feature on the new RTE has 2 major issues:
1. When user enters a new percentage value and clicks save in the form, it creates an additional resized image node instead of resizing the original image node 
2. To make the feature work, the `width` property in `.content img` in the template scss file has to be removed, which affects the old non-RTE page and is not backward compatible 
1. To avoid duplicating image node, `updateAttributes` is called on the image editor instead of `setImage`, which will update the attribute of the selected image node. 
2. To avoid removing the `width` property in `.content img` css, a locally scoped `style` tag is used to update the `width` of each image node which overrides the pre-defined css …
=> IS-712 Fixed image resizing issue in RTE

src/layouts/EditPage/MarkdownEditPage.tsx, src/layouts/LegacyEditPage.jsx
Previously, we set both editpages to a fixed `62.5rem` width. This appears ok on big screens (1920+) but squashes the editor on smaller screens. 
- set editor to `45vw` 
- let the preview fill teh remaining space.
- this was done using the `flex` [syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/flex); concretely, what this means is that we always use `45vw` as the basis for the editor and let any remaining space go to the preview. (see videos below)
https://github.com/isomerpages/isomercms-frontend/assets/44049504/fca9d7c5-eda6-46bc-8824-0c7dbc57202d
=> refactor(legacy/markdown-editpage): update width

src/layouts/components/Editor/components/ImageBubbleMenu/ImageAltTextPopover.tsx, src/layouts/components/Editor/components/ImageBubbleMenu/ImageHyperlinkPopover.tsx, src/layouts/components/Editor/extensions/Image/Image.ts
Closes IS-807
The Hyperlink and AltText options of the image node in our new RTE has user-impacting bugs. Everytime users add or change the values through the handler, the RTE creates a duplicated image and applies the changes to the newly duplicated image, resulting in user confusion and very bad user experience. 
The bug resides in the `setImage` method of the `image` extension. The logic of selecting the current node and updating its attributes is incorrect. This PR fixes the logic therefore fixes the bug for both options. 
- Details ...
**Bug Fixes**:
- The image duplicating issue is fixed for both `Hyperlink` and `AltText` options of image node in the new RTE
**BEFORE**:
https://github.com/isomerpages/isomercms-frontend/assets/14878879/4a7c8213-f157-46df-bb13-c930 …
=> IS-807 Fixed duplicating issue when setting hyperlink & alt text for image in RTE

src/layouts/components/Editor/components/MenuItem.tsx, src/layouts/components/Editor/components/TableBubbleMenu.tsx, src/layouts/components/Editor/extensions/Table/styles.scss
Closes [IS-734](https://isomeropengov.atlassian.net/browse/IS-734?atlOrigin=eyJpIjoiYTFiN2I4NTg2YWI0NDJmODg3YjIzZTFmOGRiMzVhYzIiLCJwIjoiaiJ9)
Closes [IS-810](https://isomeropengov.atlassian.net/browse/IS-810?atlOrigin=eyJpIjoiNTM2YzM0MzNkOWFkNDQ1M2EzZWY3MTkzYTdkN2FiZDkiLCJwIjoiaiJ9)
Closes [IS-811](https://isomeropengov.atlassian.net/browse/IS-811?atlOrigin=eyJpIjoiZWQ1ODQwZTgxYTM3NDlmZWJjYWVmNzM3YThjOTI2MWQiLCJwIjoiaiJ9)
- IS-734: the table component in our new RTE does not have a delete icon in the floating menu, and it's quite hard for users to delete the table.
- IS-810: Table block label is visibly larger than the labels of other nodes/components (image, cards, etc.), the font size is inconsistent 
- IS-811: Text in the first cell of table is overlapping with the table label when the …
=> IS-734 Add delete icon to table control and other minor UI fixes

src/layouts/EditHomepage/EditHomepage.jsx
Despite a successful save, navigating back or away shows the modal incorrectly
Closes IS-824
Set original frontmatter to the latest one so that comparison succeeds after successful update of homepage
- Perform a edit on homepage
- Click back
- Unsaved changes modal (as in above ss) should *not* appear
=> fix: warning modals

src/utils/validators.js
Some agencies was to show upcoming events etc in announcements. but current validation disallows future dates
Closes IS-842
Removed validation on future dates
- Details ...
- Go to staging site
- Click on Homepage
- Add announcement block
- Put a future date
- Ensure there are no validation errors
- Ensure you're able to save page properly
=> fix: remove date validation in announcements

src/theme/components/Rating.ts, src/theme/components/index.ts
Current NPS modal has no styles applied. Seems like we accidentally deleted it.
Closes IS-843
Reinstate styles from https://github.com/isomerpages/isomercms-frontend/pull/1370/files#diff-96215533909ccc4efb20eaff62065495f61ce94f83d218f11b7d28882f8b5544
- Details ...
- Enable NPS modal for staging on GB
- Go to a staging site
- Navigate to page and then press back
- Ensure NPS modal pops up with expected styles (e.g. is given below)
=> fix: missing style for nps modal

src/services/DirectoryService/DirectoryService.ts
current limit value of 1000 affects ggs repos as all files are being fetched. changed it to be 15. For github repos, they are not affected as we do not pass the limit value to the read call
src/services/db/RepoService.ts
```
const contents = await super.readDirectory(sessionData, {
directoryName,
})
```
=> fix: limit for get media

src/hooks/mediaHooks/useDeleteMultipleMediaHook.tsx, src/services/MediaService.jsx
The mass deletion of media files often encounters the repo lock, which causes only half of the media files to be deleted.
**Bug Fixes**:
- Make use of the new backend endpoint to bulk delete all the media files, so that the repo lock is only performed once. This will also allow the deletes to happen much quicker.
> [!WARNING]
> The backend needs to be fully deployed first.
> Backend PR: https://github.com/isomerpages/isomercms-backend/pull/1065
=> fix(media): enhance bulk delete for media files

src/components/Header.jsx
On normal pages, the staging build indicator overlaps the page title if the title is too long.
Done as a part of Design team learning thanks @seaerchin for demoing the solution and explaining concepts! 🙇 
**BEFORE**:
**AFTER**:
1. Open / create a normal page with a long title (100 chars)
2. Check that status indicator doesn't overlap page title (title should truncate)
3. Change folder name to something long (30 chars)
4. Check that no elements on header overlap each other
=> fix(styles): fix overlapping page title issue

src/hooks/settingsHooks/useUpdateSettings.ts
This PR resets the staging url when a quickied site is converted to private (and vice-versa). To be reviewed in conjunction with PR [#1094](https://github.com/isomerpages/isomercms-backend/pull/1094) on the backend repo.
Tests:
- Privatise a quickied site
- Staging url should change from `staging-lite` to `staging`
- Unprivatise a quickied site
- Staging url should change from `staging` to `staging-lite`
=> chore: reset staging url when privatising site

package-lock.json, package.json, src/components/Attachment/Attachment.tsx, src/components/MediaCreationModal/MediaCreationModal.tsx
The react-dropzone library is having issues on GSIB, causing users to be unable to upload media.
**Bug Fixes**:
- Follow OGP's design system's decision to downgrade `react-dropzone` while a longer-term fix is being worked on.
- Also prevent JFIF files from being uploaded as we currently do not support rendering it within our CMS.
*None*
=> fix(deps): downgrade react-dropzone to fix media uploading on GSIB

src/layouts/components/Editor/extensions/Image/Image.ts
The image node is not correctly parsed by Tiptap when it contains a link and it is the first node in the page.
**Bug Fixes**:
- Make `parseHTML` parse the parent `<a>` tag directly instead of the `<img>` tag.
- I have no idea why, it just seems to work
*None*
=> fix(tiptap): correctly parse linked image node if it is first

src/components/media/MediasSelectModal.jsx
This PR fixes a bug where the breadcrumb for images when inserting it via a field (e.g. on the settings page) was not working.
Tests
=> fix: mediasselectmodal breadcrumb

src/layouts/components/Editor/components/LinkBubbleMenu.tsx
This PR fixes an issue where attempting to modify a link would not work if no `link` attribute exists in the editor.
=> chore: fix broken edit link button

src/components/EditorCardsDrawer/EditorCardItem.tsx, src/components/EditorCardsDrawer/EditorCardsDrawer.tsx
Users have been requesting that the card block do not need to contain a link. Let's make their wishes come true.
**Features**:
- Updated the validation schema for the card grid block to make links optional, unless a link URL has been provided.
- If the link URL is not present, but the link text is provided, it is still treated as a card without a link and the link text does not appear on the card
- Made the validation happen on blur, so that the error message can appear to prompt the user to add the link text as soon as they have added the link URL.
**BEFORE**:
**AFTER**:
*None*
=> feat(cards): make the card link optional

public/index.html, public/manifest.json
=> fix: update manifest

src/layouts/EditPage/utils.ts
our csp headers are too permissive for a wholistic block of allowed lists. 
while we should be limiting csp headers, a quick fix here is to limit the allowed src. 
This is a breaking change for our users who have been using the `script` tag, to ease in this change, have looked at all the script tags that our agency users have currently been using in their md files, and whitelisted them to achieve parity 
- Moving forward, ops would need to inform eng if any agency would like to use a script tag with a different source. this change already breaks some agencies code, will be following up with ops to see if they are willing to change this on their end. 
https://github.com/isomerpages/isomercms-frontend/assets/42832651/0400a94f-8439-40ef-81dc-262f19418144
```
Allowed …
```
=> fix(dompurify): further limit src

src/components/CollaboratorModal/components/MainSubmodal.tsx, src/hooks/collaboratorHooks/useAddCollaboratorHook.ts, src/types/collaborators.ts
It is not possible to add multiple collaborators consecutively, due to an issue with the way the `useEffect` hook is being called.
**Bug Fixes**:
- Removed the need for a `useEffect` hook by handling the finished states via react-query directly.
*None*
=> fix: allow adding multiple collaborators consecutively

src/layouts/Login/LoginPage.tsx
github login is the default tab option and most users are logging in via email
@shazlithebestie's request
swap order of logins
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
- verify that on login screen, the email login option is displayed first
=> swap order of github and email login

package-lock.json, package.json
On a fresh install, when starting the frontend locally with `npm run dev`, the following warning message is displayed:
```text
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
```
Follow instructions …
=> chore: explicitlyi add @babel/plugin-proposal-private-property-in-object to dev dependencies

src/layouts/screens/MediaSettingsScreen.jsx
The use of the decodedParams causes the call to `useListMediaFolderFiles` to be incorrect.
**Bug Fixes**:
- Use the encoded params instead. There is no need to use the decoded version here.
This fix needs to go in before backend.
=> fix(media): use encoded params for mediaDirectoryName

src/components/MediaSettingsModal/MediaSettingsSchema.jsx, src/hooks/mediaHooks/useCreateMultipleMedia.ts
currently files that start with _ are ignored. this means that in the final output, the site does not have the broken link.
this issue is quite existent in our sites (eg. https://www.cdc.gov.sg/our-programmes/gallery/2021/) 
when i did a string search, this lead to quite a number of sites with these types of images. this is not ideal, and as such this edge case will be coded out as part of the link checker for user to fix
Tests 
https://github.com/isomerpages/isomercms-frontend/assets/42832651/1ce91503-04b0-442e-8fef-10ae99e3129c
=> fix(media): should not have files that begin with underscore

src/templates/contact-us/ContactsSection.jsx, src/templates/contact-us/FeedbackSection.jsx, src/templates/contact-us/LocationsSection.jsx, src/templates/utils/sanitiseTemplateUrl.ts
The sanitize-url library does filters HTML entities, but it does not do so recursively. By nesting HTML entities, it is possible to create a URL which specifies the JavaScript protocol handler.
Closes GTA-24-006
Handroll a quick url constructor and check that the protocols are adhered to. 
- Details ...
=> fix(sanitiseUrl): fix limitations with library

src/layouts/LinkReport/LinksReport.tsx
currently we only have designs for broken links and not duplicate permalinks. 
add a less confusing state when the site only has duplicate permalinks. note that design is currently working on the iterations for duplicate permalinks, this is just a temp measure
**BEFORE**:
**AFTER**:
=> fix(no broken link): not reporting duplicate permalink

src/App.jsx
currently our backend trace isn't tied to our frontend RUM replay. this PR adds an allow list of backend urls, which will then allow DD to tie the traces to the specific rum session. 
- add `allowedTracingUrls` - see [here](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum)
- we can add in regex, functions or strings.
- strings match by initial section, so any url that starts with the given string will be matched. in our case, we use the env vrs `REACT_APP_BACKEND_URL`
=> feat(app): add link between traces + rum

src/utils/siteColorUtils.js
Text colors are the same for preview + staging sites
is-Secondary change is abit scary, after doing a string search on `.is-secondary` noted that this is used for
`.bp-button`
`.bp-sec`
`input`
`textarea`
`select`
`file`
`help`
`bp-notification`
`navbar`
`bp-hero`
nav bar + incols was ok
the search bar in the staging site looked alright + the files not used in blueprint.scss
For reference, in `blueprint.scss` has the following rules:
=> fix(scss): importing of styles

src/layouts/components/Editor/components/BlockWrapper/BlockWrapper.tsx, src/layouts/components/Editor/components/MenuBar.tsx, src/layouts/components/Editor/extensions/Details/IsomerDetailGroup.ts, src/layouts/components/Editor/extensions/Details/IsomerDetailGroupView.tsx, src/layouts/components/Editor/extensions/Details/IsomerDetails.ts, src/layouts/components/Editor/styles.scss, src/styles/isomer-cms/pages/Editor.module.scss
This PR attempts to fix the functional issues wrt to Accordions. 
Will leave paddings as separate since those will be easier to fix + don't really need much context to be worked on. 
Fix bunch of stuff [here](https://www.notion.so/opengov/Accordion-1de9bd79bfa540daacfdc5b703a80b00?pvs=4)
To test template stuff, need to make changes to [kishore-test](https://staging-cms.isomer.gov.sg/sites/kishore-test/editPage/accordion%20page.md)
Corresponding template pr: https://github.com/isomerpages/isomerpages-template/pull/361 (doesnt block this pr since complex blocks are behind feature flag anyway)
deprior padding related fix as design is not 100% sure about it yet + padding are easier to fix so no biggie
The approach for this PR would look weird considering the buttons are not bubble-menued. 
I …
=> fix p1 accordion issues

src/routing/RouteSelector.jsx
Currently, our frontend is vulnerable to path traversal attacks due to non-sanitisation of path parameters. 
Validate site name according to teh regex in the picture below. sanitization is **not** done for other stuff like resource room name because **these allow spaces in the name.**
Attempting to use `%20` in the regex will lead to erroneous validation (as seen in the ss). We also cannot allow `%` because this will lead to allowing url encoded characters (`%5c`).
=> fix(path-traversal): add regex to prevent path traversal attack

package-lock.json
Deps upgrading got issue halfway, re-syncing the package-lock.json.
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> deps: fix package-lock.json

package-lock.json
prosemirror has potential legal issues, see [here](https://opengovproducts.slack.com/archives/CK9GGK6EP/p1709632812521449)
bump version to `2.0.8`
=> build(package-lock): bump pm to 2.0.8 to avoid legal

src/layouts/components/Editor/components/BlockWrapper/BlockWrapper.tsx, src/layouts/components/Editor/extensions/Details/IsomerDetailGroupView.tsx, src/layouts/components/Editor/extensions/Details/IsomerDetails.ts, src/layouts/components/Editor/styles.scss, src/styles/isomer-cms/elements/base.scss, src/styles/isomer-cms/pages/Editor.module.scss
Design review for accordions, addressing changes [here](https://www.notion.so/opengov/Accordion-design-QA-7a07a952d7514f6989e8d04f61c1fac8?pvs=4).
Fix styling issues
=> fix(accordion): styles

src/components/PageSettingsModal/PageSettingsModal.tsx
We have quite a number of duplicate permalinks
this does not fix the problem completely, but it does allow for some sort of preventive measure to prevents accidental dups. 
we are not sure if of the number of agencies that use dup permalinks for the sake of playground, and it would be hard to enforce this until we have the functionality for playground out. more context [here](https://opengovproducts.slack.com/archives/CK68JNFHR/p1710317487152189)
sane default when creating a page.
- Details ...
follow video
https://github.com/isomerpages/isomercms-frontend/assets/42832651/3c3657dc-b9a1-4a40-9e49-07d71c32fd0a
=> fix(permalinks): default permalink for create

src/__tests__/RouteSelector.spec.jsx, src/layouts/Media/Media.tsx, src/layouts/ResourceRoom/ResourceRoom.tsx, src/routing/ProtectedRoute.tsx, src/routing/ProtectedRouteWithProps.tsx, src/routing/RouteSelector.jsx, src/routing/types.ts
Some of our routes don't have validation - this leads to security vulnerabilities where path traversal attacks can be done. 
Validate routes based on teh following criteria (observed behaviour): 
1. top level sites/resource categories/resource rooms will **not** have special characters; spaces will get converted to `-` in the url so it's ok if we validate alphanumeric + `-`. do note that **non-ascii** characters (chi/tamil) might have issues...
2. for filenames, we have the extension + we allow non-ascii characters (chi/tamil) so we will only check for special characters (inclusive of `.`) 
3. for media folders, we allow `/` (encoded) so we have to split and validate each one separately .___.
**NOTE:** refer to this [doc](https://docs.google.com/document/d/1_ouaNW3S3grk_ROjU7pHiskqzgULMEsx …
=> chore(validation): add validation for all routes

src/__tests__/RouteSelector.spec.jsx, src/layouts/ResourceRoom/ResourceRoom.tsx, src/routing/RouteSelector.jsx, src/utils/validators.js
merged previous PR too early, had a commit that was unpushed to upstream that removes extra comments and fixes a typo.
1. fix typo
2. remove extra comment
3. validate on `terms-of-use` 
4. use decoded params instead
=> fix(routeselector/resourceroom): remove accidental comments + fix typo

src/components/PageSettingsModal/PageSettingsModal.tsx, src/components/PageSettingsModal/ResourcePageSettingsModal.tsx, src/utils/permalink.ts
same as #1843 but for resource pages 
follow video
https://github.com/isomerpages/isomercms-frontend/assets/42832651/f545f927-90ba-4daf-a555-62f5b1a834f7
=> fix(resourceModal): sane default permalink

.github/mergify.yml
package updates are not automated and we have to look through even minor ones. minor updates should be approved + merged automatically
update dependabot config to merge minor packages automatically. we auto-merge snyk cos is security issue (open to also changing this to minor)
=> chore(mergify): enhance mergify

src/constants/datadog.ts
No frustration signal tracking in dd meant that we weren't getting important dd points
Closes [ISOM-1309]
Add frustration signal trackign in + remove `as const` cast. the cast had to be removed as the library type doesn't allow readonly assignment to a mutable property...
=> chore: add frustration signal tracking

src/utils/validators.js
It appears that Telegram invite links to private groups are created in the format `t.me/+...`, which does not match the existing regex we have.
**Features**:
- Enhance the Telegram URL regex to allow for an optional `+` at the start of the path.
**BEFORE**:
**AFTER**:
_None_
=> feat: enhance Telegram URL regex

src/layouts/EditPage/EditPage.tsx
Current referrer policy for external links does not allow the receiving site to have any analytics of their site traffic.
Update referrer policy from "noreferrer" to "strict-origin-when-cross-origin"
- Details ...
=> update referrer policy for hyperlinks

src/components/ViewStagingSiteModal/ViewStagingSiteModal.tsx, src/hooks/useStagingLink.ts, src/layouts/SiteDashboard/SiteDashboard.tsx
1. gsib access to staging site fails as gsib uses a security scan which. leasd to too many redirects
1. use `menlosecurity` and prepend if gsib is detected
=> fix: use menlo security for gsib

.github/workflows/playwright.yml
The `actions/upload-artifact@v3` action is deprecated and will no longer be working soon.
- Upgrade `actions/upload-artifact` from v3 to v4.
- Migration notes: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
- Main difference is that we need to provide a unique name for the artifact for each job run, which we handle using the `github.run_number`
=> chore: upgrade actions/upload-artifact to v4

package-lock.json, package.json, src/App.jsx, src/layouts/Workspace/Workspace.stories.tsx, src/services/ApiService.ts
We need to upgrade axios to 1.8.3.
Reference: https://opengovproducts.slack.com/archives/CK9GGK6EP/p1741763549869339
**Features**:
- Upgrade axios to 1.8.3.
=> fix: upgrade axios to 1.8.3
