src/layouts/EditImage.jsx
src/layouts/Images.jsx

Images are now shown as images and not as base64 decoded text
Images can be uploaded!

improve image page

---

src/components/editor/Homepage.jsx
src/layouts/EditHomepage.jsx
src/layouts/EditImage.jsx
src/styles/isomer-template.scss
src/templates/homepage/HeroSection.jsx

This PR completes the basic version of the EditHomepage function. When this PR is merged in, users will be able to edit/create:
- the Hero section
- the Infobar section
- the Resources section.
Feature:
- Users can switch between the Hero Dropdown or Hero button + key highlights: https://github.com/isomerpages/isomercms-frontend/issues/10
Bug fix:
- Users can add key highlights if there were none to begin with: https://github.com/isomerpages/isomercms-frontend/issues/9

Feature: Homepage continued

---

package-lock.json
package.json
src/components/editor/Homepage.jsx
src/layouts/EditHomepage.jsx

This PR addresses issue https://github.com/isomerpages/isomercms-frontend/issues/21. 
Users can now drag and drop all non-hero homepage sections to reorder them in the homepage.
The PR uses the [React Beautiful DnD library](https://github.com/atlassian/react-beautiful-dnd) by Atlassian.

Feat: Add drag-drop functionality to homepage sections

---

package-lock.json
package.json
src/layouts/EditCollectionPage.jsx
src/layouts/EditPage.jsx
src/utils.js

**Overview**
This PR introduces a function in `src/utils.js` that modifies the `src` attributes of internal links so that images on the right display pane of `EditPage` and `EditCollectionPage` are rendered.

Feature: Display images in EditPage and EditCollectionPage

---

src/components/tree/EditTree.jsx

Corrected a typo when receiving variable from backend

[bug fix] Correct typo in response attribute 

---

.vscode/launch.json
src/components/Header.jsx
src/layouts/Sites.jsx
src/styles/isomer-cms/pages/Sites.module.scss

This PR will add styling to the Sites page, including creating a card for each site rendered
Use the `fix-site-endpoint` on the backend

[Styling] Style Sites page

---

src/components/Header.jsx
src/layouts/EditPage.jsx
src/layouts/EditResourcePage.jsx

This PR allows us to pass in the following props: `title`, `backButtonText`, and `backButtonUrl` from each page so that we can make the header dynamic.

feat: make header dynamic

---

src/App.jsx
src/layouts/Menus.jsx

This PR adds the Menus page that connects to the Main Menu and Footer editing pages (https://github.com/isomerpages/isomercms-frontend/pull/65).

feat: add Menus page

---

src/layouts/EditCollectionPage.jsx
src/styles/isomer-cms/elements/variable.scss
src/styles/isomer-cms/pages/Editor.module.scss
src/styles/isomer-template.scss
src/templates/LeftNavPage.jsx
src/templates/SimplePage.jsx
src/templates/pageComponents/LeftNav.jsx

This PR tidies up the CSS for EditPage and EditCollectionPage so that it looks more presentable and less zoomed in.

style: zoom out the display for EditPage and EditCollectionPage

---

src/App.jsx
src/components/NavigationPreview.jsx
src/components/utils/tree-utils.jsx
src/layouts/EditNav.jsx
src/layouts/Menus.jsx

This is meant to add on to the existing PR #65.
This PR does the following:
1) Include the route to edit the navigation menu
2) Fix bugs regarding the rendering
3) Improve rules on the drag and drop behaviour
This PR will also fix issue #58

feat: include route to edit main menu

---

src/components/CollectionPageSettingsModal.jsx
src/components/PageSettingsModal.jsx
src/components/ResourceSettingsModal.jsx
src/components/Sidebar.jsx
src/layouts/EditCollectionPage.jsx
src/layouts/EditHomepage.jsx
src/layouts/EditPage.jsx
src/layouts/EditResourcePage.jsx
src/layouts/Files.jsx
src/layouts/Images.jsx
src/layouts/Pages.jsx
src/layouts/Resources.jsx
src/templates/LeftNavPage.jsx
src/templates/SimplePage.jsx
src/templates/pageComponents/Breadcrumb.jsx

This reverts commit 47d25c06424655ba71a45fcded20f592b086c1f2.

Revert "fix: refresh form only after all API calls finish (#72)"

---

src/components/CollectionPageSettingsModal.jsx
src/components/PageSettingsModal.jsx
src/components/ResourceSettingsModal.jsx
src/components/Sidebar.jsx
src/layouts/EditCollectionPage.jsx
src/layouts/EditHomepage.jsx
src/layouts/EditPage.jsx
src/layouts/EditResourcePage.jsx
src/layouts/Files.jsx
src/layouts/Images.jsx
src/layouts/Pages.jsx
src/layouts/Resources.jsx
src/templates/LeftNavPage.jsx
src/templates/SimplePage.jsx
src/templates/pageComponents/Breadcrumb.jsx

Reverts isomerpages/isomercms-frontend#84

Revert "Revert "fix: refresh form only after all API calls finish (#72)""

---

src/components/tree/EditTree.jsx
src/layouts/Media.jsx
src/layouts/Pages.jsx
src/layouts/Resources.jsx
src/templates/LeftNavPage.jsx

Self explanatory - made a typo while resolving a merge conflict on the GitHub UI in line 152 of the Pages file.

fix: typo in Pages and lint files

---

src/components/homepage/HeroButton.jsx
src/templates/homepage/HeroSection.jsx
src/utils/validators.js

Currently, the user of the HLB site cannot save their EditHomepage changes because they don't have a hero button.
The temporary fix for the user test is to disable the validation for the hero button and make it optional.

fix: make Hero button optional

---

src/components/homepage/InfopicSection.jsx
src/components/homepage/NewSectionCreator.jsx
src/layouts/EditHomepage.jsx
src/templates/homepage/InfopicLeftSection.jsx
src/templates/homepage/InfopicRightSection.jsx

This PR addresses https://github.com/isomerpages/isomercms-frontend/issues/11 by adding the ability to add/modify/remove infopic sections in the homepage.

feat: add homepage infopic section

---

package-lock.json
package.json

This PR makes the repo commitizen-friendly so that we can use the `git cz` command line tool for commits.
For more information, refer to this page: https://github.com/commitizen/cz-cli#making-your-repo-commitizen-friendly

[feat] make repo commitizen-friendly

---

src/layouts/Menus.jsx

This PR removes the Footer button for now until we build the EditFooter page.

feat: remove Footer button

---

src/layouts/Resources.jsx

This PR moves the create new resource button up to the top of the page

feat: display create new resource button up front

---

src/components/Header.jsx

This PR adds the logout feature to the frontend - it should be reviewed alongside https://github.com/isomerpages/isomercms-backend/pull/52

feat: logout button

---

src/layouts/Home.jsx
src/styles/isomer-cms/Elements.module.scss
src/styles/isomer-cms/elements/buttons.scss
src/styles/isomer-cms/elements/login.scss
src/styles/isomer-cms/elements/variable.scss

This PR makes the login page more aesthetically appealing.

style: login page

---

src/styles/isomer-cms/elements/variable.scss
src/styles/isomer-cms/pages/Content.module.scss

This PR fixes the line height issue in the Resource Card in the Resources view.
**Before**
**After**

style: line height for resource card

---

src/components/FolderCard.jsx

This PR introduces a deliberate error to test our Sentry integration in a staging environment

test: throw error to test Sentry integration

---

src/components/FolderCard.jsx

Reverts isomerpages/isomercms-frontend#264 since tests were completed

Revert "test: throw error to test Sentry integration"

---

src/layouts/Settings.jsx

**Note 1:** This PR is built on top of PR #285 - please review that first
**Note 2:** This PR is to be reviewed together with PR #[92](https://github.com/isomerpages/isomercms-backend/pull/92) on the backend.
This PR modifies the behavior of the `Settings` layout save handler so that only fields which have been changed are sent in the request. The payload we send consists of three attributes: `configSettings`, `footerSettings`, and `navigationSettings`. For example, if only the `title` field has been changed, then the payload sent with the request is:
```
{
configSettings: {
title: <new title>
},
footerSettings: { },
navigationSettings: { },
}
```
Previously, we would send all state fields, regardless of whether the fields have changed in value. The problem is that this results in …

feat: send only settings field which have been changed

---

src/components/ComponentSettingsModal.jsx
src/components/FormFieldMedia.jsx
src/components/OverviewCard.jsx
src/layouts/Home.jsx
src/layouts/Images.jsx
src/layouts/Workspace.jsx
src/styles/isomer-cms/elements/card.scss
src/utils.js

This PR fixes the issue where private repos did not show up on the list of available sites. The reason for this was the scope of our oauth token, which has been changed in this PR.
In addition, this PR also resolves some misc UI bugs.
- Resolves https://github.com/isomerpages/isomercms-frontend/issues/301 (in conjunction with PR https://github.com/isomerpages/isomercms-frontend/pull/299)
- Clarify what unlinked pages are in workspace
- Add divider between unlinked page and categories when moving pages
- Addresses most of https://github.com/isomerpages/isomercms-frontend/issues/302
- Success toast when changing images in a form field
- Check for existence of images in image layout
- Expand clickable area for dropdown chevron
- Prevents automatic redirection into newly created file for …

Fix/private repo access and misc UI bug fixes

---

src/templates/homepage/HeroSection.jsx

fix: updates syntax for background image size

---

src/layouts/EditContactUs.jsx

This PR refactors editContactUs to use hooks. For the motivations and side-effects, refer to https://github.com/isomerpages/isomercms-frontend/pull/334, which has similar changes.

refactor/change editContactUs to use hooks

---

src/layouts/EditPage.jsx
src/layouts/Workspace.jsx

This PR refactors editPage to use hooks, in preparation to store site colours using context instead. In addition, this PR also removes an extra log statement in Workspace.

Refactor: change edit page to use hooks

---

src/layouts/Images.jsx

This PR refactors the `Images` layout into a functional component

refactor: Images layout into functional component

---

src/components/OverviewCard.jsx
src/layouts/EditPage.jsx

This PR fixes small bugs on the CMS:
- For FileMoveDropdown on Workspace, rootName should be "Workspace"
- For Edit Page, deslugifies back button

fix: misc fixes

---

src/components/PageSettingsModal.jsx

fix: third nav title on page creation (#446)

Merge to prod: 10 May 21

---

.env-example
README.md
cypress.json
cypress/integration/homepage.spec.js
cypress/integration/sites.spec.js
package-lock.json
package.json

This PR adds basic end-to-end tests. Please refer to the instructions in the README.md file on how to run Cypress E2E tests.
- Home page should have login button
- Login button should redirect to GitHub login on click
- Sites page should have sites header
- Sites page should allow user to click into a test site repo

chore: set up basic Cypress E2E tests

---

package-lock.json
package.json
src/api.js
src/components/CollectionPagesSection.jsx
src/components/ComponentSettingsModal.jsx
src/components/FileMoveMenuDropdown.jsx
src/components/FolderModal.jsx
src/components/OverviewCard.jsx
src/components/PageSettingsModal.jsx
src/components/folders/FolderContent.jsx
src/components/media/MediaCard.jsx
src/components/media/MediaSettingsModal.jsx
src/constants.js
src/layouts/Folders.jsx
src/layouts/Media.jsx
src/styles/isomer-cms/pages/Media.module.scss
src/utils/validators.js

This PR releases the following changes:
Fix: disable save button for folder modal on error (#468)
fix: duplicate resource title check for example_title (#474)
fix: update save button for resource modal when fileUrl changes (#485)
Feat/front matter changes for resources and pages (#478) 
* Feat: add layout in frontmatter 
* Fix: add resource room name into default permalink
* Fix: use title from frontmatter instead of filename when editing page settings
Feat/moving media (#475) 
* Feat: Moving media between folders
* Feat: Duplicate filename checking on MediaSettingsModal ** (see below)
* Refactor: removes call to retrieve media content in MediaSettingsModal on the frontend during rename operations
* Refactor: generalizes FileMoveDropdownModal to accept path query of any length
* Fix: …

Merge to production: 27 May 2021

---

cypress/integration/pages.spec.js

This PR adds end-to-end tests for the Pages flow.
Note: this PR does not have the following two tests:
- Edit page (will be tackled in a general Editor test suite)
- Rearrange pages and rearrange folders (we will need to do more research on how to run drag-and-drop operations in Cypress)
---

feat: add Pages tests

---

cypress/integration/editPage.spec.js
cypress/integration/files.spec.js
cypress/integration/homepage.spec.js
cypress/integration/images.spec.js
cypress/integration/pages.spec.js
cypress/integration/resourceCategory.spec.js
cypress/integration/resources.spec.js
cypress/integration/settings.spec.js
cypress/integration/sites.spec.js
cypress/support/index.js
cypress/support/medias.js
src/__tests__/RouteSelector.js
src/api.js
src/constants.js
src/contexts/LoginContext.js
src/utils.js
src/utils/contact-us/dataSanitisers.js
src/utils/contact-us/validators.js
src/utils/cspUtils.js
src/utils/dropdownUtils.js
src/utils/leftnavGeneration.js
src/utils/siteColorUtils.js
src/utils/toasts.js
src/utils/validators.js

This PR adds linting fixes that were automatically made by eslint

lint: auto fix with eslint

---

.env-example
src/layouts/Home.jsx

To be reviewed with https://github.com/isomerpages/isomercms-backend/pull/206

fix: oauth flow

---

src/contexts/LoginContext.jsx

This addresses [isomer-product/issues/12](https://github.com/isomerpages/isomer-product/issues/12). To be reviewed with backend PR [isomercms-backend/pull/217](https://github.com/isomerpages/isomercms-backend/pull/217).

fix: update logout to use delete

---

src/styles/isomer-template.scss

This PR fixes a display issue with the editor section in editPage causing by the bumping of easymde from 2.9.0 to 2.15.0.

Fix: adjust simple mde styling

---

src/styles/isomer-template.scss

This PR fixes the styling of the editor when editing pages.

Merge to production - 3 Aug 2021 

---

netlify.toml

Adds HTTP security headers, see [isomer-product/issues/11](https://github.com/isomerpages/isomer-product/issues/11)
This addresses GTA-03-015.

fix: add http security headers

---

src/components/media/MediaModal.jsx
src/layouts/Media.jsx
src/styles/isomer-cms/pages/Content.module.scss

Same as https://github.com/isomerpages/isomercms-frontend/pull/575 except this is to release the changes to staging for VAPT testers

feat: validate and sanitize media files

---

package-lock.json
package.json
src/layouts/EditPage.jsx
src/templates/contact-us/ContactsSection.jsx
src/templates/contact-us/FeedbackSection.jsx
src/templates/contact-us/LocationsSection.jsx

Duplicate of #571 to be merged into develop

[develop] fix: xss

---

src/contexts/LoginContext.jsx

Duplicate of #573 to be merged into develop
Should be merged with corresponding backend PR []()

[develop] fix: update logout to use delete

---

netlify.toml

Duplicate of #553 for merge to develop

[develop] fix: add http security headers

---

netlify.toml
package-lock.json
package.json
src/components/media/MediaModal.jsx
src/contexts/LoginContext.jsx
src/layouts/EditPage.jsx
src/layouts/Media.jsx
src/styles/isomer-cms/pages/Content.module.scss
src/templates/contact-us/ContactsSection.jsx
src/templates/contact-us/FeedbackSection.jsx
src/templates/contact-us/LocationsSection.jsx

This PR contains the following changes:
-  VAPT fixes
- Validating and sanitizing media files (https://github.com/isomerpages/isomercms-frontend/pull/575)
- Fix xss (https://github.com/isomerpages/isomercms-frontend/pull/584)
- Use delete on logout endpoint (https://github.com/isomerpages/isomercms-frontend/pull/583)
- Add http security headers (https://github.com/isomerpages/isomercms-frontend/pull/582)

Merge to production - 12 Aug 2021

---

src/layouts/EditPage.jsx
src/layouts/EditPageV2.jsx

[hotfix to master] Allow iframe objects in EditPage

---

README.md
netlify.toml
src/layouts/Settings.jsx

This PR contains the following changes:
- E2E authentication setup (https://github.com/isomerpages/isomercms-frontend/pull/600)
- Description field in settings (https://github.com/isomerpages/isomercms-frontend/pull/613)

Merge to prod: 16 Sept 2021

---

src/hooks/pageHooks/useUpdatePageHook.jsx
src/layouts/EditPageV2.jsx

This PR contains the following changes:
- Handling 409 errors for conflicting page edits (https://github.com/isomerpages/isomercms-frontend/pull/636)

Merge to production (23 Sept 2021)

---

src/layouts/Settings.jsx
src/utils/validators.js

This PR adds support for telegram and tiktok social links, along with the appropriate validation.
This PR also expands the social link validation to allow for custom regex, which both telegram and tiktok require.

Feat: add telegram and tiktok socials

---

src/styles/isomer-template.scss

Hotfix to master: update fonts for span

---

src/layouts/Sites.jsx

Remove banner from production site as it is past 31st March.
Delete banner. Still keeping banner component in until Chakra/Design system is in and we can use theirs

chore(sites): remove banner

---

src/layouts/screens/DirectoryCreationScreen.jsx

previously, a `return` was missing.
add it back

fix(directorycreationscreen): add missing return

---

src/components/DirectoryCreationModal/DirectoryCreationModal.jsx
src/components/DirectorySettingsModal/DirectorySettingsModal.jsx
src/components/MediaSettingsModal/MediaSettingsModal.jsx
src/components/PageSettingsModal/PageSettingsModal.jsx
src/components/media/MediaModal.jsx
src/hooks/directoryHooks/useCreateDirectoryHook.jsx
src/hooks/directoryHooks/useUpdateDirectoryHook.jsx
src/hooks/directoryHooks/utils.js
src/hooks/mediaHooks/useCreateMediaHook.jsx
src/hooks/mediaHooks/useUpdateMediaHook.jsx
src/hooks/mediaHooks/utils.js
src/hooks/pageHooks/useCreatePageHook.jsx
src/hooks/pageHooks/useUpdatePageHook.jsx
src/hooks/pageHooks/utils.js
src/layouts/EditPage.jsx
src/layouts/ResourceRoom.jsx

This PR fixes an issue where files/folders with trailing whitespace were causing files/folders to not show up properly on the cms. We have opted to strip trailing whitespace from file/folder names to resolve this issue. Resolves https://github.com/isomerpages/isomercms-frontend/issues/839

Fix: trim whitespace

---

cypress/integration/editPage.spec.js
cypress/integration/files.spec.js
cypress/integration/resources.spec.js
cypress/integration/settings.spec.js
src/components/DeleteWarningModal.jsx
src/components/LoadingButton/LoadingButton.tsx

This PR refactors `LoadingButton` and fixes/deletes old e2e.
1. refactored `LoadingButton` so that we don't use `useEffect`. This PR also fixes some e2e tests by changing the selection code to select button containing the text; this is to avoid selecting the `p` element containing the text.

ref(design-system): fix e2e tests

---

package-lock.json
package.json

bump node-sass version to 4.14 so that release builds properly (see #898 on 404)

fix(package): bump node-sass to 4.14

---

src/routing/RouteSelector.jsx

Duplicate of https://github.com/isomerpages/isomercms-frontend/pull/904

Fix/add GitHub warning

---

src/components/Card/Card.tsx
src/components/Sidebar/Sidebar.tsx
src/layouts/Folders/Folders.tsx
src/layouts/Folders/components/FolderBreadcrumb.tsx
src/layouts/ResourceCategory/ResourceCategory.tsx
src/layouts/ResourceCategory/components/ResourceCard.tsx
src/layouts/ResourceCategory/components/ResourceCategoryBreadcrumb.tsx
src/layouts/ResourceRoom/components/ResourceBreadcrumb.tsx
src/layouts/Workspace/Workspace.tsx
src/layouts/utils.ts
src/theme/components/Card.ts
src/types/directory.ts

see [here](https://docs.google.com/document/d/1EreGS8X1uIOgMrl7yXDF4jCprsIQ25BTVmyGLpT5P9k/edit#) under UI fixes.
1. change copy
2. change colours

fix(v1.5): UI fixes

---

src/components/Sidebar/Sidebar.stories.tsx
src/components/Sidebar/Sidebar.tsx
src/contexts/LoginContext.tsx
src/routing/ProtectedRoute.jsx
src/routing/RedirectIfLoggedInRoute.jsx

This PR fixes a minor bug involving the logout button on the sidebar not working. This PR adds the onClick event back to the button.
It also refactors the existing LoginContext component to typescript, so as to allow the storybook component for the sidebar to work properly.

Fix: add logout hook to sidebar button

---

src/components/PageSettingsModal/PageSettingsModal.jsx

See #986 for a brief overview of the issue.
Also, as ogp design system is now part of the codebase, we should shift towards using chakra ui and so some of the old `FormXxx` components have been replaced by the respective design system component.
Closes #986
1. replace handwritten modal components and styling with chakra modal components
2. replace old `FormXxx` components with ogp design system components

fix(pagesettingsmodal): use chakra modal and form components

---

src/layouts/Home.tsx

This PR introduces the login acknowledgement on the existing login screen.

Feat: add acknowledgement on old login screen

---

src/components/Sidebar/Sidebar.tsx
src/hooks/settingsHooks/useGetResourceRoomName.ts
src/layouts/Folders/Folders.tsx
src/layouts/ResourceCategory/ResourceCategory.stories.tsx
src/layouts/ResourceCategory/ResourceCategory.tsx
src/layouts/ResourceCategory/components/ResourceCategoryBreadcrumb.tsx
src/layouts/ResourceRoom/ResourceRoom.stories.tsx
src/layouts/ResourceRoom/ResourceRoom.tsx
src/mocks/constants.ts
src/mocks/utils.ts
src/services/DirectoryService/DirectoryService.ts
src/types/directory.ts

see #980 for an overview of the problem
1. write stories for `ResourceRoom` and `ResourceCategory`
2. minor fixes (explicitly specifying last breadcrumb color/add skeleton height etc)

ref(storybook): add resources stories

---

src/components/Footer/Footer.tsx
src/layouts/Settings/AnalyticsSettings.tsx
src/layouts/Settings/Settings.stories.tsx
src/layouts/Settings/Settings.tsx
src/mocks/constants.ts
src/mocks/utils.ts

see #980 for an overview
1. add settings stories

ref(storybook): add settings stories

---

src/utils/validators.js

Fix failing CI/CD during to eslint rules issue in develop due to #1011

fix(validators): fix eslint issues

---

src/components/DirectorySettingsModal/DirectorySettingsModal.jsx
src/layouts/Media/Media.stories.tsx
src/layouts/Media/components/ImagePreviewCard.tsx
src/mocks/constants.ts
src/mocks/utils.ts

follow up to #1012 - this PR adds stories for `Media`.

ref(media): add stories for media tab

---

src/layouts/Workspace/Workspace.tsx

Fix bug for create page button for workspace

fix(workspace): create page button fix

---

cypress/e2e/editPage.spec.ts
cypress/e2e/workspace.spec.ts

Some of the `<button/>` changed to `<a/>`, which caused some tests to fail

fix(workspacespec): fix flaky tests

---

src/hooks/settingsHooks/useGetSiteUrl.ts
src/layouts/ReviewRequest/components/PublishedModal/PublishedModal.tsx
src/layouts/SiteDashboard/SiteDashboard.tsx
src/layouts/Workspace/Workspace.tsx
src/services/ReviewService.ts

see #1109
Closes #1109
Use latest `/siteUrl` endpoint provided

fix(rr): update site url endpoint

---

.github/mergify.yml

related to #745, this adds the stale PR rule back.

chore(mergify): add rule for stale PRs

---

src/layouts/ReviewRequest/components/RequestOverview/RequestOverview.tsx

Waiting on BE PR to be approved, so we have to hide buttons for now
add `display="none"`

chore(review overview): hide buttons

---

src/components/Header.jsx
src/contexts/LoginContext.tsx
src/routing/ProtectedRoute.tsx

1. Header gets url from params, but none is passed in
2. no await for routes

fix(app): hotfixes for header + routes

---

.github/workflows/chromatic.yml

fixed formatting for the chromatic workflow - had additional indent ._.
add indent

fix(chromatic): fixed formatting

---

cypress/e2e/folders.spec.ts

E2E tests in folders.spec are failing. This fixes them. 
Closes IS-65

fix(folders.spec): pass test cases

---

src/hooks/collaboratorHooks/useAddCollaboratorHook.ts
src/hooks/collaboratorHooks/useDeleteCollaboratorHook.ts

collaborator number doesnt update 
Closes is163
invalidate query

fix(collaborators): ui not updating latest number

---

package-lock.json
package.json

This PR updates datadog-ci to resolve vulnerabilities.

chore: update datadog-ci

---

.github/workflows/chromatic.yml

Chromatic builds are failing, but due to the [nature of triggered workflows only working once I merge to dev](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment), I dont have a good way to test if this code changes work. will need to monitor post merge. 
add env var

fix(chromatic.yml): fix failing workflows

---

src/components/DirectoryCreationModal/DirectoryCreationModal.jsx
src/components/EmptyArea.tsx
src/hooks/directoryHooks/useDeleteDirectoryHook.jsx
src/layouts/ResourceRoom/ResourceRoom.tsx
src/layouts/Workspace/components/UngroupedPages.tsx
src/layouts/Workspace/components/WorkspaceFolder.tsx

This PR is a follow up to #1352 (a list of copy changes that design wanted). Some of the changes were accidentally in that branch were not pushed, thus this PR. 
Change copy.

Fix: Copy Changes

---

src/components/FeedbackModal/FeedbackModal.tsx

cannot build on `staging` cos of import order (see [here](https://app.netlify.com/sites/staging-isomercms-frontend/deploys/64cb4e350f4db40008719b2c)). 
auto format to correct order - force push to `staging` [works](https://app.netlify.com/sites/staging-isomercms-frontend/deploys/64cb508dd435a90008aa6621)

fix(import): update order

---

cypress/e2e/editPage.spec.ts
cypress/e2e/folders.spec.ts
cypress/e2e/notifications.spec.ts
cypress/e2e/resourceCategory.spec.ts
cypress/e2e/workspace.spec.ts
cypress/fixtures/messages.ts

This PR fixes several e2e test selectors which were looking for the wrong string/colour. Tested on local against staging.

fix: selectors

---

src/contexts/SiteLaunchContext.tsx
src/layouts/SiteLaunchPad/SiteLaunchPad.stories.tsx
src/layouts/SiteLaunchPad/SiteLaunchPad.tsx
src/layouts/SiteLaunchPad/components/SiteLaunchCheckList.tsx
src/layouts/SiteLaunchPad/components/SiteLaunchDisclaimer.tsx
src/types/siteLaunch.ts

The flows for site launch should be different for new and old domains. This PR changes the storybook to allow for that functionality. 
Modify the storybooks to show these two distinct flows.
https://github.com/isomerpages/isomercms-frontend/assets/42832651/3bb7c487-2eeb-454d-bb1c-85f889f90bd1

Is 346 fe UI flow for new domain and old domains

---

.github/workflows/chromatic.yml

#1406 did not fully fix chromatic. We get this error during the comment based dev. 
Trying out the solution [here](https://github.com/actions/checkout/issues/331#issuecomment-925405415) instead.  (Testing is a pain cuz I can only test this when it goes into dev)

fix(chromatic): attempt to get full commit hist

---

src/layouts/SiteLaunchPad/components/SiteLaunchCheckList.tsx

Team feedbacked that `I need support` button was confusing . 
Moved it as a text instead. 
- Details ...
**BEFORE**:
**AFTER**:

fix(sl checklist): i need support copy

---

.github/workflows/chromatic.yml

This change reverts the comment-based triggering of Chromatic builds to 78cd88d465220f84e92ac3d01290bda69bbc364e, but updated for dependency upgrades.

fix(chromatic): revert comment-based trigger

---

src/__tests__/RouteSelector.spec.jsx
src/layouts/FeatureFlaggedNavBar.tsx
src/layouts/LegacyEditNavBar.jsx
src/routing/RouteSelector.jsx

This PR adds a feature flag for the new nav bar to only show up on ogp sites.

chore: add feature flag for new nav bar

---

src/components/FormFieldMedia/FormMediaInput.jsx
src/layouts/EditHomepage/EditHomepage.jsx
src/layouts/components/Editable/Editable.tsx
src/layouts/components/Homepage/HeroBody.tsx
src/layouts/components/Homepage/HeroHighlightSection.tsx

See the restyling notion page [here](https://www.notion.so/opengov/Restyling-feedback-3a4dc84523ff44529e0644ae85b4e0ca?pvs=4), specifically those that were tagged to me
Mostly style fixes + copy changes, should be self explanatory

fix(homepage): various styling fixes 

---

src/templates/homepage/HeroSection/HeroSideLayout.tsx

dup of [this](https://github.com/isomerpages/isomerpages-template/pull/318) to FE
same as #1523 - used the hero banner in this PR for that SS

ref(hero-template): use breakpoints

---

src/layouts/components/Homepage/HeroBody.tsx
src/styles/isomer-template/components/homepage/_hero.scss
src/styles/isomer-template/theme/_colors.scss
src/styles/isomer-template/theme/_layout.scss
src/templates/homepage/HeroSection/HeroCenteredLayout.tsx
src/templates/homepage/HeroSection/HeroDropdown.tsx
src/templates/homepage/HeroSection/HeroImageOnlyLayout.tsx
src/templates/homepage/HeroSection/HeroSection.tsx
src/templates/homepage/HeroSection/HeroSideLayout.tsx

Hero section has some style nits
Update styling
**Notes**
- template changes coming in another PR 
- changes made to **template** components here (for preview) need to dup to template repo

fix(hero): update panel styles for hero section

---

src/styles/isomer-template/components/homepage/_hero.scss
src/styles/isomer-template/theme/_breakpoints.scss
src/styles/isomer-template/theme/_display.scss
src/styles/isomer-template/theme/_layout.scss
src/templates/homepage/HeroSection/HeroInfoboxDesktop.tsx
src/templates/homepage/HeroSection/HeroInfoboxMobile.tsx

**NOTE: build fails but is fixed [here](https://github.com/isomerpages/isomercms-frontend/pull/1548)**
dup of [this](https://github.com/isomerpages/isomerpages-template/pull/328) to frontend
copy paste styling etc to frontend

refactor(hero): duplicate changes from template

---

src/components/media/MediaModal.jsx

This PR fixes an issue introduced by the earlier image file upload behaivour - the functionality was breaking for new files/images uploaded while creating pages/resources.

fix: page setting file/image behaviour

---

src/layouts/EditContactUs.jsx

Closes IS-544.
- Smooth scrolling has been added to the contact us page.
https://github.com/isomerpages/isomercms-frontend/assets/27919917/9044833b-13ad-41a7-b9b8-89e9c53558b1
*None*

feat(contactus): add smooth scrolling

---

src/components/media/MediasSelectModal.jsx
src/layouts/Media/Media.tsx

fix(media): add limit

---

src/components/media/MediasSelectModal.jsx

Using wrong var
Use correct var >_<

fix(mediasselectmodal): update dir name

---

src/hooks/directoryHooks/useListMediaFolderFiles.ts
src/hooks/mediaHooks/useCreateMediaHook.jsx
src/hooks/mediaHooks/useDeleteMediaHook.jsx
src/hooks/mediaHooks/useUpdateMediaHook.jsx
src/hooks/moveHooks/useMoveHook.jsx

we are refetching too fast from github and getting stale data
add a fake delay zz

chore(hooks): add timeout

---

src/layouts/EditHomepage/EditHomepage.jsx

- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:

fix: errors indexes

---

src/components/pages/PagePreview.jsx
src/layouts/EditPage/MarkdownEditPage.tsx
src/layouts/EditPage/TiptapEditPage.tsx
src/layouts/LegacyEditPage.jsx

some styles are abit off cos of rebase sadge
add back :(

style(pages): update styles

---

src/components/PageSettingsModal/PageSettingsModal.tsx
src/components/PageSettingsModal/ResourcePageSettingsModal.tsx

- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:

fix(page-settings): remove toggle if feature not on

---

src/hooks/pageHooks/useUpdatePageHook.jsx
src/layouts/EditPage/MarkdownEditPage.tsx
src/layouts/LegacyEditPage.jsx

- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:

fix(editpage): update warning modal trigger

---

src/components/Header/StatusBadge.tsx
src/constants/featureFlags.ts
src/hooks/useGetStagingStatus.ts
src/layouts/layouts/SiteEditLayout/SiteEditHeader.tsx
src/layouts/layouts/SiteViewLayout/SiteViewHeader.tsx
src/routing/ProtectedRoute.tsx
src/services/StagingBuildService.ts
src/types/featureFlags.ts

Not sure if this best design here, but added this at the react query level cuz i dowan ping be 
At the compnent level, returning <></> if growthbook returns false. 
When GB is on:
When GB is off: 
Note lack of be ping

fix(api): dont ping be every 5 sec if ! whitelist

---

src/components/Header/StatusBadge.tsx

Fixed. Design havent gvivne green check yet, will prioritise + make design changes if needed on monday. 
shouldnt flicker on refresh (which was solved using portal, using only useMemo did not solve it)

fix(badge): flickering issue

---

src/layouts/EditPage/EditPage.tsx

Took out alt text modal by accident
Closes IS-757
Add prop back in

refactor(editpage): add alt text modal

---

package-lock.json
package.json
src/components/media/MediasSelectModal.jsx

This PR modifies the styling of the Select media modal seen in edit pages, as well as the settings modal of various pages and the settings page (via the insert image modal).
[figma](https://www.figma.com/file/7OtNYkc4s9BkFk05ConEbd/%E2%AD%90-V1.5-Master?type=design&node-id=16627%3A9465&mode=design&t=aSyMe69nzapWNYvm-1)
Resolves IS-687
Before:
After:
Tests:

chore: update select media modal

---

src/layouts/EditPage/EditPage.tsx
src/layouts/EditPage/TiptapEditPage.tsx
src/layouts/components/Editor/components/LinkBubbleMenu.tsx
src/layouts/components/Editor/extensions/Image/Image.tsx
src/layouts/components/Editor/extensions/Image/ImageView.tsx
src/layouts/components/Editor/extensions/Image/index.ts
src/layouts/components/Editor/extensions/index.ts

IS-713 + is-782 + is-783
https://github.com/isomerpages/isomercms-frontend/assets/42832651/9b42566c-ce36-4478-b9b3-5f98917fd980

IS-782-Editor-File-text-always-comes-out-as-file-regardless-of-text

---

src/layouts/EditPage/MarkdownEditPage.tsx

Fixes copy + layout changes on preview new editor modal and also changes scrolling to internal instead of external.
Also resolves is-785
Before:
After:

is-714/chore: add copy and layout changes

---

src/layouts/EditPage/EditPage.tsx
src/layouts/components/Editor/components/LinkBubbleMenu.tsx

Put default placeholder name 'File'.  
INput validation for change link

fix(input): empty input validation

---

src/layouts/EditPage/EditPage.tsx
src/layouts/components/Editor/Editor.tsx
src/layouts/components/Editor/components/ImageBubbleMenu.tsx

fix(images): ability to change img

---

src/layouts/EditPage/EditPage.tsx
src/layouts/EditPage/TiptapEditPage.tsx
src/layouts/components/Editor/extensions/Details/IsomerDetailGroup.ts
src/layouts/components/Editor/extensions/Details/IsomerDetailGroupView.tsx
src/layouts/components/Editor/extensions/Details/IsomerDetails.ts
src/layouts/components/Editor/styles.scss
src/layouts/components/EditorAccordionDrawer/EditorAccordionDrawer.tsx
src/layouts/components/EditorCardsDrawer/EditorCardsDrawer.tsx
src/layouts/components/EditorDrawer/EditorDrawer.tsx
src/layouts/components/EditorDrawer/index.ts
src/layouts/components/MiniDrawer/MiniDrawer.tsx
src/layouts/components/MiniDrawer/index.ts
src/styles/isomer-cms/pages/Editor.module.scss
src/types/editPage.ts

Add background colours 
Note: quite a bit of code was taken from @dcshzj's PR here #1705. (ps still learning how use graphite, will attempt to cherry pick in the future) 
The toggle is still a bit flaky, will be documenting in a notion doc
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/4JosFH65rhzwIvkZw2J6/33ec7c00-6253-4ff9-b1a8-abc1cc25dcab.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/4JosFH65rhzwIvkZw2J6/33ec7c00-6253-4ff9-b1a8-abc1cc25dcab.mov">Screen Recording 2023-11-28 at 4.47.19 PM.mov</video>

feat_background_toggling

---

src/layouts/components/Editor/extensions/FormSG/FormSGView.tsx
src/layouts/components/Editor/extensions/Iframe/IframeView.tsx
src/layouts/components/Editor/extensions/Instagram/InstagramView.tsx

The old embed view is very different from how the rest of our editor looks like due to it not using our theme colours/styling.
Change the design to a design approved design!

refactor(tiptap): change embeds view

---

src/styles/index.scss
src/styles/isomer-cms/elements/base.scss
src/styles/isomer-cms/pages/Editor.module.scss
src/styles/isomer-template/theme/_text-styles.scss

Updates styles used for the preview components. To be reviewed in conjunction with https://github.com/isomerpages/isomerpages-template/pull/365.
Should not be merged until rollout to all users.

chore: swap preview fonts

---

src/components/Sidebar/Sidebar.tsx

The help link on the sidebar is incorrect.
**Bug Fixes**:
- The link to the help form has been updated.
*None*

chore(sidebar): update link to issue reporting form

---

src/layouts/EditPage/MarkdownEditPage.tsx
src/layouts/LegacyEditPage.jsx

- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:

fix(preview): update overflow behaviour

---

.github/CODEOWNERS

feat(codeowner): make life easier

---

src/styles/isomer-template/components/_cards.scss

Sync from template: https://github.com/isomerpages/isomerpages-template/pull/371

fix(cards): prevent overflowing of cards by enforcing width

---

src/components/Header.jsx

Fixes spacing issue for page header

fix: header spacing

---

src/layouts/EditPage/MarkdownEditPage.tsx
src/layouts/EditPage/TiptapEditPage.tsx
src/layouts/components/Editor/Editor.tsx

Edit copy regarding new RTE
Refer to [Figma](https://www.figma.com/file/owgl8SFMKQd2jrCJMVrukR/CMS-%7C-Q42023?node-id=1726%3A13659&mode=dev) for design and UI verification. No functional logic changes.

IS-846 fix copy for new rte

---

src/layouts/components/Editor/extensions/Image/Image.ts

We don't allow base64 images but users were able to bypass this restriction by copy-pasting an image encoded in base64.
**Bug Fixes**:
- Prevent users from being able to paste in a base64 image by explicitly not parsing as an image if the paste is a base64 image. [Code was adapted from here](https://github.com/ueberdosis/tiptap/issues/2455#issuecomment-1031597865).
```
```
*None*

fix(tiptap): block usage of base64 images

---

src/layouts/components/Homepage/InfocolsBody.tsx

Bug fix, disable deleting last infobox
https://github.com/isomerpages/isomercms-frontend/assets/42832651/673c0aaf-5ee4-40f2-81e4-af89deaacb20

fix(infocols): should not be allowed to rm last

---

package-lock.json
package.json

To resolve snyk vulnerabilities

chore: update datadog

---

src/hooks/siteDashboardHooks/useGetLinkChecker.ts
src/layouts/LinkReport/LinksReport.tsx
src/layouts/SiteDashboard/SiteDashboard.tsx

design crit 
https://github.com/isomerpages/isomercms-frontend/assets/42832651/9779d002-18e0-4287-a696-ee1198fda841

feat(linkChecker): design changes

---

src/App.jsx

we want to unify `service` tag.
change tag to `isomer`

fix(app): change service to `isomer`

---

package.json

dup of [this](https://github.com/isomerpages/isomercms-backend/pull/1237)

chore(package): update to use `release` command

---

package.json

source maps weren't getting updated with the service tag for fe, which leads to errors not having a good diagnostic
update source map name for service

fix(package): update source maps

---

.github/mergify.yml

duplicate of [backend](https://github.com/isomerpages/isomercms-backend/pull/1328)

fix(mergify): update snyk author to isomeradmin
